### ISSUE TITLE
Grouping Cluster

### ISSUE THREAD

**Issue by hugocroch** [googlemaps/android-maps-utils#100]
I am using the library for one of my project, but I was wondering if it is possible to cluster my marker by group. For example, I want to cluster only markers that are "Friends" and cluster the others who are only "Coworker" and etc... (Maybe not the best example, but I hope that you understand)

My idea was to use multiple ClusterManager but I didn't tried it and don't really know if it is the best solution or even a good solution.

Thanks for the reply.

**Comment by eicm** [comment]
@broady How do you set different related GoolgeMap listeners for two different ClusterManagers simultaneously?

**Comment by ajay-practo** [comment]
@broady I tried it for multiple cluster managers and the listeners are applied only to the latest cluster manager that the listeners are being set to. Could you handle this in the library or atleast suggest a way to handle it ?

**Comment by naddou14** [comment]
Hello,
I have the same problem for using multiple cluster managers. Does any one found a solution for that?
Thank you in advance

**Comment by qthurier** [comment]
Hello,
I'm facing the same problem. I can't figure out how to handle multiple cluster managers. My listeners are applied only to the latest cluster manager. Does anyone have a solution? 
Many thanks.

**Comment by jaayesh** [comment]
Hi qthurier,

Well, I did not find any other solution but to use 'n' cluster manager with associated 'n' cluster renderer. This solution worked for me. All you have to do is to ensure you set data to respective appropriate cluster manager. 
As far as listeners are concerned you can always get respective manager with a bit dirty way, need to use onMarkerClick listener only. Example: At the time of adding Marker to manager ensure you set either title or snippet as "Pizza" and add it to respective manager i.e. PizzaManager. Then upon click of Marker, onMarkerclick will be invoked and there you can check for title/snippet and can retrieve respective manager or renderer.

I know this not at all a good way but thats how it works with this library.

Hope this helps!

**Comment by cheval-2** [comment]
Hi ! i'm facing the same issue, i can't figure out how to manage multiple cluster managers to make cluster groups as we can do in "android-maps-extension".
I'm not sure i understand your solution @jaayesh, which manager's listeners are you binding with the map ? Like @qthurier said if you declare 3 Cluster Manager, you need to bind setOnCameraChangeListener and setOnMarkerClickListener to a manager not 3, so how do you perform your trick ? Maybe a little example would help ? :)
Thanks !

**Comment by Buggyy** [comment]
Any solutions?

**Comment by erichlotto** [comment]
I'm also looking for this

**Comment by yuvarajchavan25** [comment]
For this you can implement OnCameraMoveListener and on moving of zooming of map you can force to clustermanger to make cluster. Like this, 
 if (mClusterManager != null)
                    mClusterManager.cluster();

**Comment by thangkho** [comment]
@jaayesh how to add multi cluster manager in a map? I try with 
mMap.setOnCameraChangeListener(new GoogleMap.OnCameraChangeListener() {
        @Override
        public void onCameraChange(CameraPosition cameraPosition) {
            mClusterManager1.onCameraChange(cameraPosition);
            mClusterManager2.onCameraChange(cameraPosition);
        }
    });
but it can't. Can you share your code add multiple cluster manager?

**Comment by jaayesh** [comment]
What exactly do you mean by, "how to add multi cluster manager in a map?", if you want to update respective cluster manager with respect to map's camera change event, you need to call manager.cluster()

**Comment by JRajer** [comment]
setOnCameraChangeListener is now deprecated. You can use setOnCameraIdleListener.

Calll cluster method on each clusterManager:

```
mMap.setOnCameraIdleListener(new GoogleMap.OnCameraIdleListener() {
             @Override
             public void onCameraIdle() {
                 for (ClusterManager<MarkerClusterItem> cm:clusterManagerList)
                 {
                     cm.cluster();
                 }
             }
         });
```

**Comment by hunterxxx** [comment]
googleMap.setOnCameraIdleListener(new GoogleMap.OnCameraIdleListener() {
            @Override
            public void onCameraIdle() {
                clusterManager.cluster();
                clusterManager2.cluster();
            }
        });

**Comment by ElegyD** [comment]
When using multiple ClusterManager, the listeners are still overwritten by the latest ClusterManager.
```
private lateinit var clusterManagerA: ClusterManager<AItem>
private lateinit var clusterManagerB: ClusterManager<BItem>

override fun onMapReady(googleMap: GoogleMap) {
    clusterManagerA = ClusterManager(this, googleMap)
    clusterManagerA.setOnClusterItemInfoWindowClickListener {
        Log.d(TAG, "clusterManagerA onClusterItemInfoWindowClick")
    }
    clusterManagerA.addItem(AItem())

    clusterManagerB = ClusterManager(this, googleMap)
    clusterManagerB.setOnClusterItemInfoWindowClickListener {
        Log.d(TAG, "clusterManagerB onClusterItemInfoWindowClick")
    }
    clusterManagerB.addItem(BItem())
}
```
Now when I click on the InfoWindow of:
- AItem: Nothing happens
- BItem: It shows the log message

Is there a solution/workaround for this?

**Comment by bolebolo** [comment]
I know this might be late, but it might help someone who encounters this poorly documented issue in the future.

To successfully add **multiple clusters** to Google Maps that work **independently**, the most important and often overlooked step is to add:

    `MarkerManager markerManager = new MarkerManager(gMap);`

You then use this MarkerManager to create your clusters:

    ```
ClusterManager<MyClusterItemA> clusterManagerA = new ClusterManager<>(this, gMap, markerManager);
    ClusterManager<MyClusterItemB> clusterManagerB = new ClusterManager<>(this, gMap, markerManager);
```

Notice that both clusters are created using **the same MarkerManager, and this is essential**. If you create two different MarkerManager instances, only the last ClusterManager you defined (in this case, clusterManagerB) will handle the clicks and other interactions, effectively ignoring the first one.

I'm not 100% sure why this happens, but my educated guess, which I’m about 90% confident in, is that when you create a ClusterManager tied to the map without passing a MarkerManager like this:

   ` ClusterManager<MyClusterItemA> clusterManagerA = new ClusterManager<>(this, gMap);`

it defaults to creating a new MarkerManager, as can be seen in the constructor:

        ```
public ClusterManager(Context context, GoogleMap map) {
        this(context, map, new MarkerManager(map));
    }
```

This means the previous MarkerManager associated with the map is effectively replaced (as indicated by new MarkerManager(map)), capturing all click events.

However, if you use the constructor where you pass an existing MarkerManager, then it simply adds the clicks from the new cluster to the same MarkerManager. Here’s the constructor code for reference:

        ```
public ClusterManager(Context context, GoogleMap map, MarkerManager markerManager) {
            mMap = map;
            mMarkerManager = markerManager;
            mClusterMarkers = markerManager.newCollection();
            mMarkers = markerManager.newCollection();
            mRenderer = new DefaultClusterRenderer<>(context, map, this);
            mAlgorithm = new ScreenBasedAlgorithmAdapter<>(new PreCachingAlgorithmDecorator<>(
                    new NonHierarchicalDistanceBasedAlgorithm<T>()));
            mClusterTask = new ClusterTask();
          
    
      mRenderer.onAdd();
    }
```

So, the key takeaway is to create a shared MarkerManager before creating multiple clusters and pass that same MarkerManager to each ClusterManager.
