### ISSUE TITLE
v2.2.6 release was missing compiled code

### ISSUE THREAD

**Issue by barbeau** [googlemaps/android-maps-utils#1016]
#### Summary

Reported in https://github.com/googlemaps/android-maps-utils/pull/1008#issuecomment-952298163:

>I took your sample code and tested it and found indeed there is something weird going on here, but it's actually a problem with the v2.2.6 build itself.
>
>I was able to reproduce what you were seeing with v2.2.6, but not if I copied the `MapObjectManager` and `MarkerManager` source code directly to my app, unmodified. I then tested v2.3.0 and this version works as expected. Using the debugger again on v2.2.6, I see that the `mObjects` variable is actually a `HashSet` still!
>
>For some reason, the v2.2.6 build that [my PR's changes were released in](https://github.com/googlemaps/android-maps-utils/pull/972#issuecomment-920307699) does not have the change in [the decompiled binary aar](https://search.maven.org/artifact/com.google.maps.android/android-maps-utils/2.2.6/aar)! It is in the source code jar though, which is even more confusing. And the change is in the v2.3.0 binary.
>
>![Screenshot 2021-10-26 142228](https://user-images.githubusercontent.com/2053817/138955620-37fb42f2-33b7-4655-96eb-7c4f54fe1c5e.png)

So v2.2.6 release didn't contain the compiled code that it should have, although v2.3.0 seems ok.

#### Expected behavior

All changes in main project branch should be included in releases

#### Observed behavior

>PR's changes released in https://github.com/googlemaps/android-maps-utils/pull/972#issuecomment-920307699 does not have the change in [the decompiled binary aar](https://search.maven.org/artifact/com.google.maps.android/android-maps-utils/2.2.6/aar).
>
>It is in the source code jar though, which is even more confusing. And the change is in the v2.3.0 binary.

**Comment by arriolac** [comment]
Going to close this issue as we cannot update an already existing live version. For anyone finding this issue, see [releases](https://github.com/googlemaps/android-maps-utils/releases) and make sure you are using the latest version instead.
