### ISSUE TITLE
Bad performance when zoom to LatLng which is different LatLng  default (51.503186, -0.126446) in zoom level 17

### ISSUE THREAD

**Issue by lethanhtan89** [googlemaps/android-maps-utils#1028]
When I init Map, I set default zoom is 15f, And I zoomed to 17f. It is possible with Default location (LatLng(51.503186, -0.126446)).
But when I change to another LatLng that is different from the default Location. It is rendered very slow when I zoom to 17f.

How can I fix this issue?

Thanks for the helping.

**Comment by barbeau** [comment]
@lethanhtan89 Have you tried using the `animateCamera()` method that includes the `durationMs` parameter?

https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap#animateCamera(com.google.android.gms.maps.CameraUpdate,%20int,%20com.google.android.gms.maps.GoogleMap.CancelableCallback)

The `durationMs` controls how quickly the camera pans and zooms from one location to another, smaller values having faster movement.

**Comment by lethanhtan89** [comment]
@barbeau I think It is not related to **animateCamera()** because I only use zoom events.

When I init Map, I set to zoom the default is 15f, I double touch map, it increases to 16f, and I continue to double touch, the zoom default is 17f, And the map is rendered very slow with zoom level 17, And I am in zoom level 17 when I drag it's also pretty slow.

Thank you for your help.

**Comment by barbeau** [comment]
@lethanhtan89 Thanks for clarifying. Which Google Maps SDK version are you using? This sounds like more of a Maps SDK issue than android-maps-utils library issue. If so, I'd suggest opening an issue for that component here:
https://issuetracker.google.com/issues/new?component=188870&template=788712

...and then please link to it from here so others with a similar problem can find it.
