### ISSUE TITLE
Overlapping geojson feature click handling.

### ISSUE THREAD

**Issue by AlfredAfutu** [googlemaps/android-maps-utils#1052]
I'm currently facing an issue where geojson feature click events are being propagated randomly to overlapping features. Is there a way i can set the zIndex on the different geojson features so that only the top most polygon receives the click event in the case where there are overlappings?

**Comment by AlfredAfutu** [comment]
I found out that you can set zIndex on the GeojsonPolystyle object and the value has to correlate to the order of the polygon. For example the top most polygon should have the highest zIndex value. Am i right?

**Comment by sivansaitowitz** [comment]
@AlfredAfutu I'm facing the opposite as I need to get the click events for all overlapping features, any advice how did you achieve this?

**Comment by AlfredAfutu** [comment]
I would recommend setting the zindex on the GejsonPolygonStyle object of each of the features. The polygon with the highest zindex would be the one that gets the click event when the overlapping area is clicked. So if you want all polygons to get the click event when the overlapping area is clicked, I would try setting the same zindex for all of them
