### ISSUE TITLE
[MapsInitializer LATEST] custom info window does not hide on selected other marker

### ISSUE THREAD

**Issue by kefahB** [googlemaps/android-maps-utils#1053]
#### Summary

I use the new maps renderer with `MapsInitializer`  `play-services-maps = "18.0.2"`  when I set a custom info window the info window appear as expected but when I select another one the last does not disappear ! 

This behavior is with LATEST only, the LEGACY one work as expected

I use Nativescript as a framwork.

#### Expected behavior

When I select a marker, the infow window related showing up and disappear when I select another marker and there related info window appear (One at time)

#### Observed behavior

The info window appear but does not disappear when I select another marker to let place for a new one (Multiple info window at the same time)

#### Environment details

1. Samsung note 10+ 
2. android 30
3. Nativescript 8

**Comment by arriolac** [comment]
Looks like you've opened an issue about this on the [Issue Tracker](https://issuetracker.google.com/issues/214115040) already—thanks! Since this is a bug with the SDK itself and not this utility library, that would be the best place to receive support.
