### ISSUE TITLE
setOnFeatureClickListener for overlapping features

### ISSUE THREAD

**Issue by sivansaitowitz** [googlemaps/android-maps-utils#1056]
setOnFeatureClickListener is returning the highest z-index feature that was clicked
Is it possible to add support to get all overlapping features in the clicked area?

**Comment by kikoso** [comment]
@sivansaitowitz , `setOnFeatureClickListener` does not return any feature. Instead, it sets a single click listener for the entire GoogleMap object, which will be called with the corresponding Feature object when an object on the map is clicked.

What do you mean instead?

**Comment by sivansaitowitz** [comment]
What I mean was for the case the click was made on an area which has few objects overlapping. In this case the object with the highest z index was returned in the listener. I've implemented it myself with a click listener on the entire map + iteration on all objects. Thanks
