### ISSUE TITLE
I cant find PolyUtil class in code.

### ISSUE THREAD

**Issue by kst-kjh** [googlemaps/android-maps-utils#1104]
Up to version 2.3.0, the PolyUtil class can be found and used in the code, but as of version 2.4.0, the PolyUtils class cannot be found in the code.

If you download the library source, it's obviously there, but I can't find it in the code.
(/library/src/main/java/com/google/maps/android/PolyUtils.java)

**Comment by kikoso** [comment]
Hi @kst-kjh .

I have verified this, and the PolyUtils are definitely included in the artifact in Maven.

<img width="347" alt="Screenshot 2022-12-05 082116" src="https://user-images.githubusercontent.com/903097/205576955-877983a8-b212-4335-a818-52fa67eda23d.png">


Could you check if this is an issue with your cache?

Thanks
