### ISSUE TITLE
Could not find com.google.maps.android:android-maps-utils:2.4.0

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#1105]
The title says it all. I've been trying every other day since the 2.4.0 version was released. I've invalidated caches in Android Studio and clean/rebuild/make... all the ways to previously get around issues like this.

Is the new 2.4.0 library available as indicated in the documentation?

**Comment by wangela** [comment]
v2.4.0 has been uploaded to Maven. Sorry for the long delay - our automated publish process failed.
