### ISSUE TITLE
Cluster icon color by cluster

### ISSUE THREAD

**Issue by martppa** [googlemaps/android-maps-utils#1121]
Hello everyone.

I think it could be interesting to overload `getColor` method to allow developers define a color based on clusters and not only on bucket size. In my case, items in cluster are more relevant when defining a color. As the PR readme states, I should share with you the new feature.

I am pretty sure this might be interesting to lot of people.

**Comment by kikoso** [comment]
Hi @martppa,

As you say, the color is currently determined based on the bucket size:

```
 protected int getColor(int clusterSize) {
        final float hueRange = 220;
        final float sizeRange = 300;
        final float size = Math.min(clusterSize, sizeRange);
        final float hue = (sizeRange - size) * (sizeRange - size) / (sizeRange * sizeRange) * hueRange;
        return Color.HSVToColor(new float[]{
                hue, 1f, .6f
        });
    }
```
    
  How a change could be useful? I could imagine a method that receives an array of colors, and those get applied sequentially to the clusters (or maybe passing together a map of colors and cluster sizes).
