### ISSUE TITLE
Unable to use library with Google Maps Mobile SDK for Work: Android 

### ISSUE THREAD

**Issue by jonathanrandev** [googlemaps/android-maps-utils#113]
Hi,
I'm switching the implementation of my GoogleMaps to to use Google Maps Mobile SDK for Work. This involves switching to imports from com.google.android.m4b.maps

My problem is that the ClusterItem and ClusterManager (among other things), require object instances from com.google.android.gms.maps.

Is there some way i can get this done?

**Comment by INRIX-Owais-Ali** [comment]
Bump. It's easy enough to compile the library from source, but it would be nice to have this published so that we can just depend on a Maven dependency.

**Comment by tomoiti** [comment]
Same here...

**Comment by souissihaythem** [comment]
I have the same problem, any solution?

**Comment by rijvirajib** [comment]
As of now, documentation for Google Maps Android's android-maps-utils for M4B is outdated.

Any word on workarounds or fixes?

Things like won't work because there is no documentation that I can see.

```
mClusterManager.getOnClusterItemClickListener().onClusterItemClick(m, mClusterManager.getRenderer().getMarker(m));
```

**Comment by 0h-takaya** [comment]
I am in trouble because ClusterManager can not be used in Premium Plan.
I want you to respond quickly.

**Comment by rijvirajib** [comment]
Not sure if you'll get an answer but I've essentially used the source code and modified things to make ClusterManager work - this is not *good enough* for a PR because it breaks other functionality.

**Comment by DerrickMilford** [comment]
Is there any Update with regards to this? We are forced to use the M4b library but without the utilities the normal packed has.
