### ISSUE TITLE
Missing animation when overridden shouldRenderAsCluster uses zoom level to decide (part 2)

### ISSUE THREAD

**Issue by blurpy** [googlemaps/android-maps-utils#1174]
I'm creating a new issue, since #408 was closed by the stale bot some time ago without me noticing, and I can't see a way to reopen, and no contributors are following the issue.

The easiest would probably be to reopen that issue to get all the context on one place, instead of trying to copy it into this one. Then this can be closed.

**Comment by kikoso** [comment]
Hi @blurpy .

I have re-opened the previous issue. Since it has already an allocated discussion, it might be better for folks to follow the context there (closing this one also).

Thanks!

Enrique

**Comment by blurpy** [comment]
@kikoso excellent, thank you!
