### ISSUE TITLE
Adding a utility library to check Street View availability

### ISSUE THREAD

**Issue by kikoso** [googlemaps/android-maps-utils#1201]
Right now, if we try to query a StreetMaps VIew location and it is not available, Google Map crashes (it returns a null value when null is not allowed).

A utility library could query the general availability of a location by calling the Street Maps View API, and handle it at a different level (returning an exception, a boolean, an enum with the availability of the location...)

See the following branch for a draft solution: https://github.com/googlemaps/android-maps-utils/tree/feat/added_street_view_util

Would you folks be ok with this utility supporting Coroutines? Would you prefer any other async mechanism?

**Comment by wangela** [comment]
This might be of particular interest to developers who use Street View in Germany. The full guidance is at https://issuetracker.google.com/issues/287628235  and this utility helps implement the recommended mitigations by making a free request to check for the availability of Street View at the desired location, before requesting a Street View panorama for it.

@kikoso how about making that branch into a draft PR so people can comment on specific parts?
