### ISSUE TITLE
Add a REQUEST_DENIED value to the StreetMap Utility

### ISSUE THREAD

**Issue by kikoso** [googlemaps/android-maps-utils#1234]
StreetMaps can return a REQUEST_DENIED value when the Google Maps Key has not been properly set.

Adding this value to the StreetMaps Util would allow us to have a better error handling.

**Comment by wangela** [comment]
Documentation about REQUEST_DENIED and other status codes that can be returned: https://developers.google.com/maps/documentation/streetview/metadata#status-codes
