### ISSUE TITLE
Markers color lost in version 0.3.2

### ISSUE THREAD

**Issue by MarionaDSR** [googlemaps/android-maps-utils#126]
If I force version 0.3.2 from my build.gradle file, my markers losts his color on the map. 

Markers that used to be red, are now white a with very light gray text.

BEFORE:
compile 'com.google.maps.android:android-maps-utils:0.3.+' // for markers on maps
![screenshot_2014-10-22-18-14-20](https://cloud.githubusercontent.com/assets/9354336/4739736/f3741bea-5a06-11e4-9e6d-26facfe07dec.png)

AFTER:
compile 'com.google.maps.android:android-maps-utils:0.3.2' // for markers on maps
![screenshot_2014-10-22-18-13-04](https://cloud.githubusercontent.com/assets/9354336/4739740/f8899f1a-5a06-11e4-8245-d78b670164f1.png)

The change of version number on build.gradle file is the only difference between the two images.

The code I use to set the color is:

```
    protected void onBeforeClusterItemRendered(T item, MarkerOptions markerOptions) {
        MyMarker myMarker = (MyMarker) item;
        IconGenerator iconFactory = new IconGenerator(getActivity());
        String title = myMarker.getBubbleTitle(getResources());
        String snippet = myMarker.getBubbleSnippet(getResources(), user);
        int color = myMarker.getBubbleColor(user);
        iconFactory.setStyle(color);
        markerOptions.title(title).snippet(snippet)
                .icon(BitmapDescriptorFactory.fromBitmap(iconFactory.makeIcon(myMarker.getBubbleLabel(getResources()))));
        super.onBeforeClusterItemRendered(item, markerOptions);
    }

    where

    public int getBubbleColor(MyUser user) {
        int color;
        if (user.firstCase) {
            color = IconGenerator.STYLE_RED;
        } else if (user.secondCase) {
            if (user.case2b) {
                color = IconGenerator.STYLE_BLUE;
            } else {
                color = IconGenerator.STYLE_PURPLE;
            }
        } else {
            color = IconGenerator.STYLE_WHITE;
        }
        return color;
    }
```

Thank you
Mariona

**Comment by lucaben** [comment]
I was using different markers with different colours in my custom maps, one colour for each different layer, sometimes also within the layers themselves. The solution that really worked for me was to choose  a uniform style for each layer, and pick a custom icon. Then what is really important, is you have to use the new icons set, not the old one. This problem only happens with maps that were created prior to the introduction of the new icons. Using new icons seems to reset the maps so they are displayed correctly, while the old maps got corrupted at some time with one of the android updates, and they never bothered to fix it nor to post this simple solution on the forum threads that were open. Quite the contrary, the posts were removed from the forum.
