### ISSUE TITLE
Add StreetViewSource parameter to fetchStreetViewData

### ISSUE THREAD

**Issue by yusufonderd** [googlemaps/android-maps-utils#1260]
**Is your feature request related to a problem? Please describe.**
I'm currently using the `fetchStreetViewData` function in a class called `StreetViewUtils` to check if there is street detail information for a specific location within a library. However, the function lacks the ability to specify a `StreetViewSource` parameter, which is essential for my use case.

**Describe the solution you'd like**
I would like to request the addition of a `StreetViewSource` parameter to the `StreetViewUtils.fetchStreetViewData` function. This addition would greatly enhance the functionality of the function and better serve my requirements. Simply put, I need the ability to specify the source for the street view data, and this parameter addition would address that need. Thank you.

Check street view optional parameters: https://developers.google.com/maps/documentation/streetview/request-streetview#optional-parameters

**Comment by wangela** [comment]
Thanks for offering a pull request to address your need! We're taking a look.
