### ISSUE TITLE
Cluster Count : Unstable

### ISSUE THREAD

**Issue by ekta-openxcell** [googlemaps/android-maps-utils#132]
Hello,

I'm using the git-hub code : https://github.com/googlemaps/android-maps-utils

I try to load pin (more than 2 pins becomes a cluster) or cluster in visible region of map. Cluster count will be exact count of pins item like 152 rather than 100+ by replace this line code on method onBeforeClusterRendered.

descriptor = BitmapDescriptorFactory.fromBitmap(mIconGenerator.makeIcon(String.valueOf(cluster.getSize())));

In Visible Region, I have 3 cluster item , first item is 5441 and other two items are 2. While launch the app, getting correct cluster count.. but slide the map left to right or right to left 4-5 times, getting incorrect cluster count..

In Class DefaultClusterRenderer print cluster count in  method -> onClustersChanged

@Override
    public void onClustersChanged(Set<? extends Cluster<T>> clusters) {
        for (Cluster<T> c : clusters) {
            Log.e(TAG,"onClustersChanged=>"+c.getSize());
        }
        mViewModifier.queue(clusters);
    }

getting response - 5489 ,2 , 2

cluster count changed from 5441 to 5489... how can i got the correct cluster count while playing with map?

**Comment by DeviLJohn** [comment]
until now it's not fixed (or a workaround)?! 
I have the same problem like some other [http://stackoverflow.com/questions/37467237/mapclustering-not-rendering-string-valueofcluster-getsize](url)

**Comment by tontongg** [comment]
Old issue but I have a possible explanation perhaps count of cluster's markers change because when you move the map, markers going out of screen and they are removed from the cluster ?!

**Comment by RupaliBidvi02** [comment]
Have you find solution ,i am facing same issue.
