### ISSUE TITLE
Gradle error when building project

### ISSUE THREAD

**Issue by slawrence93** [googlemaps/android-maps-utils#134]
Hi,

When I go to build the project I am told that: 

Neither path nor baseDir may be null or empty string. path='' basedir='/Users/Sean/dev/android-maps-utils-master/library'

I've tried multiple edits of my build.gradle file with no luck.  Below is a link to the stack trace of the build command.

http://pastebin.com/8NTiPvtp

**Comment by xni06** [comment]
I'd like to know the answer too please.
