### ISSUE TITLE
gradle build error with Play Services 6.5.87

### ISSUE THREAD

**Issue by skunkwerk** [googlemaps/android-maps-utils#138]
In my build.gradle I have:

dependencies {
    compile 'com.google.maps.android:android-maps-utils:0.3'
    compile 'com.google.android.gms:play-services-base:6.5.87'
    compile 'com.google.android.gms:play-services-location:6.5.87'
    compile 'com.google.android.gms:play-services-maps:6.5.87'
}

and I get the error:
Error:Execution failed for task ':app:processDebugResources'.
Error: more than one library with package name 'com.google.android.gms'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

thanks

**Comment by gdky005** [comment]
please see here: http://blog.csdn.net/gdky005/article/details/45889897 !

**Comment by n00dl3** [comment]
@gdky005 could you please translate it, I don't speak chinese and google's translation makes me want to smoke crack...
