### ISSUE TITLE
animate camera to marker in cluster item click

### ISSUE THREAD

**Issue by naivekook** [googlemaps/android-maps-utils#139]
how to animate camera to marker when i use cluster with InfoWindowApater? 
coz onClusterItemClick nor return type Marker and i cant call marker.showInfoWindow();

without clustering i do that:
mGoogleMap.setOnMarkerClickListener(new OnMarkerClickListener() {
			@Override
			public boolean onMarkerClick(Marker marker) {
				marker.showInfoWindow();
				Projection projection = map.getProjection();
				Point p = projection.toScreenLocation(marker.getPosition());
				map.animateCamera(
						CameraUpdateFactory.newLatLng(projection.fromScreenLocation(new Point(p.x, p.y - Utilities.getHeight() / 2 + 120))), 300, null);
				return true;
			}
		});

now i do that:
mGoogleMap.setOnMarkerClickListener(mClusterManager);

 mClusterManager.setOnClusterItemClickListener(new ClusterManager.OnClusterItemClickListener<FishMarker>() {
                        @Override
                        public boolean onClusterItemClick(FishMarker fishMarker) {
                            mChosenMarker = fishMarker;
                            return false;
                        }
                    });

mClusterManager.getMarkerCollection().setOnInfoWindowAdapter(new MapInfoWindowAdapter(getActivity()));
                    mGoogleMap.setInfoWindowAdapter(mClusterManager.getMarkerManager());

**Comment by stephenmcd** [comment]
Sample here: 1fdb2fad3626c1667051d640863d0ee0b39dbac2
