### ISSUE TITLE
How to change marker icon?

### ISSUE THREAD

**Issue by Slake07** [googlemaps/android-maps-utils#154]
i want to change default red marker which is showing in all markers. i want to set different markers for all items. how can i do that.?

**Comment by jmvines** [comment]
@Override
        protected void onBeforeClusterItemRendered(MyItem item, MarkerOptions markerOptions) {
            super.onBeforeClusterItemRendered(item, markerOptions);

            markerOptions.title(item.getTitle());

            BitmapDescriptor icon = BitmapDescriptorFactory.fromResource(R.drawable.pin);

            markerOptions.icon(icon);

        }

I this method you can change your marker.
