### ISSUE TITLE
Overlapping markers, which also problem in clustering counts.

### ISSUE THREAD

**Issue by Slake07** [googlemaps/android-maps-utils#157]
i have several book stores and restaurants in map using cluster library. in that, i have one restaurant and one book store which are at same location. due to same location, it causes in counting of clustering and also displaying markers on map. how can i solve this.?

**Comment by bkenn011** [comment]
I'm also having this problem, a cluster displaying a count of '4' when zoomed will pop one marker out, and then the cluster displays '6'.  No clue what's up with this.

**Comment by Slake07** [comment]
@bkenn011 this is not problem anymore. when you tap on marker two time you can see other markers also.
