### ISSUE TITLE
How to solve 2 libraries with same package name in my dependencies??

### ISSUE THREAD

**Issue by setu1421** [googlemaps/android-maps-utils#161]
I have below  dependencies

       compile 'com.google.android.gms:play-services:6.5.87'
        compile('com.google.maps.android:android-maps-utils:0.3.4')

Now i am getting below error:

   Error:Execution failed for task ':app:processDebugResources'.
> Error: more than one library with package name 'com.google.maps.android'
You can temporarily disable this error with android.enforceUniquePackageName=false
However, this is temporary and will be enforced in 1.0

How to solve it??

**Comment by megamattron** [comment]
(More info on targetting google play depdencies is here: https://developers.google.com/android/guides/setup)
