### ISSUE TITLE
Markers count inside cluster doesn't sum properly

### ISSUE THREAD

**Issue by MauriFont** [googlemaps/android-maps-utils#165]
There is an other issue posted about a problem with markers count, but i think this one is a bit different.

Also changing the DefaultClusterRenderer like this:

descriptor = BitmapDescriptorFactory.fromBitmap(mIconGenerator.makeIcon(cluster.getSize()));

It works fine, but when zooming out, when clustering for the last time, it doesn't sum correctly. In my case it has to sum a red bucket with a green one, lets say 300 + 100, but when clustered it stays at 300.

PD: I have noticed the same with  the rounded numbers ('300+' + '100+' == '300+')

**Comment by amatkivskiy** [comment]
I've met this issue when I changed **DefaultClusterRenderer.MIN_CLUSTER_SIZE** to 1. After that single markers are marked as clusters sometimes and items count inside cluster becomes  wrong.
