### ISSUE TITLE
sonatypeUsername

### ISSUE THREAD

**Issue by patriotaSJ** [googlemaps/android-maps-utils#166]
Hi, my issues is when i'm trying to add the android-maps-utils library i have a the following messeges 
"build.gradle
Error(64,0) No such property: sonatypeUsername for class: org.gradle.api.internal.project.DefaultProject_Decorated"

I do not what to do.
I follow this tutorial https://www.youtube.com/watch?v=TForBjArUNg to add de library

**Comment by patriotaSJ** [comment]
I find the solution i miss to copy the "gradle.properties"


version=0.4-SNAPSHOT

# variables required to allow build.gradle to parse,
# override in ~/.gradle/gradle.properties
signing.keyId=
signing.password=
signing.secretKeyRingFile=

sonatypeUsername=
sonatypePassword=

**Comment by Ambluden** [comment]
Thank you for solution, I was looking for this everywhere

**Comment by hopewise** [comment]
@patriotaSJ thanks for the solution, it worked :+1:  but can you please highlight, what are those parameters ? and why this has solved the issue?!

**Comment by markmcd** [comment]
The gradle.properties file should be included when you check out the repository. Could you explain how you got into a state where it didn't exist?

**Comment by markmcd** [comment]
And, to clarify, those parameters are used to build and upload the package to Maven (through sonatype). They're only used when running the uploadArchives task but gradle needs them to be defined.

The version code is present to define the version of the package and is used in all builds.

**Comment by hopewise** [comment]
Thanks for clarification, I got into the state where the above parameters where not in gradle.properties, is when in my project at Android Studio, I clicked project structure and added the library folder as a module from the downloaded zip file from https://github.com/googlemaps/android-maps-utils

I didn't start from the same project which is downloaded within the zip file

**Comment by guensuanhoa** [comment]
@patriotaSJ thank bro, you save my life.
