### ISSUE TITLE
Is this library still alive?

### ISSUE THREAD

**Issue by Ricardo1980** [googlemaps/android-maps-utils#170]
Hello!
Last commit is 6 months old.
Is this library still alive?
Thanks.

**Comment by jwoolston** [comment]
Commits have been made all through the month of June and July. Also, they just bumped the version number and are preparing a GitHub pages branch, plus the Google Maps Android API docs reference this library, so I would say there is a lot of evidence that it is still alive.

**Comment by Rainer-Lang** [comment]
Look here: https://github.com/googlemaps/android-maps-utils/graphs/contributors
