### ISSUE TITLE
How to highlight the selected cluster item?

### ISSUE THREAD

**Issue by johnjohndoe** [googlemaps/android-maps-utils#174]
I would like to provide **visual feedback** when the user selects a cluster item (not a cluster group). Although I get notified about the click event in `onClusterItemClick(CustomClusterItem clusterItem)` I wasn't able to find out how I can access the associated `MarkerOptions` in order to **change the icon or title** of the cluster item. I am using a custom render which extends `DefaultClusterRenderer` if this is of interest. Another way would be to use `setIcon` on the `Marker` itself if I would have access to it as one has in [`onMarkerClick(Marker marker)`](https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnMarkerClickListener).

**Comment by johnjohndoe** [comment]
I just relalized that `DefaultClusterRenderer#getMarker()` allows resolving the `Marker` associated with a `ClusterItem`. This allows me to update the icon.

---

For reference: [How to change the clicked marker icon using android-maps-utils?](http://stackoverflow.com/questions/30843425/how-to-change-the-clicked-marker-icon-using-android-maps-utils)

**Comment by SheikhZayed** [comment]
@johnjohndoe i get NPE when trying to access the marker object using this ?

**Comment by CoolMind** [comment]
@johnjohndoe, how did you solve the problem?
