### ISSUE TITLE
Cluster by category

### ISSUE THREAD

**Issue by ayzealot** [googlemaps/android-maps-utils#178]
I am trying to cluster 2 different type of data sets, each with their own cluster. I currently use 2 different clusterManagers to acheive this. But the problem comes when I try to implement the onClusterClick for both. I can only get one to work. 

Is there anyway to allow 2 clusterManagers to be added the the markerclick listener?

Or is there another way of doing clustering for different categories?

Thank you.

**Comment by broady** [comment]
yes, delegate the click listener through to both cluster managers.

```
map.setOnClickListener(new GoogleMap.OnMarkerClickListener() {
  boolean onMarkerClick(Marker m) {
    clusterManager1.onMarkerClick(m)
    clusterManager2.onMarkerClick(m)
  }
});
```
