### ISSUE TITLE
License file missing the copyright owner

### ISSUE THREAD

**Issue by eligrey** [googlemaps/android-maps-utils#180]
The license file says "[Copyright \[yyyy\] \[name of copyright owner\]](https://github.com/googlemaps/android-maps-utils/blob/master/LICENSE#L190)"

**Comment by broady** [comment]
Each file has its own copyright header.

**Comment by eligrey** [comment]
Yeah, nvm.

**Comment by broady** [comment]
However, some were missing. Thanks for bringing that to attention :)

b72f44e9770014
