### ISSUE TITLE
Cluster by category: Choosing which cluster is clicked

### ISSUE THREAD

**Issue by ayzealot** [googlemaps/android-maps-utils#182]
Hi,

Related to my previous question, Issue #178.

I have 2 categories of clusters. Another problem arose where the 2 clusters overlap and I cannot select which one to click. Is there a method that allows me to select which cluster to select?

Thank you in advance.

**Comment by vardaan** [comment]
I didnt understand your problem completely but this may help

    @Override
    public boolean onClusterItemClick(YourObject object) {
        if(object.getType == type1)
           //action related to type1

    else
           //action related to type2

        return false;
    }
