### ISSUE TITLE
Position of Cluster number TextView

### ISSUE THREAD

**Issue by ayzealot** [googlemaps/android-maps-utils#183]
Hi,

I have customized my own cluster_layout.xml with a TextView that is aligned to the right, but after it clusters, the TextView appears on the left. I'm not sure what I am doing wrong but I can't get it to work. 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="70dp"
    android:layout_height="70dp">

    <ImageView
        android:id="@+id/request_cluster_image"
        android:layout_alignParentRight="true"
        android:layout_alignParentBottom="true"
        android:layout_width="34dp"
        android:layout_height="34dp"/>

    <TextView
        android:id="@+id/request_text"
        android:layout_width="wrap_content"
        android:layout_height="16sp"
        android:minWidth="16sp"
        android:gravity="center_horizontal"
        android:layout_alignParentRight="true"
        android:textAppearance="@style/Bubble.TextAppearance.Light"
        android:background="@drawable/text_circle"
        android:paddingLeft="2dp"
        android:paddingRight="2dp"
        android:alpha="1"/>

</RelativeLayout>

And how I call it is similar to the demo.

Thank you in advance for any advice.

**Comment by ayzealot** [comment]
I was using relative layout. Changed to frame layout and it worked.

**Comment by Ricardo1980** [comment]
Do you use that to put a number in the marker or icon that represents a cluster on the map? Thanks.
