### ISSUE TITLE
showInfoWindow() programmatically

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#188]
this would be a nice feature

**Comment by LouisCAD** [comment]
I'm wondering how we can show the info window when the map has clusters too.
Without, it's as simple as calling `showInfoWindow()` on the marker, but with clusters, we don't have any marker reference, nor an object with a similar method.

**Comment by suvercha** [comment]
Added this in a3638edb8f5e42325069d41b03165f4bcf62a6ad

**Comment by LouisCAD** [comment]
Could you notify us here when this gets integrated into a new release please?

**Comment by stephenmcd** [comment]
@LouisCAD there's an RSS feed for releases, please subscribe to it: https://github.com/googlemaps/android-maps-utils/releases.atom
