### ISSUE TITLE
.removeLayerFromMap() doesn't work

### ISSUE THREAD

**Issue by GigaDroid** [googlemaps/android-maps-utils#190]
After calling KmlLayer.removeLayerFromMap() you can still see the layer

**Comment by William-ST** [comment]
I have the same problem

**Comment by digounet** [comment]
I have the same problem, how can I remove a layer? Do I have to clear all map?

**Comment by juvs** [comment]
Same situation here...

**Comment by juvs** [comment]
A workaround: call clear() from map, but careful, you well need to add the rest of layers and markers again. For me was the only solution for now.

**Comment by stephenmcd** [comment]
Duplicate #270
