### ISSUE TITLE
Integrate latest industry practices

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlemaps/android-maps-utils#193]
Hi,
Great library.  But you know what would make it better?  Integrating Dagger2 for dependency injection, RxJava for awesome asynchronous behavior, some MVP code organization.  Are there any plans to use these in the works?

Thank you,
Igor

**Comment by IlyaEremin** [comment]
RxJava consists of 3k methods. Not every developer uses RxJava in his projects. Less dependencies = good for library users.

**Comment by barbeau** [comment]
+1 for avoiding unnecessary dependencies.  When you start including the support and design libraries and Google Play services, it's really easy to hit the [65k method ceiling](https://developer.android.com/tools/building/multidex.html) quickly.  Yes, there are ways around this, but all of them complicate and/or slow down the build process.
