### ISSUE TITLE
How to load marker images from URL in custommarkerclusterddemo

### ISSUE THREAD

**Issue by SanyasiraoM** [googlemaps/android-maps-utils#195]

**Comment by TomasValenta** [comment]
No ideas?

**Comment by pbertsch** [comment]
You should wrap the below into a AsyncTask and draw/add the marker **after** you obtain the bitmap
```
URL url = new URL("http://load.image/from/url");
Bitmap bmp = BitmapFactory.decodeStream(url.openConnection().getInputStream());

map.addMarker(new MarkerOptions()
    .icon(BitmapDescriptorFactory.fromBitmap(bmp)));


```
I would recommend using a LRU Cache with a WeakReference if you have a lot of different Icons/Bitmaps

**Comment by ManishSharmaApporio** [comment]
> You should wrap the below into a AsyncTask and draw/add the marker **after** you obtain the bitmap
> 
> ```
> URL url = new URL("http://load.image/from/url");
> Bitmap bmp = BitmapFactory.decodeStream(url.openConnection().getInputStream());
> 
> map.addMarker(new MarkerOptions()
>     .icon(BitmapDescriptorFactory.fromBitmap(bmp)));
> ```
> I would recommend using a LRU Cache with a WeakReference if you have a lot of different Icons/Bitmaps

its works for me @pbertsch  Thanks.

**Comment by RajneeshShukla** [comment]
Here is the solution for this. It's working for me...
https://stackoverflow.com/questions/28280221/android-add-marker-to-maps-v2-with-seticon-from-url

https://stackoverflow.com/questions/8992964/android-load-from-url-to-bitmap

**Comment by haithemhasni** [comment]
Could you please explain how you got this working? I have the same issue and can't go over it for some reason. Thank you

**Comment by joelinjatovo** [comment]
Vary
Vola any

**Comment by Alexei-Suzdalenko** [comment]
fanks a lot

**Comment by sunnymopada** [comment]
Hi @Alexei-Suzdalenko @haithemhasni ,

The syntax might not be that relevant as it's been a long time and android API might have changed.

But it worked with the approach suggested @RajneeshShukla 

Step1:  Create a Bitmap using Url following answer for this question https://stackoverflow.com/questions/8992964/android-load-from-url-to-bitmap

Step2: Setting bitmap icon to marker as mentioned in the question of the https://stackoverflow.com/questions/28280221/android-add-marker-to-maps-v2-with-seticon-from-url
`
markerOptions.setIcon(BitmapDescriptorFactory.fromBitmap(bmp));
`
