### ISSUE TITLE
Cluster InfoWindow disappears

### ISSUE THREAD

**Issue by asda28** [googlemaps/android-maps-utils#198]
Hi,

I've recently upgrade from one of the very first version of the library to the latest one. The issue is that now whenever I click on cluster, the infoWindow pop-up and them almost immediately disappears - so I can't click on it. When I click on the individual item, everything works fine. When over my code several times, but can't find anything that might lead to this behavior. Did anyone had similar issue?

Thanks,

**Comment by willgurht** [comment]
I got this behaviour due to that I was recreating markers in onCameraChanged listener (which is triggered when centering on the selected cluster).

**Comment by KingAlex1985** [comment]
Hallo,

how can I unsubscribe this mails.
I couldnt find any informations.

Thank you in advance.

Greetings
Alex

Am 12.10.2015 um 10:52 schrieb willgurht:
