### ISSUE TITLE
Items not clustered after map zooms out

### ISSUE THREAD

**Issue by VirtuallyInvincible** [googlemaps/android-maps-utils#211]
Hello.

Usually, the clustering works fine, but I noticed that if I have a cluster of 2 elements located in exactly the same place and another item located nearby, then if the map zooms out abruptly following, for instance, a tap on the cluster, then I get a cluster of 2 + an item separated from the cluster and slightly hidden by it. I would expect the lone item to merge with the cluster and create a cluster of 3 in this scenario, but this doesn't happen. I was able to recreate this issue again and again. After the zooming out, as soon as I start to scroll the map in any direction, the item is merged with the cluster. This also happens if I turn off the screen and then turn it back on.

As far as I understand, my responsibility is to give the library the geo-locations of the items and the library itself is responsible for the merging and breaking of clusters. Thus if I have an issue where I expect to have a cluster of 7 but I have a cluster of 9 because I accidentally added 2 more items, that's my bug. But I have no control on how the clusters are created and broken into items, so I think  this is an issue with the library. Are you aware of this issue? Can you assist me in solving it?

I uploaded 2 screenshots for your convenience. One shows the item and cluster of 2 items right after the maps zooms out. The second is a screenshot of the same map with the same zoom level but just after I scroll the map just a little bit and the item is merged with the cluster of 2.

Thank you.

![screenshot_2015-10-07-13-32-06 1](https://cloud.githubusercontent.com/assets/14920433/10335329/8ecfe1b4-6cf8-11e5-8c2a-a46ea0cfb29e.png)

![screenshot_2015-10-07-13-32-00 1](https://cloud.githubusercontent.com/assets/14920433/10335293/571d1250-6cf8-11e5-9ab3-946ffa9a0b4d.png)

**Comment by Hirbod** [comment]
I can confirm this! It does not happen always, it's kinda random,
