### ISSUE TITLE
These utils seem kind of useless without any documentation or code comments.

### ISSUE THREAD

**Issue by hswope** [googlemaps/android-maps-utils#212]
These utils seem kind of useless without any documentation or code comments.

**Comment by broady** [comment]
I agree. That's why there is documentation:
http://googlemaps.github.io/android-maps-utils/
http://googlemaps.github.io/android-maps-utils/javadoc/

**Comment by broady** [comment]
And a demo app:
https://github.com/googlemaps/android-maps-utils/tree/master/demo/src/com/google/maps/android/utils/demo

**Comment by hswope** [comment]
Please don't get me wrong. I am certainly not dumping on this code. I am learning from it. Although my comment was less than constructive. But I had seen these documents prior to my comment and they don't provide much more information than reading the code. For example. I wanted to use the SphericalMercatorProjection and had to provide a construction parameter of worldwidth. Is this in meters, degrees, particles of stardust? After many hours of playing around and not having my code work (for other reasons) I found a sample that confirmed my suspicion that it was (1 << zoom) * tileSize. Even a code comment in support of this would have saved me many hours of wondering if I was using the class wrong.

**Comment by barbeau** [comment]
@hswope I'd suggest putting your documentation improvement in a pull request - that way others don't go through the same process.

**Comment by broady** [comment]
yes, `worldWidth` probably should have a comment. It's in whatever units of measurement you want. I usually just use `1`, actually.
