### ISSUE TITLE
z-order with cluster and normal markers

### ISSUE THREAD

**Issue by hannesa2** [googlemaps/android-maps-utils#214]
I have two clustermangers and separate markers without clustering as well:
blue: clustered items implements ClusterItem
black: normal markers
I know with normal markers I can send one in foreground with 

```
 marker.showInfoWindow();
```

but how can I handle this with clusters and clusteritems ?

![screenshot_20151015-163020](https://cloud.githubusercontent.com/assets/3314607/10516950/e6eecd48-735a-11e5-8d1a-073c830b975f.png)
Is there a way to put the black one to foreground ?

Thank you !

**Comment by Hirbod** [comment]
even it's offtopic @hannesa2 - but how did you manage to have two different groups? I also need markers which never get clustered. Any advice? Hast du eine Idee?

**Comment by hannesa2** [comment]
.. more than an idea, you need two ClusterManagers (and Renderer)

    private ClusterManager<ClusterItemA> clusterManagerA;
    private ClusterManager<ClusterItemB> clusterManagerB;

the never-clustered items are added normal

    map.addMarker(new MarkerOptions()....

but all three don't take care about each other and will overlap as you see in my picture

**Comment by Hirbod** [comment]
This would be fine for me, now I also need a solution for iOS. Thank you!

**Comment by Hirbod** [comment]
@hannesa2 could you provide a more detailed example? I can't get this work...
You must know, I'm using this on cordova, I make a call with JS to the plugin, which has the clustering, and I provide an "excludeFromCluster" value. If true, and don't pass it to my addItem method, instead, I pass it to "addItemUnclustered", where I just make a addMarker. It won't show up.

**Comment by Hirbod** [comment]
@hannesa2 I finally figuered out myself, but it won't fire my click event on that non-clustered marker.

**Comment by hannesa2** [comment]
If I understand, you don't want to consume the onMarkerClick() from non-clustered marker ?
What's about to ignore it ?
But the topic of this not closed issue is **z-order with cluster and normal markers** please open an other issue with your question

**Comment by mpprog** [comment]
I've researched this issue a lot before using ClusterManager. The problem is with Google Maps v2, which draws markers (systematically) from the top to the bottom of the projected map. There is no z-order unfortunately, and the order in which markers are added has no impact.
