### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ChristianLJ** [googlemaps/android-maps-utils#216]
Is here a changelog somewhere? I want to upgrade from 0.3.1 to 0.4 and i would like to know what the differencies are.

**Comment by markmcd** [comment]
We don't have an official changelog but you can have a quick glance using either `git log 0.3.1...0.4` or the [compare versions page](https://github.com/googlemaps/android-maps-utils/compare/0.3.1...0.4).

**Comment by ChristianLJ** [comment]
I see. Thank you.

**Comment by athkalia** [comment]
It would be really handy if you added a changelog against each release in https://github.com/googlemaps/android-maps-utils/releases . Keep it in mind for future releases : >

**Comment by markmcd** [comment]
Good idea. I'll re-open. Heads up @stephenmcd.

**Comment by johnjohndoe** [comment]
🗒 Please add release notes for versions **prior to version 0.5** to [REALEASENOTES.md](https://github.com/googlemaps/android-maps-utils/blob/master/REALEASENOTES.md).

**Comment by johnjohndoe** [comment]
?
