### ISSUE TITLE
demo application is not working (Where can i get working apk)

### ISSUE THREAD

**Issue by roshu10** [googlemaps/android-maps-utils#221]
Hi,

I downloaded github project and tried to run demo on android studio.
However its not working.

Where can i find working apk ??
Is this on playstore ??

Can anyone please provide working apk links ?
[bit urgent]

**Comment by lexi-sr** [comment]
I had this same problem and figured it out so posting this in case it helps anyone else in the future. I found this guide on how to set up the demo: https://developers.google.com/maps/documentation/android-api/utility/setup  I could not have my project already open when I clicked File->new->Import Project. I had to close it so Android Studio was on the splash screen, then click "Import Project (Eclipse ADT, Gradle, etc.)" and then selected the cloned repo, and it all worked.
