### ISSUE TITLE
Is it possible to adjust km for clustering

### ISSUE THREAD

**Issue by roshan8** [googlemaps/android-maps-utils#222]
Hi all,

i've used custom marker clustering concept.

only problem is items withing 1 or 1.5 km's are clustered together
[It won't separate even if i zoom in to max level.

Is it possible to set this distance ?

**Comment by ashishsakarkar2020** [comment]
any answers to this question?

**Comment by ibrahimAlii** [comment]
You need to minimize the `MAX_DISTANCE_AT_ZOOM` inside `NonHierarchicalDistanceBasedAlgorithm` classs @roshu10  @ashishsakarkar2020

**Comment by hesu-persee** [comment]
> You need to minimize the `MAX_DISTANCE_AT_ZOOM` inside `NonHierarchicalDistanceBasedAlgorithm` class @roshu10 @ashishsakarkar2020

Could you please indicate how do you modify the value? I cannot modify it as NonHierarchicalDistanceBasedAlgorithm is read-only for me

**Comment by barbeau** [comment]
@roshan8 You can modify the maximum distance between clustered items using the method `setMaxDistanceBetweenClusteredItems()`. For example:

        mClusterManager = new ClusterManager<>(this, getMap());
        mClusterManager.getAlgorithm().setMaxDistanceBetweenClusteredItems(myDistance);
