### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: when using PolyUtil.decode

### ISSUE THREAD

**Issue by sant527** [googlemaps/android-maps-utils#223]
I am making an android app where it will collect the overview_polyline->points string from the google maps api. For testing sake i have directly copied it(overview_polyline->points) and used as shown in the below code. I am using Polyutil to decode it:

```
List<LatLng> list = PolyUtil.decode("yxkpA_sjgMoAXuA@{GHeAFo@Jg@P[FcDHiCFu@B}@DkATiAFi@Hw@FcAKmAA[zG@n@DjAFpAPhB`@vBRt@`@|@dAbCg@F{B?eA?BpAAjC?vAC^W|@Ir@GdBe@hCm@lDpCl@|D~@J@?`AHdEAxGAVGZe@jBOnBzDLnGWPDFNRjDAjAG~@S|CCn@v@BXF?`@LtBEHOESC[BKBIJWWA?@?VV?PDbACJB?d@Ix@MRhBANABXRNDx@BBD@VD@FAj@?NB|@HAZLtBAf@CR");
```

I got the string from the below google direction api result:

```
 "overview_polyline" : {
            "points" : "yxkpA_sjgMoAXuA@{GHeAFo@Jg@P[FcDHiCFu@B}@DkATiAFi@Hw@FcAKmAA[zG@n@DjAFpAPhB`@vBRt@`@|@dAbCg@F{B?eA?BpAAjC?vAC^W|@Ir@GdBe@hCm@lDpCl@|D~@J@?`AHdEAxGAVGZe@jBOnBzDLnGWPDFNRjDAjAG~@S|CCn@v@BXF?`@LtBEHOESC[BKBIJWWA?@?VV?PDbACJB?d@Ix@MRhBANABXRNDx@BBD@VD@FAj@?NB|@HAZLtBAf@CR"
         },
```

When i run the app it says ```java.lang.StringIndexOutOfBoundsException: length=268; index=268```

**Comment by normanhh3** [comment]
+1 for this, I am using encoded polyline: "w{}oFfw`pMn}_QzhnGv`iQbufQ" and getting the same thing with index=27; index=27

My error is referencing PolyUtil.java:313 which winds up being the second occurrence of the line
```java
b = encodedPath.charAt(index++) - 63 - 1;
```

```java
   public static List<LatLng> decode(String encodedPath) {
        int len = encodedPath.length();
        ArrayList path = new ArrayList();
        int index = 0;
        int lat = 0;
        int lng = 0;

        while(index < len) {
            int result = 1;
            int shift = 0;

            int b;
            do {
                b = encodedPath.charAt(index++) - 63 - 1;
                result += b << shift;
                shift += 5;
            } while(b >= 31);

            lat += (result & 1) != 0?~(result >> 1):result >> 1;
            result = 1;
            shift = 0;

            do {
                b = encodedPath.charAt(index++) - 63 - 1;
                result += b << shift;
                shift += 5;
            } while(b >= 31);

            lng += (result & 1) != 0?~(result >> 1):result >> 1;
            path.add(new LatLng((double)lat * 1.0E-5D, (double)lng * 1.0E-5D));
        }

        return path;
    }
```

**Comment by normanhh3** [comment]
As a follow-up, I was able to resolve my issue by simply removing an extraneous newline character that was getting inadvertently appended to the end of my content that I was passing into the decode function.  I compared the character count with what was being displayed to see that there was one more character that I hadn't accounted for.

**Comment by speedious** [comment]
I am not able to solve my problem. Still getting StringOutOfBouncException. Please help me.

**Comment by adriiiprieto** [comment]
The encoded "overview_polyline" that I get from that directions response is encoded, has double encoded backslashes. To work in the request for a static map, the \\ needs to be translated to \

**Comment by adriiiprieto** [comment]
Some encoded "overview_polyline" that we get from that directions response is encoded, has double encoded backslashes. To work in the request for a static map, the \\ needs to be translated to \
