### ISSUE TITLE
Compatibility with google play services 8.3.0

### ISSUE THREAD

**Issue by christianscanu** [googlemaps/android-maps-utils#226]
Hi, is it possible to have a release of map utils compiled with google play services 8.3.0?

dependencies {
    compile 'com.google.android.gms:play-services-maps:8.3.0'
}

thanks!

**Comment by BaN4NaJ0e** [comment]
If I use the play services v8.1.0 or v8.3.0 with the 0.4 version of the map utils in combination with pro guard, I am not able to build my app. Please fix this.

For more information see this bug report: https://code.google.com/p/android/issues/detail?id=187483&q=gmail&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars

**Comment by IamTechknow** [comment]
FWIW, I am using Play Services v8.4 with proguard enabled (to use minifyEnabled) with the library and have been able to compile and run [my app](https://github.com/IamTechknow/trailapp). I haven't tested with Play services v8.1.0 or v8.3.0

**Comment by Vandalko** [comment]
just if someone tries to use latest library version with older GMS - add this to your ProGuard config
```
# References methods from gms:play-services-maps:8.4.0
-dontwarn com.google.maps.android.geojson.GeoJsonLineStringStyle
```

This was tested to work at least on `play-services-maps:7.5.0`. And for obvious reasons you can't execute methods from new API (I believe its `setClickable` in GeoJsonLineStringStyle)
