### ISSUE TITLE
Check for unique ClusterItem when adding new one

### ISSUE THREAD

**Issue by ykobets** [googlemaps/android-maps-utils#230]
It would be convenient to check if the same `ClusterItem` item was added previously inside this library. It could be checked for equality or coordinates comparing in clustering algorithms.

https://github.com/googlemaps/android-maps-utils/blob/dba3b0d8a9657ebab8c67a4f50bd731437a229bc/library/src/com/google/maps/android/clustering/algo/GridBasedAlgorithm.java#L40

**Comment by pbertsch** [comment]
**mItem** is a SET so if the exact Object already exists in the _set_ it will not be added.
