### ISSUE TITLE
KML layer using incorrect color format

### ISSUE THREAD

**Issue by avinabmalla** [googlemaps/android-maps-utils#232]
Google earth saves color in abgr format in kml. However, colors are being parsed in argb format.

**Comment by blackdigger** [comment]
also, probably related issue - when google maps export KML for some styles it sets color like "<color> 3BBFF</color>" - notice white space, where 0 could be - this leads to color parsing error. if I manually replace "<color> " with "<color>0" it works. or the same workaround can be put in kml parser.
