### ISSUE TITLE
A problem occurred evaluating root project 'android-maps-utils'. > Could not find method android() for arguments ...

### ISSUE THREAD

**Issue by AaronNGray** [googlemaps/android-maps-utils#233]
Hi,

Have tried to build but am getting the following error message :-

~~~
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Aaron\GitHub\android-maps-utils\build.gradle' line: 1

* What went wrong:
A problem occurred evaluating root project 'android-maps-utils'.
> Could not find method android() for arguments [build_1o0aldwai93z6yqcovlikc1yi
$_run_closure1@73d3e555] on root project 'android-maps-utils'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED
~~~

I updated the build.gradle :-

```
android {
    compileSdkVersion 20
    buildToolsVersion "23.0.2"
}
```

and demo/build.gradle :-

```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion
    ...
```

I am relatively new to Android development, I have got several apps built and running okay by making mods. I am not sure if its a versioning problem or a problem with my environment or whether its an actual bug either with the build system or with the app.

**Comment by stephenmcd** [comment]
These have since been updated.

**Comment by jensenmobile** [comment]
Error: /Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* Where:
Build file '/Volumes/Working/Development/Cordova/plugin/opcv/platforms/android/build.gradle' line: 253

* What went wrong:
A problem occurred evaluating root project 'android'.
> Project with path ':androidOpenCVExample' could not be found in root project 'android'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
