### ISSUE TITLE
New ClusterItems not drawn, unless the map is zoomed

### ISSUE THREAD

**Issue by dadino** [googlemaps/android-maps-utils#235]
This is what happens:
1. Map is loaded.
2. First batch of ClusterItems is added.
3. mClusterManager.cluster()
4. First batch of ClusterItems is drawn on map.
5. Second batch of ClusterItems is added.
6. mClusterManager.cluster()
7. **Second batch of ClusterItems is NOT drawn on map.**
8. Map is zoomed (in or out).
9. Second batch of ClusterItems is drawn on map.

Is there a workaround to this?

**Comment by Pkmmte** [comment]
I'm having the same issue. This occurs even when clearing the map before adding more items.

**Comment by borgwald** [comment]
same issue here.

**Comment by skywall** [comment]
I experience the same problem. The only solution I have to solve this is reset your marker renderer every time you (re)add items. In my scenario:

    clusterManager.clearItems();
	clusterManager.addItems(cars);
	clusterManager.cluster();
	clusterManager.setRenderer(new DefaultClusterRenderer<Car>(this, map, clusterManager) {
	
		@Override
		protected void onBeforeClusterRendered(Cluster<Car> cluster, MarkerOptions markerOptions) {
			ClusterHelper.initCluster(cluster, markerOptions);
		}
	
		@Override
		protected void onBeforeClusterItemRendered(Car car, MarkerOptions markerOptions) {
			ClusterHelper.initClusterItem(car, markerOptions);
		}
	});

**Comment by markuspaschke** [comment]
Try this method:
mClusterManager.cluster();
worked for me 👍

**Comment by marconealberto** [comment]
this is still not working on my side.. I tried everything that I found on google and it's still not working
