### ISSUE TITLE
how to show all markers name at once when google map opens?

### ISSUE THREAD

**Issue by vinay1a** [googlemaps/android-maps-utils#236]

**Comment by pbertsch** [comment]
You should give a bit more information.

I assume you mean showing the info window of the marker ?
If so, you could invoke **marker.showInfoWindow();** after each marker you are adding to the map.

**Comment by vinay1a** [comment]
yes,you are correct ,i used the same thing marker.showinfowindow(); .
 But it will show only the one marker info window at a time not all...

**Comment by pbertsch** [comment]
OK, the traditional InfoWindow does not work in this case because of the internal recycling of the window but there is a nice trick to overcome that.

[http://stackoverflow.com/questions/15331983/multiple-info-windows-in-android-maps-api-2](url)

**Comment by vinay1a** [comment]
please give me correct link,if i click on above link it is showing page not found error

**Comment by vinay1a** [comment]
i got thank you very much..

**Comment by pbertsch** [comment]
you are welcome.....Just a side note, if you have a lot of markers, with **different** InfoWindows, that approach could turn very fast very ugly because inflating views is resource consuming. As long as you use the same Layout for all the markers I think you should be fine.

**Comment by vinay1a** [comment]
oh ok..thats good suggestion

**Comment by bonachylauriel** [comment]
YOU MEAN each marker should have its layout(InfoWindows)?
