### ISSUE TITLE
Heatmap with more than 1000 points

### ISSUE THREAD

**Issue by gwilyr01** [googlemaps/android-maps-utils#237]
#71 falls into _two_ parts:

**First:** - https://github.com/googlemaps/android-maps-utils/issues/71#issue-30524946
**Second:** https://github.com/googlemaps/android-maps-utils/issues/71#issuecomment-39425462

While https://github.com/raymondlam/android-maps-utils/commit/57201be4b2733d45f1cf3143af3b9d8c8a6d3104 potentially addresses the first issue, the second is still outstanding.
#231 is an attempt at trying to resolve this.

This new issue has been created as requested by @markmcd, https://github.com/googlemaps/android-maps-utils/pull/231#issuecomment-174351014

**Comment by aadnk** [comment]
I don't know if it's related, but I managed to fix a similar issue (no heat map at high zoom levels) by filtering out points that are at infinity:
```java
private HeatmapTileProvider createTileProvider(List<LatLng> coordinates) {
	List<WeightedLatLng> weightedCoordinates = new ArrayList<WeightedLatLng>();

	for (LatLng coordinate : coordinates) {
		WeightedLatLng weightedCoordinate = new WeightedLatLng(coordinate);
		com.google.maps.android.geometry.Point point = weightedCoordinate.getPoint();

		// Filter points at infinity
		if (Double.isInfinite(point.x) || Double.isInfinite(point.y)) {
			Log.w(TAG, "Attempted to add undefined point " + coordinate);
			continue;
		}
		weightedCoordinates.add(weightedCoordinate);
	}
	
	return new HeatmapTileProvider.Builder()
			.weightedData(weightedCoordinates)
			.opacity(0.5)
			.build();
}
```
This seems to occur when you try to add a coordinate (LatLng) at latitude 90 or -90.
