### ISSUE TITLE
Get placemark Lat and Long from a kml layer

### ISSUE THREAD

**Issue by mbrasneves** [googlemaps/android-maps-utils#238]
Hi,
I´m trying to get the lat and lon from a kml layer to do zoom directly to a placemark after add it to a map. I tryed to do this:

camada = new KmlLayer(googleMap,R.raw.kmlfile,getApplicationContext());
camada.addLayerToMap();

for (KmlPlacemark marcador : camada.getPlacemarks()){
     marcador.getProperty("latitude");
}

but it doesn´t enter in the loop. Any help please?

**Comment by stephenmcd** [comment]
Have a look at the demo app which contains an example of both iterating placemarks and moving the camera to them: https://github.com/googlemaps/android-maps-utils/blob/fb05ef10408864106bbab3b5adcf775dbb9f8da1/demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java#L57-L72

**Comment by Vmarci94** [comment]
for example you would like "print" all placemark StyleId then do:

java```
        //First container in the kmlLayer
        ///KmlContainer container = kmlLayer.getContainers().iterator().next();
        //first nested container within the first container
        //container = container.getContainers().iterator().next();
        ///First placemark in the nested container
        ///KmlPlacemark placemark = container.getPlacemarks().iterator().next();

        //..so all placmark in the kmlLayer
        for(KmlContainer container : kmlLayer.getContainers()){
            for(KmlContainer nestedContainer : container.getContainers()){
                for(KmlPlacemark placemark : nestedContainer.getPlacemarks()){
                    Log.i("MTAG", placemark.getStyleId());
                }
            }
        }
```

it's work for me.

**Comment by yalcinmuhammed** [comment]
@Vmarci94 thank you sir. worked for me. I am grateful to you.
