### ISSUE TITLE
if OnClusterItemClickListener return true then dosen't show snippet

### ISSUE THREAD

**Issue by socar-tta** [googlemaps/android-maps-utils#243]
hi

if i OnClusterItemClickListener set return true then dosen't show snippet when i click marker
The reason why return true, i change zoom in OnClusterItemClickListener.
how to use both marker click snippet and OnClusterItemClickListener true

**Comment by markmcd** [comment]
I can't quite understand what you're asking - do you have a feature request, or is this a bug report? Could you provide a code sample that illustrates your request?
