### ISSUE TITLE
Library unusable : installing problem ?

### ISSUE THREAD

**Issue by djerem02** [googlemaps/android-maps-utils#248]
Hi !
I'm a beginner on Android , maybe it's easy to succes to my problem.
I would like to display every snippets of the markers simultanemously  on the map.
But the library doesn't work.... 
When I run app I get that :

 java.lang.NoClassDefFoundError: com.google.maps.android.ui.BubbleDrawable
         at com.google.maps.android.ui.IconGenerator.<init>(IconGenerator.java:60)                                   
         at com.easyspaceproject.MapsActivity.onLocationChanged(MapsActivity.java:320)

line 320 : IconGenerator icon = new IconGenerator(this);

Thanks

**Comment by calvinchankf** [comment]
same problem here
any solution?

**Comment by markmcd** [comment]
Looks like some files have been mysteriously stripped from the 0.4.2 release. I'll push out a 0.4.3 release with everything back in.

In the mean time, you can link the project in via source if you're super keen.

**Comment by markmcd** [comment]
And that's done now. Whenever maven updates with the latest package, your problems should be resolved.

Please comment back here if you find anything else broken - and thanks for the report.
