### ISSUE TITLE
Cluster when removed and added simultaneously, makes Markers invisible

### ISSUE THREAD

**Issue by Shub1427** [googlemaps/android-maps-utils#254]
I am trying to refresh my markers on network calls, and am removing markers before adding them. Also, i have called **ClusterManager.cluster()** after all my items are added.

This invisibility of markers happen only at alternate refreshes, i.e., first refresh markers are gone, second they are back with refreshed items

I am guessing, this is happening due to improper behaviour of markers getting added before getting removed (not sure of it).

I cannot get any total count of markers present on my map (there's no clusterManager.size() function, returning the total count of markers on map), else i wud have debugged the problem more properly

**Comment by cypressious** [comment]
@Shub1427 Have you found a solution?

**Comment by Shub1427** [comment]
I am not a part of that development team, working on the project using this library, anymore. Anyways what I do remember is, there was some kind of Code Logic error on my side, after solving that I removed this issue. I am closing this issue, if you still have the same problem you can open a new issue.
