### ISSUE TITLE
GeoJSON LineString dataset crash after update version of 0.4.2+

### ISSUE THREAD

**Issue by returnchung** [googlemaps/android-maps-utils#256]
My App use geojson utility to present "Tectonic Plate Boundaries" of USGS as geojson format on Google Maps API for Android. After the version upgrade, the data layer was not able to render and app would crash for some reason which crash logs contain message as follows:
"... java.lang.NoSuchMethodError: com.google.android.gms.maps.model.PolylineOptions.isClickable..."
When we fix the version as 0.4.0/0.4.1, the same data could be rendered as usual. Is that any function changed  but we did not notice?

**Comment by markmcd** [comment]
You'll need to update to Google Play Services 8.4.0 or higher.
