### ISSUE TITLE
Demo app won't build

### ISSUE THREAD

**Issue by dant3** [googlemaps/android-maps-utils#259]
`./gradlew :demo:aDebug` fails with:
```
A problem occurred configuring project ':demo'.
> failed to find Build Tools revision 23.0.0
```

but there is no such Build Tools version in Android SDK. You can only install 23.0.1/23.0.2 as closest ones

![image](https://cloud.githubusercontent.com/assets/820057/13707719/f7509990-e778-11e5-93e8-dfacf1972448.png)

**Comment by ssj36** [comment]
**Error:(25, 13)** Failed to resolve: com.google.maps.android:android-maps-utils:x.y.z
Getting above error after trying rebuild project

**Comment by dant3** [comment]
This is very good that this seems to be fixed since PR wich appropriate changes was merged, however, it would be very nice to actually close the issue afterwards, marking it as fixed.
