### ISSUE TITLE
Using the BalloonStyle Element as a Template

### ISSUE THREAD

**Issue by Vandalko** [googlemaps/android-maps-utils#265]
According to
- https://developers.google.com/kml/documentation/extendeddata#review-using-the-balloonstyle-element-as-a-template
- https://developers.google.com/maps/tutorials/kml/#extendeddata_elements

One can define at least this set of variables:
- **$[name]**
  - Replaced with the name of the Placemark
- **$[description]**
  - Replaced with the description of the Placemark
- **$[address]**
  - Replaced with the address of the Placemark
- **$[id]**
  - Replaced with the ID of the Placemark
- **$[Snippet]**
  - Replaced with the Snippet of the Placemark
- **$[geDirections]**
  - Replaced with the To/From driving directions of the Placemark

But it's not supported by current ([0.4.3](https://github.com/googlemaps/android-maps-utils/releases/tag/0.4.3)) version of [KmlRenderer](https://github.com/googlemaps/android-maps-utils/blob/0.4.3/library/src/com/google/maps/android/kml/KmlRenderer.java).

P.S. I've already started work on this since I need to replace **$[name]** variables inserted by Google Maps editor, but I'll appreciate any thoughts or helpful links regarding current issue.

**Comment by Vandalko** [comment]
Preliminary implementation:

```java
  private void setMarkerInfoWindow(KmlStyle style, Marker marker,
                                   final KmlPlacemark placemark) {
    boolean hasName = placemark.hasProperty("name");
    boolean hasDescription = placemark.hasProperty("description");
    boolean hasBalloonOptions = style.hasBalloonStyle();
    boolean hasBalloonText = style.getBalloonOptions().containsKey("text");
    if (hasBalloonOptions && hasBalloonText) {
      marker.setTitle(parseTextVariables(style.getBalloonOptions().get("text"), placemark));
    } else if (hasBalloonOptions && hasName) {
      marker.setTitle(placemark.getProperty("name"));
    } else if (hasName && hasDescription) {
      marker.setTitle(placemark.getProperty("name"));
      marker.setSnippet(placemark.getProperty("description"));
    } else if (hasDescription) {
      marker.setTitle(placemark.getProperty("description"));
    }
  }


  private String parseTextVariables(final String text, final KmlPlacemark placemark) {
    final Matcher m = Pattern.compile("\\$\\[(\\w+)\\]").matcher(text);
    final StringBuffer buffer = new StringBuffer(text.length());
    while (m.find()) {
      String variable = m.group(1);
      String replacement = placemark.getProperty(variable);
      if (replacement == null) {
        replacement = "";
        Log.w("LOG_TAG", "Unknown template variable $[" + variable + "]");
      }
      m.appendReplacement(buffer, replacement);
    }
    m.appendTail(buffer);
    return buffer.toString();
  }
```

**Comment by stephenmcd** [comment]
Looks good @Vandalko - could you create a pull request? Thanks!
