### ISSUE TITLE
GeoJSON rendering issue when zooming

### ISSUE THREAD

**Issue by AlexZvonik** [googlemaps/android-maps-utils#266]
When using GeoJSON with whole world dimmed but some 'hole' is not dimmed, when map is near max zoom, not dimmed area becomes dimmed.
When dimmed area is much less than whole world the issue doesn't exists.
`{
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [179.9,84.9],
                [90,84.9],
                [0,84.9],
                [-90,84.9],
                [-179.9,84.9],
                [-179.9,0],
                [-179.9,-84.9],
                [-90,-84.9],
                [0,-84.9],
                [90,-84.9],
                [179.9,-84.9],
                [179.9,0],
                [179.9,84.9]
            ],
            [
                [-73.93335,40.79225],
                [-73.93544,40.7907],
                [-73.9355,40.78937],
                [-73.93633,40.78808],
                [-73.93905,40.78526],
                [-73.94124,40.78399],
                [-73.94252,40.78327],
                [-73.94319,40.78195],
                [-73.94144,40.77607],
                [-73.94326,40.77366],
                [-73.94621,40.77092],
                [-73.954,40.76194],
                [-73.95706,40.75944],
                [-73.96969,40.74521],
                [-73.97162,40.74236],
                [-73.97239,40.73985],
                [-73.97239,40.73558],
                [-73.97446,40.73648],
                [-73.97333,40.73133],
                [-73.97143,40.72932],
                [-73.9713,40.72756],
                [-73.97393,40.71714],
                [-73.97687,40.71073],
                [-73.9812,40.70986],
                [-73.9885,40.70904],
                [-73.98889,40.70986],
                [-73.99715,40.70871],
                [-74.00102,40.70664],
                [-74.01098,40.70063],
                [-74.01392,40.7004],
                [-74.01616,40.70148],
                [-74.01961,40.7057],
                [-74.01835,40.71054],
                [-74.01678,40.71921],
                [-74.01337,40.71908],
                [-74.01183,40.72671],
                [-74.01036,40.73894],
                [-74.00849,40.74577],
                [-74.0069,40.74761],
                [-74.00813,40.74828],
                [-74.00889,40.75164],
                [-74.00147,40.76254],
                [-73.99986,40.76353],
                [-73.99519,40.76987],
                [-73.99487,40.77133],
                [-73.96752,40.81144],
                [-73.95977,40.80814],
                [-73.9613,40.80466],
                [-73.96014,40.80338],
                [-73.93335,40.79225]
            ]
        ]
    },
    "properties": {
    }
}
`
Visible area:
![device-2016-03-30-163051](https://cloud.githubusercontent.com/assets/8615785/14143720/6bca7a68-f695-11e5-9482-c3085d13b606.png)
Border of visible and not visible areas:
![device-2016-03-30-163125](https://cloud.githubusercontent.com/assets/8615785/14143728/7126c5ac-f695-11e5-942a-a83bf21973bf.png)
Visible area becomes invisible:
![device-2016-03-30-163134](https://cloud.githubusercontent.com/assets/8615785/14143730/72c4986c-f695-11e5-9859-e39b8fa3d14b.png)

**Comment by JohnDDuncanIII** [comment]
I'm using this same feature (adding a GeoJsonLayer with a ton of geometry), adding a GeoJsonPolygonStyle to each feature with either a Red or Green fill color, and getting the same problem.

**Comment by stephenmcd** [comment]
Could either of you provide a full GeoJSON example that reproduces the problem? Thanks.
