### ISSUE TITLE
Error:(25, 13) Build failed

### ISSUE THREAD

**Issue by ssj36** [googlemaps/android-maps-utils#269]
**Error:(25, 13)** Failed to resolve: com.google.maps.android:android-maps-utils:x.y.z

**build.grade of my app**

android {
    compileSdkVersion 22
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "nccl.iitbhu.swachhbharatservice"
        minSdkVersion 14
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.google.maps.android:android-maps-utils:x.y.z'
    compile files('libs/android-async-http-1.4.6.jar')
    compile files('libs/picasso-2.5.2.jar')

}

**Comment by fabiendem** [comment]
x.y.z is not a version number, use:
```
compile 'com.google.maps.android:android-maps-utils:0.4.3'
```

**Comment by ssj36** [comment]
sir, what does 0.4.3 refers to ? 
(please excuse if it is a silly question, i am a new bee in android development )
