### ISSUE TITLE
Wrong count

### ISSUE THREAD

**Issue by cesarferreira** [googlemaps/android-maps-utils#27]
Hi,
first of all thanks for the lib, it's awesome! 
I run into a little issue, when I add markers dynamically  the Sum of the markers goes nuts. For example, I have 5 markers, I have a button that adds a new marker, when I do it and zoom out the "5" now says "10" and when I zoom in it shows the 6 markers on the map, is this an issue or am I missing some objet.redraw() method call?

**Comment by nikitoSha** [comment]
Hi!
I have the same issue, but after  *.clearItems() >> *.addItem() >> *.cluster() I not see cluster markers, only a lot of simple markers. Please, help me =(

**Comment by nikitoSha** [comment]
ThisApp.getGlobals().mClusterManager.clearItems();
for (final ArrayList<String> thisPoint : ThisApp.getGlobals().listOfVisiblePoints) {
  final LatLng latLng = new LatLng(
  Double.parseDouble(thisPoint.get(8)),
  Double.parseDouble(thisPoint.get(9)));
  MyItem offsetItem = new MyItem(latLng.latitude, latLng.longitude);
  ThisApp.getGlobals().mClusterManager.addItem(offsetItem);
}
ThisApp.getGlobals().mClusterManager.cluster();

**Comment by nikitoSha** [comment]
I was try all the ways, but this bug exist. Now I use "clusterer" by nlopez and all works good!
