### ISSUE TITLE
Bucket doesn't uncluster

### ISSUE THREAD

**Issue by burnix** [googlemaps/android-maps-utils#272]
Hello. I extended `DefaultClusterRenderer<T>` class describing customize `markers`  when the  problem occurs. 

http://cs627121.vk.me/v627121202/51eb5/rY9f4p8ivos.jpg

Doesn't matter how much I try to zoom  in, my `Cluster Icon` doesn't "separate" onto five `markers`

Here's  some of code:

       public PlaceRender(Context context, GoogleMap map, ClusterManager<MyCluster> clusterManager) {
        super(context, map, clusterManager);
        mIconGenerator = new IconGenerator(context);
        imageView = new ImageView(context);
        mClusterImageView = new ImageView(context);
        mIconGenerator.setContentView(imageView);
        this.context = context;
        this.map = map;
        this.myClusterManager = clusterManager;

    }

    @Override
    protected void onBeforeClusterItemRendered(MyCluster cluster, MarkerOptions markerOptions) {
        super.onBeforeClusterItemRendered(cluster, markerOptions);
        markerOptions.title(cluster.name).snippet(cluster.snippet);
        markerOptions.infoWindowAnchor(0.5f, 0.0f);

    }

    @Override
    protected void onBeforeClusterRendered(Cluster<MyCluster> cluster, MarkerOptions markerOptions) {
        super.onBeforeClusterRendered(cluster, markerOptions);
    }

    @Override
    protected boolean shouldRenderAsCluster(Cluster cluster) {
        // Always render clusters.
        return cluster.getSize() > 1;
    }

    @Override
    protected void onClusterRendered(Cluster<MyCluster> cluster, Marker marker){
        super.onClusterRendered(cluster, marker);
    }

    @Override
    protected void onClusterItemRendered(MyCluster geo, Marker marker) {
        super.onClusterItemRendered(geo, marker);
        loadIconFromApi(geo, marker);
    }

    public void addItems(List<MyCluster> clusters, Context context, GoogleMap map) {
        myClusterManager = new ClusterManager<>(context, map);
        map.setOnMarkerClickListener(this);

        for (int i = 0; i < clusters.size(); i++) {
            myClusterManager.addItem(clusters.get(i));
            myClusterManager.setRenderer(new PlaceRender(context, map, myClusterManager));

        }
        myClusterManager.cluster();

    }

    //
    private void loadIconFromApi(MyCluster geo, Marker marker) {
        PicassoMarker markers = new PicassoMarker(marker, mIconGenerator, imageView);
        geo.setPicassoMarker(markers);
        Picasso.with(context).load(geo.image).into(markers);
    }

    @Override
    public boolean onMarkerClick(Marker marker) {
        marker.showInfoWindow();
        return true;
    }

Had anybody had the same problem? Could you help with it?

**Comment by burnix** [comment]
Ok. I've fixed it by  adding  function:

      public void updateUI(List<MyCluster> clusters) {
        myClusterManager.clearItems();

        for (int i = 0; i < clusters.size(); i++) {
            myClusterManager.addItem(clusters.get(i));
         //   myClusterManager.setRenderer(new PlaceRender(context, map, myClusterManager));

        }
        myClusterManager.onCameraChange(map.getCameraPosition());
    }

**Comment by jpfsilvaa** [comment]
Where did you call this function in the code?
