### ISSUE TITLE
Marker's anchoring position is not consistent when content rotation is -90 and rotation is 90

### ISSUE THREAD

**Issue by amadupu** [googlemaps/android-maps-utils#273]
Im trying to display the marker (content view with custom image view and text view in horizontal linear layout) to the right side of the map position by setting content rotation as -90 and rotation as 90.My expectation is bubble caret should still point to the same location on the map. however in actual the bubble caret is not pointing to the correct postion rather offset horizantally by some amount..

there is no additional paddding either in content view or specified explicitly for the icongenerator factory. 
any suggestions pls

**Comment by amadupu** [comment]
looks like i need to update the marker anchor inline to Icongenerator's (U,V) anchoring postions (using getAchorU and getAnchorV methods) post rotation.

**Comment by amadupu** [comment]
![rotation_issue](https://cloud.githubusercontent.com/assets/14251460/14672749/6c9f5732-0717-11e6-8705-feb17e6a712c.jpg)


can some one comment on why the extra padding happens when the content is rotated from the attached snapshot.
the attached snapshot captures the marker icon generated from icon generator factor for different rotation and content rotation.

**Comment by Sithira** [comment]
@amadupu have you fixed the extra padding issue ???

**Comment by amadupu** [comment]
@Sithira No, I could not able to fix it so far
