### ISSUE TITLE
White squares - issue with latest Play Services 9.0.83

### ISSUE THREAD

**Issue by yuraj11** [googlemaps/android-maps-utils#276]
Hello,
today has started appearing this issue (after few of zoom in/out most of group icons are replaced by white squares):
![gmaps_white_squares_issue](https://cloud.githubusercontent.com/assets/5477518/15248847/b05ce5cc-191c-11e6-8286-249d0695eaf3.png)

We had no problems before but latest Play services has broken something (9.0.83, updated 11. may). We have test our application with Play Services 8.7.03 and there is absolutely no problem. Our application uses Play services SDK 8.4.0.

**Comment by evgentset** [comment]
Confirm, I have the same issue. There are no any issues on devices with Play Services 9.0.82 and Play Services 8.7.03. I use Play services SDK 8.4.0 and android-maps-utils 0.4.3.

**Comment by ursimon** [comment]
Confirm, we have also the same issue. Using Play services SDK 8.4.0 and android-maps-utils 0.4.3 and Play Service 9.0.83.

![markers](https://cloud.githubusercontent.com/assets/1089761/15250218/fdc05d9c-1923-11e6-8c70-db5ac573314f.png)

**Comment by Mavamaarten** [comment]
I can confirm the same erroneous behavior. Play Services SDK 8.4.0, Play Services 9.0.83, android-maps-utils 0.4.3.

![](http://i.imgur.com/W32FirE.png)

**Comment by madsvyat** [comment]
![screenshot_20160513-231601](https://cloud.githubusercontent.com/assets/5320930/15260704/f87ae680-1960-11e6-9ef1-edec850192ec.png)

Confirm, I'm faced with a same issue. Our app uses android-maps-utils 0.4.3, Google Play Services 9.0.83, Google Play services SDK 8.4.0

**Comment by akirmse** [comment]
I'm seeing it too on two Nexus 5 devices:

Android 4.4.4, Google Play services 9.0.82
Android 6.0.1, Google Play services 9.0.83

A Samsung Galaxy S4 with Android 4.2.2 and Google Play services 8.7.03 is working correctly.

I've seen cases where some markers with a particular bitmap are correct, and others with the same bitmap are white squares.

I've heavily simplified the android-maps-utils library, and as an experiment I tried disabling cluster rendering and the marker cache, but the problem still happens.  Strange that this bug hasn't been reported in the main gmaps-api-issues database yet.

**Comment by yuraj11** [comment]
Ok someone has opened issue on gmaps-api-issues too: https://code.google.com/p/gmaps-api-issues/issues/detail?id=9765

**Comment by Mavamaarten** [comment]
Possible workarround from the gmaps-api-issues page:

> change
marker.setIcon(BitmapDescriptorFactory.fromResource(R.drawable.drawableid));
>
>to
>marker.setIcon(BitmapDescriptorFactory.fromBitmap(BitmapFactory.decodeResource(getResources(), R.drawable.drawableid))); //could affect general memory consumption tho(?), I haven't tested with more than the app reported with in the issue.

**Comment by meierjan** [comment]
I can confirm this issue.

**Comment by bperin** [comment]
@Mavamaarten in what method are you calling marker.setIcon ? somewhere in the ClusterRenderer?

**Comment by spotlmnop** [comment]
+1 - we are facing the same issue.

**Comment by asanovcs** [comment]
Confirm, we have also the same issue

![index_1](https://cloud.githubusercontent.com/assets/6161784/15354916/cdc97f3c-1d11-11e6-9e64-5399053ed8a8.jpg)

**Comment by josebrandao13** [comment]
Same problem here.
Google Play services 9.0.83

![13262642_1049201668467857_2078773042_o](https://cloud.githubusercontent.com/assets/13275681/15356610/a6bc27ac-1cf1-11e6-9b24-ba091572b87f.png)

**Comment by brockhaus** [comment]
Same issue here. The fix mentioned by @Mavamaarten works for me but only partially.
Single icons on cluster are displayed now correctly always but not (standard) clustered icons (the circles with numbers). Am I missing a part to fix?

**Comment by bperin** [comment]
@brockhaus it fixes the individual icons because your generating unique bitmaps for each icon, but the cluster ones are still shared, if you create custom cluster icons it might fix it

**Comment by dfsilva** [comment]
![screenshot_2016-05-20-08-16-55](https://cloud.githubusercontent.com/assets/424713/15426212/6fae1efa-1e63-11e6-99c9-d5905849289a.png)

Same issue in my app.

**Comment by omricarmi** [comment]
Same issue also in my app
![screenshot_2016-05-20-18-13-37](https://cloud.githubusercontent.com/assets/5064959/15432420/d6adf38e-1eb6-11e6-96a0-3c2cf6dcca4e.png)

**Comment by bdiegel** [comment]
Having the same issue. Implemented a workaround (same as mentioned by @Mavamaarten) but have similar concerns about memory consumption and performance.

**Comment by vbuberen** [comment]
Also have this issue, but only on some devices (like Xiaomi). White spaces appear instead of markers or cluster markers during zoom in/out. Don`t think it`s related to Play services SDK, because my app uses version 8.4.0 and android-maps-utils version 0.43.

**Comment by bishop87** [comment]
Having the same issue, I made a workaround avoid the SparseArray object, used in official DefaultClusterRender.java (private SparseArray<BitmapDescriptor> mIcons = new SparseArray<BitmapDescriptor>();).

So I make the cluster icon every time, setting background color and text dynamically in onBeforeClusterRendered method.

Here my full working code:
https://github.com/bishop87/share/blob/master/android/MyMapRender.java

Note about my code: for my scope I also introduce a boolean flag to handle a enabled/disabled cluster status, changing its color (green if disabled, orange if enabled). But you can simply remove all this stuff and obtain a original-like rendering.
At the moment, the only disadvantage I noticed is on performance: without shared object SparseArray, you are going to draw all cluster icon, even if these have already been drawn. But for a limited items number (1000 items in my case), the performance gap is negligible.

Hope this help someone.

**Comment by vjerryv** [comment]
I got the same issue

**Comment by xni06** [comment]
Same issue with https://play.google.com/store/apps/details?id=org.wildlifetrusts.naturefinder

**Comment by jerrychan6waves** [comment]
same here

**Comment by AAverin** [comment]
+1

**Comment by thuat26** [comment]
Same issue in my app.

**Comment by lashket** [comment]
Have same issue in ny app too:rage:

**Comment by billylindeman** [comment]
Had the same issue in my app and used @bishop87's workaround and it fixes the issue with negligible performance impact on my end.  Going to test on some lower end devices, but for now that seems to do the trick.

**Comment by AlexanderTolstykh** [comment]
I am using  @bishop87's workaround with removed enabled/disabled functionality. See more info here -  http://stackoverflow.com/a/37431561/2308720. Hope it will help to someone.

**Comment by ArthurSav** [comment]
Any update on this?

**Comment by tseglevskiy** [comment]
Do you know what exactly versions of Google Play Services on device cause this problem? And how to detect it?

**Comment by chitgoks** [comment]
9.0.1 still has this problem

**Comment by seanfchan** [comment]
BUMP
also have the same issue

**Comment by broady** [comment]
Please comment on the root cause issue:
https://code.google.com/p/gmaps-api-issues/issues/detail?id=9765
