### ISSUE TITLE
Cluster Manager is Not Updating/Refreshing on Map

### ISSUE THREAD

**Issue by RajappaR** [googlemaps/android-maps-utils#277]
I am trying to add some markers after changing camera position, that is working fine when i taken MapsActivity, But This is not working when i taken MapFragment under PagerView.

Can anyone Help here please... 

Thank you

**Comment by A86S** [comment]
@RajappaR have you got any solution over this

**Comment by RajappaR** [comment]
@A86S Yeah I got the Solution and resolved it

**Comment by stephenmcd** [comment]
@RajappaR can you post the solution here? Thanks

**Comment by RajappaR** [comment]
Before adding new markers, first Clear all the Markers in ClusterManager using "mClusterManager.clearItems()" and then add the new Markers....

**Comment by stephenmcd** [comment]
@RajappaR thanks :-)

**Comment by leonardovsilva** [comment]
mClusterManager.cluster();

**Comment by marconealberto** [comment]
calling clearItems and cluster don't make any difference on my side. Any other ideas?

**Comment by yousefjoe4** [comment]
@albert0m  where you able to solve it?

**Comment by andres2093** [comment]
> calling clearItems and cluster don't make any difference on my side. Any other ideas?

How did you solve it?

**Comment by aliustaoglu** [comment]
```java
googleMap.setOnCameraIdleListener(mClusterManager);
```

You need to set Camera Idle Listener to your cluster manager instance if you want the markers to refresh automatically on zoom changes. That's how I solved this.
