### ISSUE TITLE
Click on Layer

### ISSUE THREAD

**Issue by remydavid** [googlemaps/android-maps-utils#280]
I can't see a way to handle a click on a Layer (KML or GeoJSON), am I missing something ?

Thanks !

**Comment by JohnDDuncanIII** [comment]
same here. I am working on a piece of disaster relief software for DHS/FEMA, and it would be great if I could show the evacuation zone # when a user clicks on one of the map features.

**Comment by remydavid** [comment]
I ended up ditching android-maps-util and manually extracting the KML polygons and adding them using the GMaps addPolygon / setOnPolygonClickListener functions. It works but the click zone are not precise at all, seems like Polygons are over simplified for click detection.

**Comment by JohnDDuncanIII** [comment]
I just found out you could do that earlier today. That's what I will do. Thanks.

**Comment by stephenmcd** [comment]
Added in 19344ee34ec1d14e19adc41146ecf2af598f88ec
