### ISSUE TITLE
Maps don't render colors from all polygons inside kml file 

### ISSUE THREAD

**Issue by julciane** [googlemaps/android-maps-utils#282]
Hi all,
I have a kml file with many regions, there are two regions that color is only displayed after user zooms in into the map, otherwise it has the original map color.
Please refert to this image (https://drive.google.com/open?id=0B_O4Z1pQdVfnSXJIcFpUczdlRE0): the red rectangle shows the not colored region (with a green region inside it)
I would like to have all colors rendered when map is loaded (without rely on user interaction to display colors correctly)

Best regards,
J.

**Comment by stephenmcd** [comment]
Could you provide the KML file that produces the image? Thanks!

**Comment by julciane** [comment]
You can find the kml file here https://drive.google.com/file/d/0B_O4Z1pQdVfnSmRQaUdpbDdUUnc/view?usp=sharing

**Comment by stephenmcd** [comment]
Appears to be a known issue with Maps on Android as reported here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=5241

I've made a note of this report on our corresponding internal issue, but I'll close this for now since it's not an issue with AMU itself.
