### ISSUE TITLE
KmlLayer from InputStream not working.

### ISSUE THREAD

**Issue by Doraviv** [googlemaps/android-maps-utils#287]
When I use the function: 
KmlLayer layer = new KmlLayer(googleMap,inputStream , getApplicationContext());
(im using Kml file from url).
I get exception "NetworkOnMainThread".
when I try to use AsyncTask or background Thread, I get exception that I cant use handler inside thread.
If I use the above function on local file instead of inputStream - everything works fine.

thanks.

**Comment by stephenmcd** [comment]
Have a look at the sample here:

https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java

**Comment by Doraviv** [comment]
Thanks!! :)

**Comment by alintongutierrez2007** [comment]
i have match problem at load kml file, in local google maps android. URL  in later response (https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/com/google/maps/android/utils/demo/KmlDemoActivity.java)   is not work . can you help me please

**Comment by barbeau** [comment]
@alintongutierrez2007 The KML demo has moved to:
https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/KmlDemoActivity.java

**Comment by alintongutierrez2007** [comment]
your example is perfect. thank you. i am very happy.
excuseme for my bad english,  i am learning now.

**Comment by hmyongsong826** [comment]
Perfect! 
Thank you very much.
