### ISSUE TITLE
Kml exception

### ISSUE THREAD

**Issue by digounet** [googlemaps/android-maps-utils#292]
Unable to load kml file. Error:

> END_TAG expected (position:START_TAG (empty) <br>@26:37 in java.io.InputStreamReader@c8587d0) 

Kml attached
[CNTTronco.zip](https://github.com/googlemaps/android-maps-utils/files/350890/CNTTronco.zip)

**Comment by stephenmcd** [comment]
If you have HTML embedded inside description tags they need to be wrapped in CDATA strings, see some examples here: 

https://developers.google.com/kml/documentation/kmlreference#examples 
https://www.w3.org/TR/REC-xml/#sec-cdata-sect
