### ISSUE TITLE
Build with the new listeners

### ISSUE THREAD

**Issue by edumucelli** [googlemaps/android-maps-utils#296]
Thank you for the amazing project.

Using `compile 'com.google.maps.android:android-maps-utils:0.4.3'` does not provide yet the new camera listeners. How could I use them? I have tried [jitpack.io](jitpack.io) but it did not worked either.

Thank you in advance.

**Comment by Maverick25** [comment]
I had the same problem and I think I cracked it.. try this:

`map.setOnCameraIdleListener(new GoogleMap.OnCameraIdleListener()
        {
            @Override
            public void onCameraIdle()
            {
                clusterManager.onCameraChange(map.getCameraPosition());
            }
        });`

That's one of the examples that is working for me :)

**Comment by stephenmcd** [comment]
Just to be clear, the new listeners have been added to the code base, but we're yet to push a new release, which will happen soon.

**Comment by edumucelli** [comment]
Thanks @stephenmcd, looking forward to the release. Cheers!

**Comment by thakkaryash94** [comment]
Thanks @stephenmcd.

**Comment by stephenmcd** [comment]
Just released 0.4.4
