### ISSUE TITLE
Interpolate on a path

### ISSUE THREAD

**Issue by nevi-me** [googlemaps/android-maps-utils#298]
I'm trying to animate a marker on a path, but from reading the documentation it appears that I can only `interpolate()` between two points. Does anyone know how to interpolate on a Polyline with many points?

**Comment by pingothedoer** [comment]
Hi @nevi-me , did you find any solution for this?

**Comment by nevi-me** [comment]
Hi @pingothedoer, I sort of did, I ended up using linear interpolation over very short distances. It however didn't work well, so I stopped trying.
