### ISSUE TITLE
getMap().setOnCameraChangeListener(clusterManager) is deprecated in Google Play Service 9.4.0

### ISSUE THREAD

**Issue by GulajavaMinistudio** [googlemaps/android-maps-utils#303]
While trying to implement use ClusterManager, I noticed that the getMap().setOnCameraChangeListener(clusterManager) is deprecated. Looking at the android-maps-utils sample on Github, I noticed that getMap().setOnCameraIdleListener(mClusterManager);

When I try doing the same, I get an error because the default ClusterManager class doesn't implement GoogleMap.OnCameraIdleListener.

Yet, in my gridle file, I am using what seems to me, the latest maps-util libraries:

dependencies {
    compile 'com.google.maps.android:android-maps-utils:0.4.3'
    compile 'com.google.android.gms:play-services-location:9.4.0'
    compile 'com.google.android.gms:play-services-maps:9.4.0'
}

How can I get access to the newest ClusterManager class? Thanks

**Comment by stephenmcd** [comment]
#296

**Comment by vaymaks** [comment]
you need to update to new android-maps-utils:0.4.4 (compile 'com.google.maps.android:android-maps-utils:0.4.4')
