### ISSUE TITLE
Update library with new Camera Methods

### ISSUE THREAD

**Issue by thakkaryash94** [googlemaps/android-maps-utils#305]
Google maps library v9.4.0 deprecated setOnCameraChangeListener method, I saw the [commit](https://github.com/googlemaps/android-maps-utils/commit/2f7f2c03b14eab5e49d95cb233124a9dc7aef7e7) but it is not release on maven. Please release it so that we can use it with maps.

**Comment by stephenmcd** [comment]
#296
