### ISSUE TITLE
marker positions are not updated

### ISSUE THREAD

**Issue by altairmizuchi** [googlemaps/android-maps-utils#307]
**Summary:** 

I have data from moving devices (The one moving with ~50 km/h). I creat my ClusterItem with link to this object. After I update all objects coordinates and call ClusterManager.cluster(). However this object's marker (I want to repeat i do not create it with addMarker) does not move. Its marker is not merged with any cluster cloud. I am 100% sure that coordinates change. Where am i wrong? Help me, please.

**Steps to reproduce:** 

```
class MyClusterItem implements ClusterItem {
    WeakReference<MovableObject> mWrObject;
    public MyClusterItem (MovableObjectobj) {
        mWrObject = new WeakReference<>(obj);
    }
    @Override
    public LatLng getPosition() {
        Log.v("TAG", "GET_POSITION_CALLED");
        MovableObjectobjobj = mWrObject.get();
        if(obj == null)
            return null;
        else {
            if(obj.coord == null)
                return null;
            else
                return obj.coord.latlng;
        }
    }
```

this method is called from MyDefaultClusterRenderer.onBeforeClusterItemRendered

```
    public void fillMakerOptions(MarkerOptions markerOptions) {
        MovableObjectobjobj = mWrObject.get();
        if(obj != null) {
            markerOptions.snippet(obj.id)
                        .icon(obj.getBitmapDescriptor())
                        .title(obj.name);
        }
    }
}
```

**Expected behavior:** 

I expect that not merged marker position will be updated after cluster() call.

**Observed behavior:** 

Object stays still regardless coordinates updates. If i reopen activity i will have new position. cluster() does not change anything.

**Device and Android version:** 

Samsung galaxy s5, android 4.4

**Comment by tontongg** [comment]
Hi,
This is the most recent post which describe a similar problem with actually encounter. If we are right, there is actually no possibly update of markers. We are working to add this feature but it's not easy :)
For us, it's not for move marker but juste update marker when ClusterItem status changed.
I'll come back to you if our attempts finally work !

FYI : look at DefaultClusterRenderer.RenderTask.run (there is a condition to render cluster.equals(...mClusters) and you probably return directly from here because it's the same clusters.

Ciao !

**Comment by altairmizuchi** [comment]
I see. Probably overriding of equals() will solve problem somehow.
I had to go with straightforward solution back then with running through markers collection within a separate thread with updating their positions if they are visible.

**Comment by altairmizuchi** [comment]
Although it works bad for many not clustered objects.
