### ISSUE TITLE
Default marker TextView id has been changed.

### ISSUE THREAD

**Issue by nafizb** [googlemaps/android-maps-utils#309]
I spend an hour to understand why my markers just stopped getting text value's.

Then i realized:
Before version 0.4.4, mContentView field was returning TextView which id's is id.text :
`this.mContentView = this.mTextView = (TextView)this.mRotationLayout.findViewById(id.text);`

After version 0.4.4, it has been changed to id.amu_text :
`this.mContentView = this.mTextView = (TextView)this.mRotationLayout.findViewById(id.amu_text);`

Therefore when you trying to use makeIcon(yourText) from IconGenerator, its not assigning the value.

Beware if you are using
`compile 'com.google.maps.android:android-maps-utils:0.4+'`

**Comment by xsorifc28** [comment]
@nafizb How did you fix this? I'm having the same issue.

**Comment by nafizb** [comment]
@xsorifc28 You can change your TextView id to amu_text in marker layout.(Quick Fix)
However, i fix in another way:
Inflate your your marker layout:
` View markerView = LayoutInflater.from(getContext()).inflate(R.layout.marker, bottomSheet, false);`
Then get the Textview:
`TextView text = (TextView) markerView.findViewById(R.id.text);`
And just change the value :)
`text.setText("cibili");`

**Comment by xsorifc28** [comment]
@nafizb  Hmm, I don't have a custom marker layout (just using IconGenerator, debugging shows that TextView is not null in there), I'm not sure where the bug is.

**Comment by stephenmcd** [comment]
See #252
