### ISSUE TITLE
Sometimes a "ConcurrentModificationException" occurs when adding markers from multiple threads

### ISSUE THREAD

**Issue by JonasDaWi** [googlemaps/android-maps-utils#31]
When I add markers from multiple threads I sometimes get following exception:
E/AndroidRuntime(19091):        at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm.getClusters(NonHierarchicalDistanceBasedAlgorithm.java:90)
E/AndroidRuntime(19091):        at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.getClustersInternal(PreCachingAlgorithmDecorator.java:83)
E/AndroidRuntime(19091):        at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.access$0(PreCachingAlgorithmDecorator.java:73)
E/AndroidRuntime(19091):        at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator$PrecacheRunnable.run(PreCachingAlgorithmDecorator.java:106)

Seems like mItems should be thread safe or what is the best solution for this?

Greetings,
Jonas

**Comment by PauloLinhares09** [comment]
Isso pode ser resolvido criando uma nova thread para fazer o while na lista de markers. 
Em seguida é só voltar para a UI Thread  quando for executar algum ação de UI como mMarker.remove() ou mMarker.setPosition(), por exemplo.
