### ISSUE TITLE
Cannot resolve IconGenerator class with version 0.4.4

### ISSUE THREAD

**Issue by king89** [googlemaps/android-maps-utils#310]
i can build my app before 0.4.4, but i cannot build it after version 0.4.4.
it was because the IconGenertor class can not resolve by the Android Studio.
       `IconGenerator factory = new IconGenerator(MainActivity.this);`

i am not sure why, but when i changed the gradle :
from
`compile 'com.google.maps.android:android-maps-utils:0.4+'`
to
`compile 'com.google.maps.android:android-maps-utils:0.4.3'`

it works fine.

**Comment by nafizb** [comment]
You can use getContext() instead of MainActivity.this
