### ISSUE TITLE
KmlStyle class not declared public

### ISSUE THREAD

**Issue by jonasao** [googlemaps/android-maps-utils#311]
**Summary:** 

I am attempting to read style information using the method KmlContainer.getStyle(styleId), but AndroidStudio will not allow me to make a reference to the KmlStyle class, which is the object returned from this method. 

**Steps to reproduce:** 
1. Create a new KML-layer
2. Get a reference to the 1st KML-container: layer.getContainers().iterator().next();
3. Loop through the container's placemarks
4. While looping, get the style ID of the current placemark: styleId = placemark.getStyleId();
5. Attempt to get the placemark'style: KmlStyle style = kmlContainer.getStyle(styleId);

AndroidStudio fails to resolve a reference to the class KmlStyle in step 5.

**Expected behavior:** 
I expected the reference to the KmlStyle class to be working, by letting AndroidStudio import the necessary namespace or by typing in the full path to the class. Neither works since the KmlStyle class is not declared public.

The KmlStyle class needs to be declared public as this is the type returned by the public method KmlContainer.getStyle(styleId).

**Observed behavior:** 

I am unable to create a reference to the KmlStyle class, but while debugging I am able to see the output of kmlContainer.getStyle(styleId), which is parsed as a KmlStyle class.

**Comment by Libby713** [comment]
Fixed in 087615d
