### ISSUE TITLE
cluster text not visible on 0.4.4

### ISSUE THREAD

**Issue by mengoni** [googlemaps/android-maps-utils#315]
**Summary:** 

Upgrading to 0.4.4 the text on clusters is not visible (the number of items in cluster). 

**Steps to reproduce:** 

In previous version I used this code:
` mIconClusterGenerator.setTextAppearance(com.google.maps.android.R.style.ClusterIcon_TextAppearance);
`
but on 0.4.4 the resource is not available. I tried to use instead:
`mIconClusterGenerator.setTextAppearance(com.google.maps.android.R.style.amu_ClusterIcon_TextAppearance);`

**Expected behavior:** 

On map should be visible the number of items within the clusters.

**Observed behavior:** 

In the logs I can correctly see the number of items, but on map the cluster text is not visible.

**Device and Android version:** 

I tried on Nexus 5 and Nexus 6P with latest play services.

**Screenshots:** 

![screenshot_20160912-165800](https://cloud.githubusercontent.com/assets/10978407/18440637/3bd1b090-790a-11e6-9d43-db7cb2407802.png)

**Comment by dawidhyzy** [comment]
Same for me

**Comment by BxSMobility** [comment]
Same issue here

**Comment by bishop87** [comment]
I tried to implement a custom style like 
`    <style name="AppTheme.ClusterIcon.TextAppearance" parent="AppTheme">
        <item name="android:fontFamily">sans-serif</item>
        <item name="android:textStyle">bold</item>
        <item name="android:textSize">16sp</item>
        <item name="android:textColor">@color/simple_white</item>
    </style>`
But the result is the same: transparent text on cluster items.

**Comment by mengoni** [comment]
Thanks @bishop87 your fix works for me!
