### ISSUE TITLE
Generate APK with ProGuard fails with 0.4.4

### ISSUE THREAD

**Issue by fmagalhaes** [googlemaps/android-maps-utils#316]
In version 0.4.4, when trying to Build APK with ProGuard enabled, the build fails with this exception:
Warning:com.google.maps.android.clustering.ClusterManager: can't find superclass or interface com.google.android.gms.maps.GoogleMap$OnCameraIdleListener
Warning:com.google.maps.android.clustering.ClusterManager: can't find referenced class com.google.android.gms.maps.GoogleMap$OnCameraIdleListener
Warning:there were 4 unresolved references to classes or interfaces.
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForQaRelease'.

> java.io.IOException: Please correct the above warnings first.

Downgrading to version 0.4.2 solved the issue

**Comment by Vandalko** [comment]
what version of Google Play Services do you use ?
the API was changed recently https://github.com/googlemaps/android-maps-utils/pull/295/files
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap
