### ISSUE TITLE
[Question] - InfoWindow touch propagate to childView ?

### ISSUE THREAD

**Issue by Jerome67000** [googlemaps/android-maps-utils#319]
Hi,

For a project I need to handle touch inside InfoWindow at a specific children view.

I have a Custom GoogleMap.InfoWindowAdapter returning a listview when getInfoWindow() is called. Each row of this ListView represent a ClusterItem with a label and a left and right ImageButton. How can I handle the click specifically on the right OR left ImageButton ?

`map.setOnInfoWindowClickListener(clusterManager);`

this methods can't propage the touch to childsView :
`clusterManager.setOnClusterItemClickListener()`
`clusterManager.setOnClusterItemInfoWindowClickListener()`

**Screenshots:** 
![sans titre](https://cloud.githubusercontent.com/assets/7358899/19240812/5c9d5e06-8f0c-11e6-9ef7-a3e32e398d3b.png)

**Device and Android version:** 
Android 6.0
android-maps-utils 0.4.4

**Comment by Vandalko** [comment]
It's actually not related to this particular library. Google Maps in Android simply render your view and show it as image. So your views can't react to the clicks (or touches). For example, 3 years old question on SO http://stackoverflow.com/questions/20283539/button-onclicklistener-on-infowindow-in-google-map

Probably, the simplest way to achieve required result is to simply show custom Dialog at the location of Marker.

You may also play with overlay layout to get map scroll working when info window is shown, but it would require additional work (time investment)

**Comment by Jerome67000** [comment]
Thanks for your answer, very usefull ! I close the issue
