### ISSUE TITLE
This project support android studio not Eclipse ?

### ISSUE THREAD

**Issue by userhuman** [googlemaps/android-maps-utils#324]
Now I develop android studio. I want to integrate with my project.

Thank you.

**Comment by jeffdgr8** [comment]
The library supports Android Studio. Just follow the [setup guide](https://developers.google.com/maps/documentation/android-api/utility/setup).

**Comment by barbeau** [comment]
Here are some general tips about migrating from Eclipse to Android Studio:
https://developer.android.com/studio/intro/migrate.html#migrate-eclipse

If you have specific issues after the migration in terms of getting this library to run with your migrated app, please open a new issue with details on the problem you're having.  Thanks!
