### ISSUE TITLE
Handy ways to implement uniqueness for markers

### ISSUE THREAD

**Issue by natario1** [googlemaps/android-maps-utils#340]
As per title, I’d like to have a version of `ClusterManager.addItem(T)` and `ClusterManager.addItems(Collection<T>)` where item is not added if already present.
 
Would this be interesting to anyone?

Do you have any pointers to how this could be achieved?
Collections seem to be always backed up by `ArrayList`. I could have a wrapper and keep a second copy of markers in a `Set`, but that does not seem ideal.

It would be nice if we had something (Algorithm? I’m not confident with the source right now) already backed up by `Set`.

Hints or thoughts?

_(If you are wondering, this is the use case:
For performance reasons, I query the database for only 100 items (that will become markers)._

```
query.near(centerOfMap);
query.limit(100);
items = query.find();
manager.addItems(items);
```

_When the map is panned beyond a certain threshold, a new query is triggered, with a new centerOfMap. But it might be that some of the fetched items was already present in the previous query, thus the need of a uniqueness check)._

**Comment by barbeau** [comment]
FWIW, I've implemented this concept outside of the android-maps-utils library, specifically for showing bus stops on a map:
https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/StopOverlay.java#L668

Use case is very similar to what you say - we have a server-side API to get bus stops within a geographic bounds, and we hit the API when the user pans the map with the new geographic bounds.  The set of stops we get back may or may not already exist on the map depending on where the user has previously scrolled.  HashMaps are used to track what's already been added.  When the number of markers on the map exceeds a fixed threshold, the map is wiped clean and you start over.
