### ISSUE TITLE
Render a cluster item as marker after removing it from cluster in android

### ISSUE THREAD

**Issue by RishabJaiswal** [googlemaps/android-maps-utils#343]
I am trying to move a clusterItem as a marker on a map when it is clustered in a Cluster(even if it's marker has not been rendered yet).

I remove that cluster item from cluster(clusterManager.remove(clusterItem)) and then try to get it rendered as a Google Map marker and then add it back. I took the following approach

     ` Marker marker = markers.get(position);   
      clusterManager.removeItem(clusterItem);
       LatLng latLng = new LatLng(Double.valueOf(lat), 
      Double.valueOf(long));
      if(marker!=null)
             marker.setPosition(latLng)
      clusterItem.setPosition(latLng);
      clusterManager.addItem(friend);`

The problem is that clusterItem gets removed from the cluster but the number shown on cluster is wrong(i.e still the old one), also, I wont get correct number until I zoom in/out(when clusters are rendered again).

How can I get cluster item's indvidual marker after removing it from cluster? or Is there any way that when I change the position of clusterItem then it automatically moves to the desired position without me have to render the marker and change the position manually and adding it back to clusterManger.

**Comment by SunmerCho** [comment]
Have you try clusterManager.cluster() again afater you add your items?

**Comment by rahul860366** [comment]
I faced a similar issue, but I got this working.
I reset the CustomClusterRenderer to clusterManager everytime the dataset changed, instead of clearing the data from clusterManager.
