### ISSUE TITLE
Markers which are really far forms a cluster

### ISSUE THREAD

**Issue by Malikkhoja** [googlemaps/android-maps-utils#350]
Markers which are really far off from each other forms a cluster. I want to set the radius in such a way that markers nearby to each other only forms a cluster. 

**Steps to reproduce:** 
1. Add a marker which are far from each other and zoom out. It would automatically form a cluster.

**Expected behavior:** 

1. Marker close to each other should only form a cluster.

**Observed behavior:** 
1. Marker which are far from each other forms a cluster

6.0 MarshMellow

**Comment by jeffdgr8** [comment]
I've made this configurable in my pull request: https://github.com/googlemaps/android-maps-utils/pull/339
