### ISSUE TITLE
Map Marker animation

### ISSUE THREAD

**Issue by shankarpilli** [googlemaps/android-maps-utils#358]
Hi , I have googled for map marker animations But i didn't found any clear doc for animating the map marker. If i want to show a map marker like water bobble for same place to come on map. Can you help me how to do that.  In the Ios we found pop and push animations. but in android not there any animations to show list of markers.

**Comment by barbeau** [comment]
@shankarpilli Take a look at https://github.com/googlemaps/android-maps-utils/issues/171, and please comment on that thread if it doesn't meet the use case you're looking for.
