### ISSUE TITLE
Custom marker, background display mismatch

### ISSUE THREAD

**Issue by rongdongliu** [googlemaps/android-maps-utils#359]
nexus 5x
Android 6.0.1
android-maps-utils 
[https://github.com/rongdongliu/TweenAnimation/blob/master/img/marker.png](url)

nexus5
Android 5.1.1
[https://github.com/rongdongliu/TweenAnimation/blob/master/img/device-2017-02-17-175728.png](url)

xiaomi miui8
Android 5.1.1
[https://github.com/rongdongliu/TweenAnimation/blob/master/img/device-2017-02-17-180121.png](url)
Nexus mobile phone, but misplaced?

**Comment by stephenmcd** [comment]
What was the solution?
