### ISSUE TITLE
java.lang.NullPointerException 	at com.google.maps.api.android.lib6.impl.cz.onClick(:com.google.android.gms.DynamiteModulesB:3055)

### ISSUE THREAD

**Issue by rongdongliu** [googlemaps/android-maps-utils#386]
--------- beginning of /dev/log/main
04-01 23:22:16.827     0     0 W AEE     : some logs have been lost (90 bytes estimated)
04-01 23:22:16.827 10480 10995 D libc-netbsd: getaddrinfo: clients4.google.com get result from proxy >>
04-01 23:22:16.828 10480 10997 D libc-netbsd: getaddrinfo: clients4.google.com get result from proxy >>
04-01 23:22:16.832 10480 10996 D libc-netbsd: getaddrinfo: clients4.google.com get result from proxy >>
04-01 23:22:16.845 10480 10994 D libc-netbsd: getaddrinfo: clients4.google.com get result from proxy >>
04-01 23:22:21.347 10480 10480 E DEBUG   : begin to generate java report
04-01 23:22:21.358 10480 10480 E DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-01 23:22:21.360 10480 10480 E DEBUG   : Basic Information: 'pid: 10480/tid: 10480/logver: 2/time: 20170401232221/cpu: armeabi-v7a/cpu hardware: mt6572'
04-01 23:22:21.360 10480 10480 E DEBUG   : Mobile Information: 'model: Aqua Air/version: 4.4.2/sdk: 19'
04-01 23:22:21.361 10480 10480 E DEBUG   : Build fingerprint: 'DEXP/IxionE25/IxionE25:4.4.2/KOT49H/20151208100727:user/test-keys'
04-01 23:22:21.361 10480 10480 E DEBUG   : Runtime Information: 'start: 20170401231553/maxheap: 100663296'
04-01 23:22:21.362 10480 10480 E DEBUG   : Application Information: 'version: 2.2.0/subversion: release/buildseq: 170401141000'
04-01 23:22:21.362 10480 10480 E DEBUG   : CrashSDK Information: 'version: 1.5.0.0/nativeseq: 0/javaseq: 160318104655/target: release'
04-01 23:22:21.362 10480 10480 E DEBUG   : Report Name: 
04-01 23:22:21.362 10480 10480 E DEBUG   : UUID: 65f97f05-1578-44d5-b190-a8f9492ee024
04-01 23:22:21.362 10480 10480 E DEBUG   : Log Type: java
04-01 23:22:21.362 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-01 23:22:21.363 10480 10480 E DEBUG   : imei
04-01 23:22:21.363 10480 10480 E DEBUG   : : 
04-01 23:22:21.363 10480 10480 E DEBUG   : 911475556***
04-01 23:22:21.363 10480 10480 E DEBUG   : country
04-01 23:22:21.363 10480 10480 E DEBUG   : : 
04-01 23:22:21.363 10480 10480 E DEBUG   : in
04-01 23:22:21.363 10480 10480 E DEBUG   : bid
04-01 23:22:21.363 10480 10480 E DEBUG   : : 
04-01 23:22:21.363 10480 10480 E DEBUG   : 1
04-01 23:22:21.363 10480 10480 E DEBUG   : isRoot
04-01 23:22:21.364 10480 10480 E DEBUG   : : 
04-01 23:22:21.364 10480 10480 E DEBUG   : false
04-01 23:22:21.364 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-01 23:22:21.364 10480 10480 E DEBUG   : Process Name: 'com.infr**
04-01 23:22:21.364 10480 10480 E DEBUG   : Thread Name: 'main'
04-01 23:22:21.366 10480 10480 E DEBUG   : Back traces starts.
04-01 23:22:21.366 10480 10480 E DEBUG   : java.lang.NullPointerException
04-01 23:22:21.366 10480 10480 E DEBUG   : 
04-01 23:22:21.366 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.366 10480 10480 E DEBUG   : com.google.maps.api.android.lib6.impl.cz.onClick(:com.google.android.gms.DynamiteModulesB:3055)
04-01 23:22:21.367 10480 10480 E DEBUG   : 
04-01 23:22:21.367 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.367 10480 10480 E DEBUG   : android.view.View.performClick(View.java:4463)
04-01 23:22:21.367 10480 10480 E DEBUG   : 
04-01 23:22:21.367 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.367 10480 10480 E DEBUG   : android.view.View$PerformClick.run(View.java:18789)
04-01 23:22:21.368 10480 10480 E DEBUG   : 
04-01 23:22:21.368 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.368 10480 10480 E DEBUG   : android.os.Handler.handleCallback(Handler.java:808)
04-01 23:22:21.368 10480 10480 E DEBUG   : 
04-01 23:22:21.369 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.369 10480 10480 E DEBUG   : android.os.Handler.dispatchMessage(Handler.java:103)
04-01 23:22:21.369 10480 10480 E DEBUG   : 
04-01 23:22:21.369 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.371 10480 10480 E DEBUG   : android.os.Looper.loop(Looper.java:193)
04-01 23:22:21.371 10480 10480 E DEBUG   : 
04-01 23:22:21.372 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.372 10480 10480 E DEBUG   : android.app.ActivityThread.main(ActivityThread.java:5299)
04-01 23:22:21.372 10480 10480 E DEBUG   : 
04-01 23:22:21.373 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.373 10480 10480 E DEBUG   : java.lang.reflect.Method.invokeNative(Native Method)
04-01 23:22:21.373 10480 10480 E DEBUG   : 
04-01 23:22:21.374 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.375 10480 10480 E DEBUG   : java.lang.reflect.Method.invoke(Method.java:515)
04-01 23:22:21.375 10480 10480 E DEBUG   : 
04-01 23:22:21.376 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.376 10480 10480 E DEBUG   : com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
04-01 23:22:21.377 10480 10480 E DEBUG   : 
04-01 23:22:21.378 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.379 10480 10480 E DEBUG   : com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
04-01 23:22:21.380 10480 10480 E DEBUG   : 
04-01 23:22:21.380 10480 10480 E DEBUG   : 	at 
04-01 23:22:21.381 10480 10480 E DEBUG   : dalvik.system.NativeStart.main(Native Method)
04-01 23:22:21.381 10480 10480 E DEBUG   : 
04-01 23:22:21.382 10480 10480 E DEBUG   : Back traces ends.
04-01 23:22:21.382 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-01 23:22:21.383 10480 10480 E DEBUG   : meminfo:
04-01 23:22:21.383 10480 10480 E DEBUG   : MemTotal:         477736 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : MemFree:            7944 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Buffers:            3500 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Cached:            90560 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : SwapCached:        15140 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Active:           134720 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Inactive:         150240 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Active(anon):     102252 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Inactive(anon):    90572 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Active(file):      32468 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Inactive(file):    59668 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Unevictable:        1728 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Mlocked:               0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : HighTotal:             0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : HighFree:              0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : LowTotal:         477736 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : LowFree:            7944 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : SwapTotal:        393212 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : SwapFree:         204956 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Dirty:               264 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Writeback:             0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : AnonPages:        191192 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Mapped:            40736 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Shmem:                52 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Slab:              28448 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : SReclaimable:       9560 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : SUnreclaim:        18888 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : KernelStack:        8784 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : PageTables:        10292 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : NFS_Unstable:          0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Bounce:                0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : WritebackTmp:          0 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : CommitLimit:      632080 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : Committed_AS:    6839972 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : VmallocTotal:     516096 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : VmallocUsed:       94652 kB
04-01 23:22:21.383 10480 10480 E DEBUG   : VmallocChunk:   
04-01 23:22:21.383 10480 10480 E DEBUG   :   112576 kB
04-01 23:22:21.384 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-01 23:22:21.384 10480 10480 E DEBUG   : status:
04-01 23:22:21.385 10480 10480 E DEBUG   : Name:	.infreewifi.cct
04-01 23:22:21.385 10480 10480 E DEBUG   : State:	R (running)
04-01 23:22:21.385 10480 10480 E DEBUG   : Tgid:	10480
04-01 23:22:21.385 10480 10480 E DEBUG   : Pid:	10480
04-01 23:22:21.385 10480 10480 E DEBUG   : PPid:	152
04-01 23:22:21.385 10480 10480 E DEBUG   : TracerPid:	0
04-01 23:22:21.385 10480 10480 E DEBUG   : Uid:	10150	10150	10150	10150
04-01 23:22:21.385 10480 10480 E DEBUG   : Gid:	10150	10150	10150	10150
04-01 23:22:21.385 10480 10480 E DEBUG   : FDSize:	256
04-01 23:22:21.385 10480 10480 E DEBUG   : Groups:	1015 1028 3003 50150 
04-01 23:22:21.385 10480 10480 E DEBUG   : VmPeak:	  479488 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmSize:	  440788 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmLck:	       0 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmPin:	       0 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmHWM:	   49448 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmRSS:	   46720 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmData:	   92676 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmStk:	     136 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmExe:	       8 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmLib:	   49352 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmPTE:	     260 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : VmSwap:	   13416 kB
04-01 23:22:21.385 10480 10480 E DEBUG   : Threads:	67
04-01 23:22:21.385 10480 10480 E DEBUG   : SigQ:	0/3724
04-01 23:22:21.385 10480 10480 E DEBUG   : SigPnd:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : ShdPnd:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : SigBlk:	0000000000009204
04-01 23:22:21.385 10480 10480 E DEBUG   : SigIgn:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : SigCgt:	00000002000094b8
04-01 23:22:21.385 10480 10480 E DEBUG   : CapInh:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : CapPrm:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : CapEff:	0000000000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : CapBnd:	ffffffe000000000
04-01 23:22:21.385 10480 10480 E DEBUG   : Cpus_allowed:	3
04-01 23:22:21.385 10480 10480 E DEBUG   : Cpus_allowed_list:	0-1
04-01 23:22:21.385 10480 10480 E DEBUG   : voluntary_ctxt_switches:	37762
04-01 23:22:21.385 10480 10480 E DEBUG   : nonvoluntary_ctxt_switches:	59155
04-01 23:22:21.385 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
04-01 23:22:21.385 10480 10480 E DEBUG   : Dalvik:
04-01 23:22:21.385 10480 10480 E DEBUG   : MaxMemory: 100663296 TotalMemory: 17248256 FreeMemory: 2047992
04-01 23:22:21.385 10480 10480 E DEBUG   : --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---

**Comment by barbeau** [comment]
From a quick look at the stack trace, it looks like this is related to the Android Maps API v2 and Google Play Services - `com.google.maps.api.android.lib6.impl.cz.onClick(:com.google.android.gms.DynamiteModulesB:3055)`.  

Application ID for this library is `com.google.maps.android`, so the above exception doesn't seem to be related to this library.  Therefore, I'm closing out this issue.

The next question is "where is the proper place to report this stack trace"?  Great question - I actually have an open StackExchange question for this here - http://android.stackexchange.com/questions/53354/where-should-issues-with-google-play-services-e-g-fused-location-provider-be.

Quick answer - doesn't seem to be a great place.  If anyone watching this thread knows, please speak up!  :)
