### ISSUE TITLE
add Google maps utils dependency to travis ci

### ISSUE THREAD

**Issue by aminyazdanpanah** [googlemaps/android-maps-utils#398]
Hi there,
I have Github repository that uses google maps utils and builds with travis ci:
https://github.com/aminyazdanpanah/google-maps-3D-pie-chart-marker-clustering-java
how can I add google maps utils dependency to .travis.yml
my .travis.yml is here:
https://github.com/aminyazdanpanah/google-maps-3D-pie-chart-marker-clustering-java/blob/master/.travis.yml

**Comment by barbeau** [comment]
@aminyazdanpanah You shouldn't need to include anything special to build an app on Travis CI that uses the android-maps-utils project.  Here's an example of one that does:
https://github.com/OneBusAway/onebusaway-android/blob/master/.travis.yml
