### ISSUE TITLE
How can I add marker dynamically?

### ISSUE THREAD

**Issue by swanhtet1992** [googlemaps/android-maps-utils#40]
Are there ways to add markers dynamically depending on the area of the map which is shown?
I found that Android Map Extensions [https://code.google.com/p/android-maps-extensions/] has this functionality.
Can we be also achieve like that with this library?

I don't want to switch library since this library is very convenient. :smile_cat: 

Thanks,
SH

**Comment by pandaSoftGroup** [comment]
googleMap.setOnMapClickListener(new GoogleMap.OnMapClickListener() {
				@Override
				public void onMapClick(LatLng latLng) {
					MarkerOptions marker = new MarkerOptions().position(
							latLng)
							.title("Hello Maps ");
					marker.icon(BitmapDescriptorFactory
							.defaultMarker(BitmapDescriptorFactory.HUE_AZURE));
					googleMap.addMarker(marker);
				}
			});
