### ISSUE TITLE
GeoJSON Layer parses lat lng backwards

### ISSUE THREAD

**Issue by gettdorsamet** [googlemaps/android-maps-utils#401]
**Summary:** 

When feeding the parseCoordinate(JSONArray coordinates) method coordinates it says:
return new LatLng(coordinates.getDouble(1), coordinates.getDouble(0));
when it should be
return new LatLng(coordinates.getDouble(0), coordinates.getDouble(1));

**Steps to reproduce:** 

Send a lat lng array with two doubles,
It shows the opposite location

**Expected behavior:** 

It should show the correct lat lng location

**Comment by stephenmcd** [comment]
GeoJSON defines coordinates in lng/lat format.
