### ISSUE TITLE
Adding OnFeatureClickListener on multiple GeoJsonLayers won't work

### ISSUE THREAD

**Issue by raiffeisennet** [googlemaps/android-maps-utils#402]
When you're having multiple GeoJsonLayers and you'll set on each of these a OnFeatureClickListener, the last one set overrides all others, as it overrides the OnMarkerClickListener for the whole GoogleMap object. So it is not possible to have listeners for each layer.

I'd like to be able to set different (or also the same) OnFeatureClickListeners on multiple existing GeoJsonLayers.

**Comment by arpanbose** [comment]
I'm facing similar issue while adding multiple GeoJsonLayers the last layer's OnFeatureClickListeners overrides all other OnFeatureClickListeners.

**Comment by jasonflaherty** [comment]
[GeoJsonDemoActivity.zip](https://github.com/googlemaps/android-maps-utils/files/1579805/GeoJsonDemoActivity.zip)
I am coming hear to report a very similar if not the same issue. I thought it was my data, but I downloaded the demo app, added the clustering demo to the geojson demo and get the same issue. 

Basically my issue is clicking on a marker will also trigger the feature click listener on a random layer, though it is always the same random layer when I reload my app. Attached is the combined GeoJsonDemoActivity.java

**Comment by satendrarocks** [comment]
OnFeatureClickListener, is not working on multiple GeoJsonLayers
