### ISSUE TITLE
OnMarkerClickedListener doesn't return the correct clicked Marker

### ISSUE THREAD

**Issue by syntaxerror007** [googlemaps/android-maps-utils#403]
When several overlapped marker are added on map, the OnMarkerClickedListener doesn't return the correct clicked Marker. It keeps returning the Marker that has lowest z-index (which is the most bottom) in the area that has the overlapping section.

For example, if the marker is the red, green and blue box and I clicked the bottom right of red Marker, OnMarkerClick give the green Marker.
![screen shot 2017-06-13 at 11 14 48 am](https://user-images.githubusercontent.com/6532476/27065786-9943e47c-5029-11e7-8b81-36b8858e91a0.png)

Can it be fixed? Or is there any suggestion how to fix this?

Thanks

**Comment by stephenmcd** [comment]
That seems unrelated to this library, and an issue with the maps SDK on Android instead, which has issue tracked here: https://issuetracker.google.com/issues/new?component=188870&template=789004

**Comment by syntaxerror007** [comment]
okay, thanks :)
