### ISSUE TITLE
cluster items from database

### ISSUE THREAD

**Issue by nurcita** [googlemaps/android-maps-utils#411]
im developing news center app, and just a beginner in developing app, espesially map android. i need to show my news location data into cluster item, how could it be? please help? i can't find any source?

**Comment by bitpit** [comment]
I'm working on something similar, my immediate naive implementation is to start zoomed in on the user location and load items from the database based on the coordinate box visible in the map rect (using something like Android's `map.getProjection().getVisibleRegion()` to get the min/max latlng coordinates of the visible map box), then re-loading the data as needed via the same strategy as the user zooms and pans.
