### ISSUE TITLE
MapClickListener not works over KML Layer

### ISSUE THREAD

**Issue by erickvelasco11** [googlemaps/android-maps-utils#420]
I want to add map markers on a KML Layer, but when I touch on the KML Layer, the event of Map Listener isn't fired, but when I touch out of the layer, the event is fired normally.

**Device and Android version:** 

I'm using a Sony Xperia XA Ultra F3213 with Android 7.0 but we can reply on Samsung SM-J700M with Android 6.0.1
This issue born in 0.5 realease, in 0.4.+ all works fine.

**Comment by jeffdgr8** [comment]
This is fixed in my pull request https://github.com/googlemaps/android-maps-utils/pull/380.

**Comment by jeffdgr8** [comment]
This is still an issue until https://github.com/googlemaps/android-maps-utils/pull/380 is merged.
