### ISSUE TITLE
How to animate marker every 10 seconds after cluster rendered?

### ISSUE THREAD

**Issue by ThameemAK** [googlemaps/android-maps-utils#421]
In my App, I have to display 100 - 200 markers, whenever its latlng change i will get update of new latlng for some marker.

if the marker not inside the cluster, i have to animate the marker from old latlng to new latlng.
Any ideas for how I can solve this?

**Comment by ulaserdegor** [comment]
Same problem. I working on this. What is status? @ThameemAK
