### ISSUE TITLE
map view crops when not in fullscreen

### ISSUE THREAD

**Issue by frenzyfrenzyfrenzy** [googlemaps/android-maps-utils#425]
**Summary:** 

I've tried to display maps through SupportMapFragment in my app and first I tried to do it not in full screen, like so:

```
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/activity_main_layout_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <fragment
        android:id="@+id/map"
        android:name="com.google.android.gms.maps.SupportMapFragment"
        android:layout_width="match_parent"
        android:layout_height="400dp" />
</FrameLayout>
```
And what I got is that map was cropped: 
![cropped](https://user-images.githubusercontent.com/17321582/30632105-98b870ea-9def-11e7-877e-2b14f0a2dfdc.png)

(look at greenland, I can't scroll anyway further on top)

But when I changed height of fragment (id=map) to match_parent map became fullsize:

![full](https://user-images.githubusercontent.com/17321582/30632144-bf1dcdac-9def-11e7-879c-b2e076603985.png)

So is there a way not to crop the map while displaying it not fullscreen?

My activity's code is:

```
public class MainActivity extends AppCompatActivity implements OnMapReadyCallback {

    @BindView(R.id.activity_main_layout_root)
    FrameLayout layoutContainer;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ButterKnife.bind(this);

        SupportMapFragment mapFragment = (SupportMapFragment) getSupportFragmentManager()
                .findFragmentById(R.id.map);
        mapFragment.getMapAsync(this);

    }

    @Override
    public void onMapReady(GoogleMap googleMap) {
        googleMap.getUiSettings().setScrollGesturesEnabled(true);
    }
}
```

**Comment by stephenmcd** [comment]
Not sure what the exact solution is, but this isn't specific to this library in any way.
