### ISSUE TITLE
computeDistanceBetween shows aerial distance or road distance?

### ISSUE THREAD

**Issue by sandeep2242** [googlemaps/android-maps-utils#429]
**Summary:** 
I am using computeDistanceBetween for calculating distance between two points , but the results is much greater than the original results ie. Result is 12627.6 km where it should be 29.4km . And i guess aerial distance is less than road distance. 

**Steps to reproduce:** 
providing an example doc

**Expected behavior:** 
Result is 12627.6 km where it should be 29.4km  ie minimum road distance between two points.

**Observed behavior:** 
distance is much larger than expected

**Device and Android version:** 
one plus2 api23

**Screenshots:** 

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Comment by barbeau** [comment]
@sandeep2242 Can you please provide the values you're using as input to the `computeDistanceBetween()` method?

**Comment by farhanshahid108** [comment]
I have the same issue here. If i use computeDistanceBetween() function it give me random and in accurate values as distance.

**Comment by barbeau** [comment]
@farhanshahid108 could you please provide the input values you're using, the output you expect, and the output you're actually getting?

**Comment by farhanshahid108** [comment]
Salam,
I am using IONIC 3 google maps plugins from official ionic site. According to index.d.ts file (inside product/node_modules/@ionic-native/google-maps) i have import the following ts file into my main home.ts file and code is below.

let sFrom : LatLng = new LatLng(31.5043105,74.3559769);
let sTo : LatLng = new LatLng(31.519611, 74.411572);
var dis = Spherical.computeDistanceBetween(sFrom,sTo);
console.log(dis);
