### ISSUE TITLE
LineString is invisible on Maps

### ISSUE THREAD

**Issue by MichaelBodnar** [googlemaps/android-maps-utils#434]
**Summary:** 

I'm tring to draw a line whicha base on set of coordinates, but when i parse this file and adding to map nothing happens.
I attached this file.

OS: Android
Device: Everywhere

I'm loading the file from assets, snippet code bellow:
private void prepareKMLLayer(GoogleMap map) {
        try {
            KmlLayer layer = new KmlLayer(
                    map,
                    getAssets().open("coords.kml"),
                    this
            );
            layer.addLayerToMap();
        } catch (XmlPullParserException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

Everything what i see is empty map without my line
![screenshot_20171107-220125](https://user-images.githubusercontent.com/5896911/32515066-8cfc7c68-c407-11e7-802d-5a6bf67e256c.png)
[coords.zip](https://github.com/googlemaps/android-maps-utils/files/1451445/coords.zip)

**Comment by Zephyr2627** [comment]
did you solve this issue ? Can you tell me how to solve this problem ??
