### ISSUE TITLE
Items not "declustered" (broken into smaller items) after map zooms in

### ISSUE THREAD

**Issue by vanjabobotic** [googlemaps/android-maps-utils#443]
**Summary:** 

When you zoom in, some items stays in cluster, no matter how close you zoom in.

**Steps to reproduce:** 

Unfortunately, I'm not sure. It happens all the time, but only for some locations.

**Expected behavior:** 

I'm expecting to see the "broken" clusters when the map is zoomed in.

**Observed behavior:** 

Instead, the items are clustered all the time, whether you click on the cluster on zoom in.

**Device and Android version:** 

It happens on any Android device with any Android I've tried (>5.0), the stock version ROM from the manufacturer.

**Screenshots:** 

![screenshot_20180209-143302](https://user-images.githubusercontent.com/10962710/36849580-b4527c84-1d64-11e8-9694-1d38358ed5f5.png)
[2018_03_01_15_23_16.mp4.zip](https://github.com/googlemaps/android-maps-utils/files/1771474/2018_03_01_15_23_16.mp4.zip)

**Comment by real-artswan** [comment]
Got the same problem with web page
![image](https://user-images.githubusercontent.com/3417195/37024880-ce390862-2132-11e8-9720-5613a32035fe.png)

**Comment by manoelarandaneto** [comment]
did you try changing the code below?

`@Override
protected boolean shouldRenderAsCluster(Cluster cluster) {
    return cluster.getSize() > 2;
}`

if the pins are so close, it's natural that they will keep as a cluster since would be a mess to understand them

**Comment by real-artswan** [comment]
I can say that in my case pins are not close at all, in fact there are no any pin closer than few tens kilometers around the marker on my screenshot. My pins are real house addresses.

**Comment by Gaetano-Dati** [comment]
Has this problem been solved in some way?

**Comment by emadimehrdad** [comment]
When pins are so close and the map zoomed in high level, pins don't uncluster.how to fix this problem?

**Comment by barbeau** [comment]
Looks like @gusthavosouza solved this in his comment above - https://github.com/googlemaps/android-maps-utils/issues/443#issuecomment-524895279.

If this solution doesn't work for anyone please re-open this issue. Thanks!
