### ISSUE TITLE
Can not update marker icon async

### ISSUE THREAD

**Issue by sanisloandras** [googlemaps/android-maps-utils#447]
**Summary:** 

I am trying to change marker icon. When I set the new marker icon in onClusterItemRendered, I get an exception  IllegalArgumentException: Unmanaged descriptor.

I am downloading an image using Glide as bitmap, converting it using an IconGenerator and BitmapDescriptorFactory. Doing it in onClusterItemRendered() callback. 

**Steps to reproduce:** 

Use this cluster rendered:
`private class UserAvatarRenderer extends DefaultClusterRenderer<UserClusterItem> {
        private final IconGenerator mIconGenerator =
                new IconGenerator(getContext().getApplicationContext());
        private CircleImageView ivAvatar;

        public UserAvatarRenderer(Context context,
                                  GoogleMap map,
                                  ClusterManager<UserClusterItem> clusterManager) {
            super(context, map, clusterManager);
            ivAvatar = new CircleImageView(getContext());
            int dimension = (int) getResources().getDimension(R.dimen.cluster_item_size);
            ivAvatar.setLayoutParams(new ViewGroup.LayoutParams(dimension, dimension));
            ivAvatar.setBorderColor(Color.WHITE);
            ivAvatar.setBorderWidth(4);
            mIconGenerator.setBackground(null);
            mIconGenerator.setContentView(ivAvatar);
        }

        @Override
        protected void onClusterItemRendered(UserClusterItem clusterItem, Marker marker) {
            Log.d(TAG, "onClusterItemRendered: ");
            Glide.with(getContext())
                    .asBitmap()
                    .load(clusterItem.getAvatarUrl())
                    .listener(new RequestListener<Bitmap>() {
                        @Override
                        public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<Bitmap> target, boolean isFirstResource) {
                            if (e != null) e.printStackTrace();
                            return false;
                        }

                        @Override
                        public boolean onResourceReady(Bitmap resource, Object model, Target<Bitmap> target, DataSource dataSource, boolean isFirstResource) {
                            Log.d(TAG, "onResourceReady: " + resource.getHeight() + " / " + resource.getWidth());
                            try {
                                ivAvatar.setImageBitmap(resource);
                                Bitmap icon = mIconGenerator.makeIcon();
                                marker.setIcon(BitmapDescriptorFactory.fromBitmap(icon));
                            } catch (Exception e) {
                                e.printStackTrace();
                                Log.d(TAG, "onResourceReady: e", e);
                            }
                            return true;
                        }
                    })
                    .into(ivAvatar);
        }
    }`

**Expected behavior:** 

I expect the app to render a circled image.

**Device and Android version:**
 
Google Pixel 2, Android 8.1

**Comment by jeffdgr8** [comment]
Asynchronously, the `Marker` reference may not be valid when the callback is received. Instead of using the same `marker` reference in `onResourceReady()`, call `getMarker(clusterItem)` on your cluster renderer to get the current `Marker` for the `UserClusterItem`.
