### ISSUE TITLE
Can't draw circle which encompasses either of poles.

### ISSUE THREAD

**Issue by ControlAdad** [googlemaps/android-maps-utils#453]
**Summary:** 

Hello
I know this is mentioned in document that can't draw circle which encompasses north or south pole, but I would be grateful if you let me know how can I draw this filled circle?

Summary:Can't draw circle which encompasses either of poles.

**Steps to reproduce:** 

circle = mMap.addCircle(new CircleOptions()
                .center(new LatLng(37.4, 88.0))
                .radius(200000)
                .strokeWidth(10)
                .strokeColor(Color.GREEN)
                .fillColor(Color.argb(128, 255, 0, 0))
                .clickable(true);

**Expected behavior:** 

Project a filled circle

**Observed behavior:** 

Draws just outline.

**Device and Android version:** 

Samsung S8, Android 8, Google Play Services 15

**Comment by stephenmcd** [comment]
I don't see anything wrong with your code - but this isn't related to this library at all, so you might want to try stackoverflow.
