### ISSUE TITLE
Add setOnFeatureClickListener on multiple GeoJSON

### ISSUE THREAD

**Issue by DanielCFreitas** [googlemaps/android-maps-utils#456]
I have 3 GeoJsonLayer in my code, and I want to set differents events to each layer, but when I define the last implementation of setOnFeatureClickListener the last implementation override the others layers.

How can i solve that?

**Comment by johnknelsonintific** [comment]
Subscribed to this issue. I'm having the same issue but with KML files. May open a separate issue since technically our input formats our different. I'm lucky at least in that I only need to handle polygons which I think I can massage into Google's polylines.

**Comment by masires** [comment]
I too was looking for a solution to this issue, but there doesn't seem to be one: https://stackoverflow.com/questions/44017057/android-google-maps-geojsonlayer-onfeatureclicklistener-multiple-layers

Only thing left would be to merge all files to a single one and go from there, just as in the example.

**Comment by volmus** [comment]
Still unsolved? :(

**Comment by barbeau** [comment]
Thanks for the report! This was just fixed in the master branch by merging https://github.com/googlemaps/android-maps-utils/pull/380. There is a new MultiLayerDemoActivity in the master branch that demonstrates that multiple KML, GeoJSON layers now work on the same map!
