### ISSUE TITLE
KML renderer should NOT call setInfoWindowAdapter

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#459]
The KML renderer should NOT try to setInfoWindowAdapter for Placemark points. I spent hours trying to resolve why my own InfoWindowAdapter wasn't working until finally discovering that if the KML contained Point features my adapter was being replaced with the utils version in KML renderer.

Adding a special KML infowindow messes up apps that want to create their own. Why does the KML renderer need to have its own?

**Comment by chitgoks** [comment]
The worse thing about this is that it does not even support HTML content.

**Comment by jeffdgr8** [comment]
This is fixed in my pull request https://github.com/googlemaps/android-maps-utils/pull/380.

**Comment by chitgoks** [comment]
Thank you jeff! Awesome!

**Comment by chitgoks** [comment]
hi @jeffdgr8  did they actually approve your pull request? or not yet.

**Comment by chitgoks** [comment]
the project looks dead :(
