### ISSUE TITLE
project not clone

### ISSUE THREAD

**Issue by shariikhan** [googlemaps/android-maps-utils#461]
**Summary:** 

the code on android studio not run give an  gradle issue
Error:Failed to find Build Tools revision 25.0.1
<a href="install.build.tools">Install Build Tools 25.0.1 and sync project</a>
i installed this one again issue is still same
project not working
how i will controll this kindly reply soon

**Comment by XinyueZ** [comment]
maybe duplicated https://github.com/googlemaps/android-maps-utils/issues/469

**Comment by amuramoto** [comment]
This should work now
