### ISSUE TITLE
CLUSTER removeItem doesn't work every time

### ISSUE THREAD

**Issue by CristianCardosoA** [googlemaps/android-maps-utils#468]
**Summary:** 

When I try to remove an item form the cluster the item is not removed.
`removeItem(T item)`

How can we reproduce the issue?

Obtain total of items. algorithm items.count
For example: 100
Then remove an item.
Actual: 100

**Expected behavior:** 
Expected: 99

What did you expect the app to do?

**Observed behavior:** 

Sometimes the cluster remove the item and some other does not.

**Device and Android version:** 
Every android version.

**Comment by matanelliberman** [comment]
i have the same problem. see my issue:
https://github.com/googlemaps/android-maps-utils/issues/486

**Comment by CristianCardosoA** [comment]
I made a simple internal process to remove the item,.
