### ISSUE TITLE
Support API 26

### ISSUE THREAD

**Issue by jakesilver** [googlemaps/android-maps-utils#469]
**Summary:** 
I wanted to confirm that this SDK will meet Android requirements to support API 26 by the November 1st deadline. Currently, the library compilation target is API 25 and I have tested support for API 26, but wanted to confirm.
 
https://developer.android.com/distribute/best-practices/develop/target-sdk#check_and_update_your_sdks_and_libraries

**Comment by XinyueZ** [comment]
I have shipped a PR #470 for the upgrade of the whole project including gradle, SDK etc. I hope the maintainers would care about this.  ❓

**Comment by amuramoto** [comment]
This was upgraded in a recent commit
