### ISSUE TITLE
KMZ Support

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#472]
Hi are there plans to have KMLLayer support KMZ with images?

There are some KMZ files that contain images which is used by the KML file.

**Comment by amuramoto** [comment]
No plans at this time, but please consider sending a PR to add support if you'd like to see it sooner!

**Comment by chitgoks** [comment]
sorry i dont follow. PR as in pull request? doesn't sound right. and where exactly do i file one?

**Comment by amuramoto** [comment]
Yes, pull request. You can implement support and then send us a pull request for review and potential merge into the codebase.

Some info about PRs and how they work is available here: https://help.github.com/en/articles/about-pull-requests

**Comment by jeffdgr8** [comment]
I added KMZ support in https://github.com/googlemaps/android-maps-utils/pull/625.
