### ISSUE TITLE
Last release was in 2016 (0.5). The project is active. Any plan for next release?

### ISSUE THREAD

**Issue by danielesegato** [googlemaps/android-maps-utils#477]
I've noticed lot of cool features added in the code like the ability to set max distance for items in a cluster, clustering only on visible area etc...

But the last release is 0.5 and I can see the repository is still active this day, last commit is dated only 7 days ago.

Why no more releases? Any plan for one?

**Comment by ulaserdegor** [comment]
We are waiting.

**Comment by chitgoks** [comment]
KMLLayer still needs more enhancements
support for animated GIF too

**Comment by simontb** [comment]
I had the same issue as I needed some of the new features and decided to include the dependency with Jitpack: https://jitpack.io/#googlemaps/android-maps-utils

**Comment by chitgoks** [comment]
hey simontb i dont understand. what new features are you talking about

**Comment by simontb** [comment]
@chitgoks things that were added after the 0.5 release that I can grab from the other maven repositories

**Comment by chitgoks** [comment]
wow didnt know that. let me check

**Comment by deplle** [comment]
I agree, It would be nice to have a new release with all the changes that have been made to the repository over the previous years.  Would it be possible for you to do a release soon?  If so, when do you think it will get done?

**Comment by kanadeveloper** [comment]
@simontb thank you for the tips

@chitgoks you can select a sha1, branch or tag
ex:  https://jitpack.io/#googlemaps/android-maps-utils/02455ecc65

**Comment by GerardoRobledo** [comment]
@amuramoto is there any estimated date for a new version?

**Comment by amuramoto** [comment]
In the process of increasing our code coverage so we can safely merge some of the larger PRs, but my goal is for us to cut a new version when the Android Maps SDK v3 exits beta.
