### ISSUE TITLE
How to get a marker knowing its ClusterItem and vice versa?

### ISSUE THREAD

**Issue by AntonioGonzalez** [googlemaps/android-maps-utils#48]
First at all, congratulations!!! Great job (we users ask for something but not thanks given). I started to use this library for few days ago (clustering) and I need to show markers in map, and when user click on them, it must to show the info window showing some information about the marker. Inside this information there is a photo profile from url (http...). As you know, the photo has to be taken in a background task, so when onClusterItemClick listener go out, it downloads the photo, and when it ends, callback has to show info window, so in  onClusterItemClick listener interface I return true ( I have managed the event and this way info window is not showing) but when callback from image download has to show info window but it can not call showInfoWindow method from a marker object because I have no reference to it. Also, I need to consult some information from cluster in InfoWindowAdapter, and in this case, I know the marker but not the clusterItem information.

As solution, I  have tried to give two method to DefaultClusterRenderer<T extends ClusterItem> class:

```
    protected Marker getMarker(T item) {
    return mMarkerCache.get(item);
}

protected T getCluster(Marker marker) {
    return mMarkerCache.get(marker);
}
```

This way I resolve my problem and every was fine until I recived this crash report:

01-30 17:42:50.685: E/ACRA(15290): ACRA caught a ConcurrentModificationException exception for info.si2.android.unidogs.app. Building report.
01-30 17:42:53.513: E/AndroidRuntime(15290): FATAL EXCEPTION: Thread-8895
01-30 17:42:53.513: E/AndroidRuntime(15290): java.util.ConcurrentModificationException
01-30 17:42:53.513: E/AndroidRuntime(15290):    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:792)
01-30 17:42:53.513: E/AndroidRuntime(15290):    at java.util.HashMap$KeyIterator.next(HashMap.java:819)
01-30 17:42:53.513: E/AndroidRuntime(15290):    at java.util.AbstractSet.removeAll(AbstractSet.java:110)
01-30 17:42:53.513: E/AndroidRuntime(15290):    at com.google.maps.android.clustering.view.DefaultClusterRenderer$RenderTask.run(DefaultClusterRenderer.java:383)
01-30 17:42:53.513: E/AndroidRuntime(15290):    at java.lang.Thread.run(Thread.java:856)

 Are this and my methods relationated or is this a independient issue?
Can you confirm me this methods are a good idea in the library?

Thank you, I hope to hear soon about you.

**Comment by jeffdgr8** [comment]
Oh yes, making these maps publicly accessible to get ClusterItem for Marker is a must! How else would you be able to update a ClusterItem's position when dragged for example? You only have the Marker in the OnMarkerDragListener. The problem with rolling your own map, besides duplicating an already present and managed cache, is that Markers are never removed from your map when they're removed from the cluster renderer! So this would surely leak memory.

**Comment by anhTTAsiantech** [comment]
libary ClusterItem where ?
http://www.chuanroi.net/

**Comment by bosung90** [comment]
@ericpanorel Thank you so much!!!!!
