### ISSUE TITLE
Markers visible only on one side of the international date line

### ISSUE THREAD

**Issue by jeffdgr8** [googlemaps/android-maps-utils#491]
**Summary:** 

Markers are only visible on one side of the international date line at the same time.

**Steps to reproduce:** 

Add some markers on the west side and east side of the international date line, where both should be visible on the screen at the same time.

**Expected behavior:** 

All markers should be visible

**Observed behavior:** 

Only markers on one side of the IDL are visible at the same time, whichever side is more on the screen at the time.

**Device and Android version:** 

Pixelbook
Android 7.1.1
Google Play Services Maps 16.0.0

**Screenshots:** 

![screenshot 2018-12-06 at 1 44 38 pm](https://user-images.githubusercontent.com/2053817/49611752-c78e4800-f95f-11e8-976b-2e28aae7a685.png)
![screenshot 2018-12-06 at 1 44 48 pm](https://user-images.githubusercontent.com/2053817/49611758-cc52fc00-f95f-11e8-93cb-d85ace86cf1e.png)

**Comment by jeffdgr8** [comment]
I fixed this in https://github.com/googlemaps/android-maps-utils/pull/564.

**Comment by barbeau** [comment]
Fixed by https://github.com/googlemaps/android-maps-utils/pull/564.
