### ISSUE TITLE
Enabling shrinkResources removes every layer from map

### ISSUE THREAD

**Issue by zboing** [googlemaps/android-maps-utils#493]
**Summary:** 

if the user sets shrinkResources to true in buildTypes from build.gradle the layers on the map are not appearing

**Steps to reproduce:** 

add the line shrinkResources into your buildTypes from build.gradle

**Expected behavior:** 

this line should not impact the layers from the map

**Observed behavior:** 

the layers from the map are not appearing anymore

**Device and Android version:** 

Device OS: Android 
Device OS version: 8.0.0
App Version: 1.0.1
Device Brand: HUAWEI
Device Model: VTR-L29
Device Manufacturer: HUAWEI

*this issue happens also for android.enableR8 = true in gradle.properties

**Comment by zboing** [comment]
Yes, it's still valid. Thank you also.

**Comment by barbeau** [comment]
@zboing I can't reproduce this with the debug build type in the demo app packaged with the library (with master branch at https://github.com/googlemaps/android-maps-utils/commit/122e96b8400af4c2f26f9c6237e3b4394b2a1d6a):
https://github.com/CUTR-at-USF/android-maps-utils/tree/test-shrink-resources

I added:

~~~
    buildTypes {
        debug {
            shrinkResources true
            minifyEnabled true
        }
~~~

I tested with and without `android.enableR8 = true` in `gradle.properties`, but when you go to the "Multi Layer" demo and "Clustering: Custom Look" activities all the layers appear on the map as expected.

Could you provide an example app with steps to reproduce this issue (preferably based on the demo app)?
