### ISSUE TITLE
Google Maps Android SDK - addMarker() seems not work on some type of device

### ISSUE THREAD

**Issue by Trusted97** [googlemaps/android-maps-utils#501]
**Summary:** 

addMarker not work in some device

**Steps to reproduce:** 

add a marker in maps in a Xiaomi,OnePlus,Honor phone ecc..

**Expected behavior:** 

Add correctly the marker

**Observed behavior:** 

The marker is not added and no error is raised

**Device and Android version:** 

Xiaomi with a custom Rom, Honor 10, OnePlus 5T

**Screenshots:**
Soon...

**Comment by Trusted97** [comment]
Resolved, it was an error caused by an expired ssl certificate.

**Comment by barbeau** [comment]
@Trusted97 great, thanks for sharing the solution!
