### ISSUE TITLE
crash with the setOnCameraIdleListener

### ISSUE THREAD

**Issue by zhuxinyu2468** [googlemaps/android-maps-utils#503]
googleMap.setOnCameraIdleListener(new GoogleMap.OnCameraIdleListener() {
            @Override
            public void onCameraIdle() {
                CameraPosition cameraPosition = googleMap.getCameraPosition();
                mobileLocation.updateLocation(cameraPosition.target.latitude, cameraPosition.target.longitude);
            }
        });

I'm writing this for swiping the map to get the coordinates. But it's crashed with the 
googleMap.setOnCameraIdleListener(mClusterManager); in Google map cluster. I'm new in Android. Can someone give me any suggestions pls! Appreciate!

**Comment by amuramoto** [comment]
Hi! Please ask debugging questions on our StackOverflow tag. Github issues are for reporting bugs.

https://stackoverflow.com/questions/tagged/google-maps-android-api-2
