### ISSUE TITLE
Feature click listener triggers an info window for feature marker.

### ISSUE THREAD

**Issue by uburoiubu** [googlemaps/android-maps-utils#507]
https://github.com/googlemaps/android-maps-utils/blob/master/library/src/com/google/maps/android/data/Layer.java#L118

I notice that the method `setOnMarkerClickListener()` returns `true`. This is probably why I get info window opened when feature is clicked. I would like to avoid this info window. 

<img width="148" alt="Снимок экрана 2019-03-29 в 17 09 07" src="https://user-images.githubusercontent.com/21975311/55238363-660f2380-5245-11e9-835c-6d0aae6fa26e.png">

**Comment by barbeau** [comment]
@uburoiubu When testing on the [master branch](https://github.com/googlemaps/android-maps-utils/commit/c7213cf192e243d4b7d44567bbdc110d52c899b6) using the `MultiLayerDemoActivity`, I don't see any info windows for KML or GeoJSON polylines or polygons. The marker info window appears if the title is set like this:

~~~
MarkerManager.Collection markerCollection = markerManager.newCollection();
markerCollection.addMarker(new MarkerOptions()
		.position(new LatLng( 51.150000, -0.150032))
		.title("My marker"));
~~~

...but if you don't set the title then no info windows appears:

~~~
MarkerManager.Collection markerCollection = markerManager.newCollection();
markerCollection.addMarker(new MarkerOptions()
		.position(new LatLng( 51.150000, -0.150032)));
~~~

Could you please check out the latest version of the library and re-open if you're still having issues?  Thanks!
