### ISSUE TITLE
nderstanding of google map marker algorithm, renderer concept and ClusterManager class

### ISSUE THREAD

**Issue by alexd555** [googlemaps/android-maps-utils#510]
I tried to search description of algorithms for markers but I can't find.

My questions are:

What are the major algorithms for google map marker ? What do they do ?
What is renderer ?
Why is it cluster ?

Thanks, 
Alex

**Comment by amuramoto** [comment]
Hi! GitHub issues are for reporting bugs, feature requests, etc. Please ask general programming questions on our stackoverflow tag:

https://stackoverflow.com/questions/tagged/google-maps
