### ISSUE TITLE
Load icon from url as cluster icon using glide

### ISSUE THREAD

**Issue by Nininea** [googlemaps/android-maps-utils#512]
I use dynamic icon for each cluster item  , so I have special icon url and  load marker icon from url .  I user following code :

   ```
 override fun onBeforeClusterItemRendered(item: T, markerOptions: MarkerOptions?) {
       super.onBeforeClusterItemRendered(item, markerOptions)

        try {
        var url = URL("https://cdn3.iconfinder.com/data/icons/places/100/map_pin_big_1-128.png") 
        //I use static url, to ensure that url is not null, it should be (item as MyItem).iconURL. got same result anyway
            Glide.with(context)
                .asBitmap()
                .load(url)
                .into(object : CustomTarget<Bitmap>() {
                    override fun onLoadCleared(placeholder: Drawable?) {
                    }

                    override fun onResourceReady(resource: Bitmap, transition: Transition<in Bitmap>?) {
                        markerOptions?.icon(BitmapDescriptorFactory.fromBitmap(resource))
                    }

                })

        } catch (ex: Exception) {
            Log.e("map", ex.toString())
        }
    }
```

some icons still default in my case, after zoom in zoom out icon changes sometimes. The problem is that this code is not works for every cluster item , after zoom changed cluster icon is changed too, it may render my custom icon and may use default.
![Screenshot_20190424-114305](https://user-images.githubusercontent.com/6938188/56641938-73260380-6687-11e9-8d2b-9be7877d9eb0.png)
![Screenshot_20190424-114326](https://user-images.githubusercontent.com/6938188/56641939-73be9a00-6687-11e9-9f6c-b26edc6d0c84.png)

**Comment by teknolojia** [comment]
@Nininea I have the same issue! Have you found solution?

**Comment by tanujsareen** [comment]
@Nininea , I have the same issue also... Any1 one find the solution for that ??

**Comment by donghae0414** [comment]
@Nininea  I think this link can help you
https://stackoverflow.com/questions/33663992/google-map-cluster-with-url

**Comment by arriolac** [comment]
Thank you for reporting. This is a known unresolved issue. You can see #90 and #417 for some possible workarounds.
