### ISSUE TITLE
how to show label in geojson feature?

### ISSUE THREAD

**Issue by ghopretz** [googlemaps/android-maps-utils#513]
how to show label in geojson feature?

**Comment by amuramoto** [comment]
Take a look at this link in our demo app using `GeoJsonPointStyle`:

https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/com/google/maps/android/utils/demo/GeoJsonDemoActivity.java#L89

**Comment by ghopretz** [comment]
Can it applied in geojson which only contain multipolygon?

**Comment by amuramoto** [comment]
`GeoJsonPointStyle` applies the label to the feature, so should work.

**Comment by ghopretz** [comment]
Please, give sample code of that.
