### ISSUE TITLE
Version for Android Maps SDK v.3.0.0

### ISSUE THREAD

**Issue by YuriPopiv** [googlemaps/android-maps-utils#514]
Please provide compatibility with new Maps SDK version.

Currently, this library is not compatible with Maps SDK for Android v.3.0.0 BETA because the package path was changed from` com.google.android.gms.maps package` to `com.google.android.libraries.maps`.

**Comment by systemallica** [comment]
I would also like to see this.

**Comment by ryust** [comment]
So surprised this library wasn't just rolled into the new Maps SDK to begin with.

**Comment by amuramoto** [comment]
Published a beta-compatible version to the android-sdk-v3-beta branch in https://github.com/googlemaps/android-maps-utils/pull/515

Thanks for reporting!

**Comment by systemallica** [comment]
How can I use this new version in my app ?

**Comment by amuramoto** [comment]
We just released to maven. Documentation here:

https://developers.google.com/maps/documentation/android-sdk/v3-client-migration#import-the-beta-compatible-utility-library
