### ISSUE TITLE
PolyUtil.distanceToLine() producing incorrect result

### ISSUE THREAD

**Issue by auras** [googlemaps/android-maps-utils#519]
**Summary:** 

PolyUtil.distanceToLine() produces wrong results in some cases

**Steps to reproduce:** 

PolyUtil.distanceToLine(
LatLng(13.384526409208775, 52.498523596997146),
LatLng(13.383257, 52.498945),
LatLng(13.383194, 52.498748)
) ~= 148m

**Expected behavior:** 

The correct result is somewhere between 93 and 97m

**Observed behavior:** 

The returned result is way incorrect.

If I change the point slightly, like let's say
LatLng(13.384605534374716, 52.49860503682293) it will return the correct result of about 98-99m

**Device and Android version:** 

Running on an Android 9 emulator

**Screenshots:** 

N/A

**Comment by barbeau** [comment]
I believe this PR may fix this issue - https://github.com/googlemaps/android-maps-utils/pull/349
