### ISSUE TITLE
Is Google maps API key is free/billable ? 

### ISSUE THREAD

**Issue by prudhvik-wavity** [googlemaps/android-maps-utils#534]
we are using the google maps android API key in Alpha build, we are planning to move this alpha build to production. so, do we need to generate a Restricted API Key to update in Production build? if yes is there any cost applicable for the API hits?

**Comment by amuramoto** [comment]
Map loads on native mobile are free. There would be cost associated with other types of calls like Places.

You definitely should restrict your key for security reasons

https://cloud.google.com/maps-platform/pricing/sheet/
