### ISSUE TITLE
Can you add GeoJsonLayer Info Window?

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#536]
This is not an issue but a question, in GeoJsonLayer can we add infowindows to feature? There's no sample in the code.

**Comment by barbeau** [comment]
@chitgoks Right now info windows are displayed for GeoJSON and KML points as normal markers, but not lines or polygons.

Here's an example from the demo app "GeoJSON Layer":

![image](https://user-images.githubusercontent.com/928045/74037968-5eec9200-498d-11ea-99b3-bfc6e6a25a65.png)

Are info windows for polygons and polylines something you're interested in adding to your app?

I'll close this for now, and if it's something you're interested in we can re-open as a feature request.

**Comment by chitgoks** [comment]
i will get back to you on this. ill check how it looks like. i use the kml from google crisis map.

there are still many features lacking like reading the image that is included in the zip or from a url.

**Comment by barbeau** [comment]
@chitgoks Thanks! Could you open individual issues for each feature that you think is lacking?

**Comment by chitgoks** [comment]
will do sean. thank you
