### ISSUE TITLE
GeoJson Util

### ISSUE THREAD

**Issue by DeveloperLifestylehearing** [googlemaps/android-maps-utils#541]
I need geoJson layer util highlight with canada  map and different marker of business on different province of canada, How can I achieve it?

**Comment by jpoehnelt** [comment]
You might get a quicker response on [StackOverflow with the tag `google-maps-android-api`](https://stackoverflow.com/questions/tagged/google-maps-android-api-2?tab=Newest). If you post there please link and close this issue. Thanks!
