### ISSUE TITLE
`OutOfMemoryError` in `makeIcon()` of IconGenerator 

### ISSUE THREAD

**Issue by eliOcs** [googlemaps/android-maps-utils#57]
I'm using the library for its cluster manager. I wanted to customize the cluster appearance so I followed the demo code and used the `IconGenerator` class to help me generate the cluster icon.

I initialize the cluster icon generator with a custom content view:

```
private final IconGenerator mClusterIconGenerator = new IconGenerator(getActivity());
mClusterIconGenerator.setContentView(inflater.inflate(R.layout.cluster_marker, null));
```

My custom view holds a background and a `TextView`:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="60dp"
    android:layout_height="54dp"
    android:background="@drawable/map_cluster_background" >

    <TextView
        android:id="@+id/text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="top|left"
        android:layout_marginLeft="12dp"
        android:layout_marginTop="17dp"
        android:textColor="#FFFFFF"
        android:textSize="14sp"/>

</FrameLayout>
```

Later a custom renderer uses this `IconGenerator` on the `onBeforeClusterRendered` method:

```
final Bitmap icon = mClusterIconGenerator.makeIcon(cluster.getItems().toString());
```

This throws the `OutOfMemoryError` exception. I found out that at least in my device "Samsung S2" the view is not measured correctly and therefore the `makeIcon` method is attempting to create a huge bitmap. (I modified the `IconGenerator` code log the calculated measurements in the `makeIcon` method)

```
Log.d(IconGenerator.class.getName(), "## WIDTH: " + measuredWidth + ", HEIGHT: " + measuredHeight + " ##");
Bitmap r = Bitmap.createBitmap(measuredWidth, measuredHeight, Bitmap.Config.ARGB_8888);
```

The log outputs:

```
 ## WIDTH: 70233, HEIGHT: 104 ##
```

May be there is something wrong with my view, or measuring doesn't work correctly on my device.

**Comment by mdtuyen** [comment]
I have same issue, memory increate very fast when map render cluster. How to decrease it ?
