### ISSUE TITLE
Optimize Performance for loading JSON object in GEOJSON layer in Android

### ISSUE THREAD

**Issue by su-thiri-khit** [googlemaps/android-maps-utils#572]
I have a performance problem in loading JSON object to draw polygon in GeoJson layer in android. I want to be faster than now. How can i improve it. 

Here is the code.

 heatMapLayer = GeoJsonLayer(map, JSONObject(Gson().toJson(featureCollection)))
        heatMapLayer?.features?.forEach {
            var color = it.getProperty("color")
            val polygonStyle = GeoJsonPolygonStyle()
            polygonStyle?.fillColor = Utils.hex2ARgb(170, color ?: error(""))
            polygonStyle?.strokeWidth = 0f
            it.polygonStyle = polygonStyle
            val pointStyle = GeoJsonPointStyle()
            pointStyle.isDraggable = true
            it.pointStyle = pointStyle
        }
        heatMapLayer?.addLayerToMap()

**Comment by su-thiri-khit** [comment]
I have a performance problem in loading JSON object to draw polygon in GeoJson layer in android. I want to be faster than now. How can i improve it. 

Here is the code.

 heatMapLayer = GeoJsonLayer(map, JSONObject(Gson().toJson(featureCollection)))
        heatMapLayer?.features?.forEach {
            var color = it.getProperty("color")
            val polygonStyle = GeoJsonPolygonStyle()
            polygonStyle?.fillColor = Utils.hex2ARgb(170, color ?: error(""))
            polygonStyle?.strokeWidth = 0f
            it.polygonStyle = polygonStyle
            val pointStyle = GeoJsonPointStyle()
            pointStyle.isDraggable = true
            it.pointStyle = pointStyle
        }
        heatMapLayer?.addLayerToMap()

**Comment by barbeau** [comment]
@su-thiri-khit Could you please provide the GeoJSON you're trying to load?

**Comment by barbeau** [comment]
I'm going to close this out - if you're able to provide the GeoJSON please re-open. Thanks!
