### ISSUE TITLE
QuadItem class should be public in NonHierarchicalDistanceBasedAlgorithm

### ISSUE THREAD

**Issue by g012** [googlemaps/android-maps-utils#577]
Hello,

The following function:
`protected Collection<QuadItem<T>> getClusteringItems(PointQuadTree<QuadItem<T>> quadTree, float zoom) {
        return mItems;
    }`
can't be overriden in another package because QuadItem is of visibility `internal`.

I wanted to override this function to return items based on their density so that the cluster center item selection is not random.

Thank you.

**Comment by jeffdgr8** [comment]
Fixed in https://github.com/googlemaps/android-maps-utils/pull/604
