### ISSUE TITLE
KMLDemoActivity not working

### ISSUE THREAD

**Issue by ark200** [googlemaps/android-maps-utils#579]
I was trying to check how to use a KML layer over a google map from android studio. I cloned this application to my desktop to check if the kml layer was able to plot but i couldnt see any kml layer in the map activity.
So please do kindly respond with a solution at the earliest.
Thank you in advance

**Comment by barbeau** [comment]
Thanks @ark200, this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/570, so I'm going to close it. I just opened a fix at https://github.com/googlemaps/android-maps-utils/pull/581.
