### ISSUE TITLE
passing Null "feature" to onFeatureClick when loading multiple KmlLayer

### ISSUE THREAD

**Issue by mjhram** [googlemaps/android-maps-utils#593]
Hi,
**API ver**: android-maps-utils:0.6.2
**OS**: android
**issue**: when adding multiple KmlLayers, the app crashes when clicking on any item in the KmlLayer.
**How to reproduce:**
- add 2 KmlLayers (for example using "`new KmlLayer`" twice)
- click on any item. It will crash, since feature is null in the onFeatureClick!!

               KmlLayer kmlLayer = new KmlLayer(mMap, new ByteArrayInputStream(byteArr), 
               KmlDemoActivity.this);
                kmlLayer.addLayerToMap();
                kmlLayer.setOnFeatureClickListener(new KmlLayer.OnFeatureClickListener() {
                    @Override
                    public void onFeatureClick(Feature feature) {
                        Toast.makeText(KmlDemoActivity.this,
                                "Feature clicked: " + feature.getId(),
                                Toast.LENGTH_SHORT).show();
                    }
                });

**Comment by barbeau** [comment]
@mjhram Thanks for the report! This was just fixed in the master branch by merging https://github.com/googlemaps/android-maps-utils/pull/380. There is a new MultiLayerDemoActivity in the master branch that demonstrates that multiple KML layers (along with GeoJSON, etc.) now work on the same map!
