### ISSUE TITLE
geojsonLayer - setOnFeatureClickListener disables onPolylineClickListener

### ISSUE THREAD

**Issue by Tybion** [googlemaps/android-maps-utils#594]
Version 0.6.2 of com.google.maps.android:android-maps-utils:0.6.2 in Android Studio  3.5.3

Testing on Nexus 5x - Android 8.1.0

Activity set up like so ..

```
class MainActivity : FragmentActivity(), OnMapReadyCallback, OnMapClickListener, OnMapLongClickListener, OnCameraMoveListener,
        OnCameraIdleListener, GoogleMap.OnPolylineClickListener,
        ActivityCompat.OnRequestPermissionsResultCallback, OnInfoWindowClickListener,
        OnInfoWindowCloseListener, PurchasesUpdatedListener {
                     :         :
        // In onMapReady ..
        mMap!!.setOnPolylineClickListener(this)
                     :         :
        // After geojson is read from file ..
        geojsonLayer!!.setOnFeatureClickListener(object : Layer.OnFeatureClickListener {
            override fun onFeatureClick(feature: com.google.maps.android.data.Feature?) {
                        displayGeojsonPopup(feature)
            }
        })
        geojsonLayer!!.addLayerToMap()
```

When I click on a Polyline, after plotting the Polylines on app start, my code works (as it has for a couple of years - this is a production system).

After I retrieve and plot Geoson data on the same map view, the GeojsonLayer listener works as expected, but there is no response from clicking any of the Polylines.

**Comment by barbeau** [comment]
Thanks @Tybion! I believe this should be fixed by PR https://github.com/googlemaps/android-maps-utils/pull/380, which I plan to finish reviewing soon.
