### ISSUE TITLE
GeoJsonFeature - add .tag to GeoJsonFeature.markerOptions

### ISSUE THREAD

**Issue by Tybion** [googlemaps/android-maps-utils#595]
Version 0.6.2 of com.google.maps.android:android-maps-utils:0.6.2 in Android Studio 3.5.3

_GeoJsonFeature.markerOptions_ has ..
.title
.snippet

But there can be an overhead in determining what title and snippet values should be.
To set this in **thousands** of features as they are plotted is wasteful in time and machine resources.

Better to be able to simply add a link to the _GeoJsonFeature_ in a **.tag** attribute as _GeoJsonPoints_ are plotted, and only determine the .title and .snippet for a **single feature** when a _GeoJsonPoint_ marker is tapped.

Note that taps of _GeoJsonPoints_ **do not** go through the _GeoJsonLayer_ listener.

```
geojsonLayer!!.setOnFeatureClickListener(object : Layer.OnFeatureClickListener {
      override fun onFeatureClick(feature: com.google.maps.android.data.Feature?) {
             // code here
      }
})
```

That is, have ..
_GeoJsonFeature.markerOptions_
.title
.snippet
.tag

**Comment by barbeau** [comment]
@Tybion There has been a re-structuring of click handling to support multiple layers in the current master branch of the project. Could you please take a look and see if you suggestion here is still relevant?

**Comment by Tybion** [comment]
@barbeau I don't know where to look at the documentation, but I suspect that this TAG request will still be relevant.  Probably easiest to explain by showing you the current code structure, when responding to a Polyline click.

```
     override fun onPolylineClick(polyline: Polyline) {

        // LOCATION
        if (polyline.tag is LocationGPS) {
            val locn = polyline.tag as LocationGPS
            // work done here

        // TRAIL
        } else if (polyline.tag is TrailGPS) {
            val trail = polyline.tag as TrailGPS
            // work done here

        // GeoJSON LineString or MultiLineString
        } else if (polyline.tag is GeoJsonFeature) {
            val geojFeature = polyline.tag as GeoJsonFeature
            // work done here
```
As you can see, multiple object types can be represented by a line, polygon, etc. and the developer needs to have an efficient way to access the individual data object represented by the line/polygon, **at the time it is clicked**.

**Comment by barbeau** [comment]
@Tybion Right now here's what the code looks like to set up a listener on a GeoJSON feature (from `MultiLayerDemoActivity` in the demo app):

~~~
            // GeoJSON polygon
            GeoJsonLayer geoJsonPolygonLayer = new GeoJsonLayer(getMap(), R.raw.south_london_square_geojson, this, markerManager, polygonManager, polylineManager, groundOverlayManager);
            // Fill it with red
            GeoJsonPolygonStyle geoJsonPolygonStyle = new GeoJsonPolygonStyle();
            geoJsonPolygonStyle.setFillColor(Color.RED);
            for (GeoJsonFeature f : geoJsonPolygonLayer.getFeatures()) {
                f.setPolygonStyle(geoJsonPolygonStyle);
            }
            geoJsonPolygonLayer.addLayerToMap();
            geoJsonPolygonLayer.setOnFeatureClickListener(new GeoJsonLayer.GeoJsonOnFeatureClickListener() {
                @Override
                public void onFeatureClick(Feature feature) {
                    Toast.makeText(MultiLayerDemoActivity.this,
                            "GeoJSON polygon clicked: " + (GeoJsonFeature) feature.getProperty("title"),
                            Toast.LENGTH_SHORT).show();
                }

            });
~~~

So the `onFeatureClick()` callback directly gives you a `feature`, which you can then cast directly to a `GeoJsonFeature` to access attributes.

Does this solve your problem?

**Comment by Tybion** [comment]
Thanks, Sean.  Yes, that's good.

**Comment by barbeau** [comment]
Great, thanks!
