### ISSUE TITLE
how to check if marker is clustered?

### ISSUE THREAD

**Issue by MohammadFahimi** [googlemaps/android-maps-utils#596]
when user select a marker I save a reference to it. but when user zoom out and marker goes into cluster and I want to do anything to marker get NullPointerException. How can I find that the marker is in cluster or is null? or have any listener to it when it cluster?

**Comment by barbeau** [comment]
You might get a quicker response on [StackOverflow with the tag `google-maps`](https://stackoverflow.com/questions/tagged/google-maps?tab=Newest). If you post there please link and close this issue. Thanks!

**Comment by alexcodreanu** [comment]
Easiest way to avoid NPE was to check if the marker with the saved reference is not null when getting it from the `CustomRenderer`:
`if(customRenderer.getMarker(lastClickedMarker) != null) doSomething`
