### ISSUE TITLE
support for business version maps

### ISSUE THREAD

**Issue by bdeneuter** [googlemaps/android-maps-utils#61]
For our app we are moving to the business version of Google maps. This version appears to have another package name then the free version. The package com.google.android.gms.maps is in the business version com.google.android.m4b.maps. Except for the package name, the complete API seems to be identical. Is it possible to add support for this? 
See for more info: https://developers.google.com/maps/documentation/business/mobile/android/#using_the_google_maps_mobile_sdk_for_business_with_google_play_services

**Comment by tksajeesh** [comment]
We are planning to use the m4b version of the maps. Are you still not going to provide support for that. We mainly need it for the Heatmaps.
