### ISSUE TITLE
KML load images included in kmz zip file

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#619]
Currently images included in the zip/kmz file are not loaded in KMLLayer where the urls in the KML are relative paths to the image.

e.g. /sampel.png

im not sure though if the url starts with http if it also loads, but these kind of urls should also be supported.

**Comment by barbeau** [comment]
@chitgoks Thanks! Could you please provide an example KMZ for this?

**Comment by chitgoks** [comment]
i will PM back once i can get a KMZ for this. i access the google crisis site for the kmz, currently there is no natural disaster.

**Comment by jeffdgr8** [comment]
I added KMZ support in https://github.com/googlemaps/android-maps-utils/pull/625.
