### ISSUE TITLE
Update javadocs in http://googlemaps.github.io/android-maps-utils

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#643]
**Is your feature request related to a problem? Please describe.**
Documentation in http://googlemaps.github.io/android-maps-utils/ is out-of-date.

 **Describe the solution you'd like**
(1) Page should be updated.
(2) Updating this page should be a part of the release process

 **Describe alternatives you've considered**
N/A

 **Additional context**
N/A

**Comment by jpoehnelt** [comment]
also consider javadoc.io https://www.javadoc.io/doc/com.google.maps/google-maps-services/latest/index.html

**Comment by arriolac** [comment]
> also consider javadoc.io https://www.javadoc.io/doc/com.google.maps/google-maps-services/latest/index.html

Nice. Once #644 is merged, the next published release should have docs available there (which should cover part (2) of this issue).

For (1), I've updated http://googlemaps.github.io/android-maps-utils/javadoc to display the most accurate version. Once a 1.x.x is released, we can reference https://www.javadoc.io/doc/com.google.maps.android/android-maps-utils in the README instead.
