### ISSUE TITLE
Reduce Travis matrix

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#645]
**Is your feature request related to a problem? Please describe.**
Android builds are taking up quite a bit of compute time and resources on Travis which slows down jobs for other repos in our org. 

 **Describe the solution you'd like**
We should come up with another approach to testing across device configurations that doesn't block Travis. Perhaps try out https://firebase.google.com/docs/test-lab

 **Describe alternatives you've considered**
N/A

 **Additional context**
N/A

cc @jpoehnelt

**Comment by arriolac** [comment]
@barbeau can you help?

**Comment by barbeau** [comment]
Sure, I can take a look at this. 

The other option is to change instrumented tests to use Robolectric (http://robolectric.org/) instead of starting up an emulator. The last time I looked the majority of Travis execution time is spent waiting on emulator startup. If we eliminate the emulator it should reduce the execution time for each build significantly.

**Comment by arriolac** [comment]
Roboelectric would work, too.

**Comment by barbeau** [comment]
I started working on Robolectric, which has not been as straightforward as I thought it would be.

Here's what I know so far:
1. [Robolectric 4.3.1](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.3.1) is the most recent version (released Oct 2019). However, this version requires Java 9 runtime, and you have to manually configure that in Android Studio via the "Run Configuration" dialog. I'd like to avoid any manual configuration.
1. [Robolectric 4.3](https://github.com/robolectric/robolectric/releases/tag/robolectric-4.3) works with Java 8 but has [this issue](https://github.com/robolectric/robolectric/issues/5235), which requires us to add configuration to exclude a bunch of dependencies. I've been targeting this version in this branch - https://github.com/CUTR-at-USF/android-maps-utils/tree/robolectric.
