### ISSUE TITLE
After update sdk android-maps-utils the onMarkerDragStart of my code stoped work/listening

### ISSUE THREAD

**Issue by sassejlle** [googlemaps/android-maps-utils#652]
onMarkerDragStart stopped working after updating maps-utils from 0,5 to 1.0.0.
My code can no longer load the onMarkerDragStart function.

**Comment by arriolac** [comment]
@sassejlle thanks for reporting. Are you using `ClusterManager` in your code? If so, you need to set the drag listener as follows:

```java
```

**Comment by sassejlle** [comment]
Yes, I am using ClusterManager.
I set the drag listener as suggested and the problem was solved.
thank you very much!
