### ISSUE TITLE
Markers do not de-clusters when you move the map (marker enter in screen).

### ISSUE THREAD

**Issue by sassejlle** [googlemaps/android-maps-utils#654]
I use ClusterManager from maps-utils (v1.0.0) and when I move the map, the marker / cluster does not render, only if using zoom in or zoom out.
I think it should always render when there is movement on the map.

To resolve this, I load the DefaultClusterRender.java locally (@OVERIDE) and comment out the lines 364, 365, 366, 367, as shown in the image below.

After that, the markers are rendered normally.

My suggestion is that these lines be eliminated.

![image](https://user-images.githubusercontent.com/23121802/76253936-5ad0c000-622a-11ea-8711-ad4a4c7e39f2.png)

**Comment by barbeau** [comment]
@sassejlle Is there a reason you want the clusters to be re-rendered even when they don't change?

The code you commented out is intended to avoid unnecessary re-rendering if the cluster contents don't change.

**Comment by sassejlle** [comment]
Yes, there is a reason.
As shown in the video below, I show the movement of the map with the non-commented version of the code:

![20200311001727-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/23121802/76360674-380edc00-62fc-11ea-90df-6b4713cb632e.gif)

As you can see, when moving the map, the clusters appear. Markers are not rendered.
Markers are only rendered when I zoom in ou zoom out the map.

However, when I comment on the code in question, when moving the map, the markers are rendered normally. See below:

![20200311001104-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/23121802/76360022-f6316600-62fa-11ea-8ccf-87e976539eb6.gif)

I understand that I can configure for clustering only in large quantities of accumulated markers, however I have approximately 1500 markers and there was an overflow of memory and so I made an adaptation with ClusterManager to be able to keep all markers active, which I think has no relation with this suggestion.

It is possible that I am incorrectly applying ClusterManager, but this change solves my problem. If more people experience this problem, this modification may be interesting.

**Comment by barbeau** [comment]
@sassejlle Ok, thanks for the additional info. So if I'm understanding correctly the above screen captures are on a modified version of the library.

Could you please try using the official version of the library, but use the `NonHierarchicalViewBasedAlgorithm` when setting up the `ClusterManager`?

This should solve any performance issues with clustering a lot of markers.

In the demo app, this is implemented in the [`VisibleClusteringDemoActivity`](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java), which is the "Clustering: 20k only visible markers" button in the UI:

![image](https://user-images.githubusercontent.com/928045/74545909-a9cf5200-4f17-11ea-8fc8-a2068c77d661.png)

Your code will look something like this:

```java
        DisplayMetrics metrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(metrics);

        ...
        mClusterManager = new ClusterManager<>(this, getMap());
        mClusterManager.setAlgorithm(new NonHierarchicalViewBasedAlgorithm<MyItem>(
                metrics.widthPixels, metrics.heightPixels));
```

As I mentioned in https://github.com/googlemaps/android-maps-utils/issues/164#issuecomment-586350932, I modified `VisibleClusteringDemoActivity` to add 200,000 items and then tested performance on a Samsung Galaxy S8+ w/ Android 9 both with the default clustering algorithm, and then using `NonHierarchicalViewBasedAlgorithm`. There is a significant performance difference:
1. Default - When zoomed in the default algorithm quickly gets sluggish and can no longer render the re-clustering in real-time.
2. `NonHierarchicalViewBasedAlgorithm` - Continues to cluster and move markers in real-time.

**Comment by sassejlle** [comment]
The only change in the ClusterManager library code was the removal of those lines in DefautClusterRender, as shown above.

Regarding the large number of markers, I believe they are not related to the removal of these lines.

It was a long time ago that I faced this problem, but if I'm not mistaken, in my code I forced the library to cluster 100% of the markers, except those that appear in the visual field,

```
    public class OwnRendring extends DefaultClusterRenderer<MyItem> {

        OwnRendring(Context context, GoogleMap map, ClusterManager<MyItem> clusterManager) {
            super(context, map, clusterManager);
        }

        protected void onBeforeClusterItemRendered(MyItem item, MarkerOptions markerOptions) {
                // ... Bitmap generation code ...
        }

        protected boolean shouldRenderAsCluster(Cluster cluster) {
            // Renderize only if not is in bounds.
            boolean isInBounds = latLngBounds.contains(cluster.getPosition());
            return !isInBounds || (cluster.getSize() >= cfgClusterMin); 
        }
    }
```

In my case, the markers should also be de-clustered when moving the map because they can appear in the visual field, regardless of whether there is a change or not, as they were clustered when outside the visual field and after moving the map, some markers entered the visual field .

It is likely that I am not able to express myself correctly because English is not my native language and I am using the translator.

Anyway, thanks for the clarification.

**Comment by barbeau** [comment]
@sassejlle No worries! I'm going to close out this issue, but if you try `NonHierarchicalViewBasedAlgorithm` with the official v1.0.0 release of the library and the markers still aren't visible when they enter the field of view when panning the map, please let us know and we can re-open.
