### ISSUE TITLE
After update sdk android-maps-utils OnMarkerClickListener is not called

### ISSUE THREAD

**Issue by TatyanaRTB** [googlemaps/android-maps-utils#656]
I updated maps-utils from 0.5 to 1.0.0 and OnMarkerClickListener is not working anymore. 
I set is directly on GoogleMap instance and it worked good before the update. I do not use clustering features, but I draw KML layer on the map. I work with MapView in fragment and receive GoogleMap in OnMapReadyCallback normally.

Here is short example of my code:
```
fun onMapReady(
    context: Context,
    googleMap: GoogleMap?
) {
    this.googleMap = googleMap
    this.googleMap?.let { map ->
        map.setOnMapClickListener { ... }
        map.setOnMapLongClickListener { ... }
        map.setOnPolygonClickListener { … }
        map.setOnMarkerClickListener { marker ->
            marker.tag?.let { ... } ?: run { … }
            return@setOnMarkerClickListener true
        }
        map.setOnCameraIdleListener { … }
        googleMap?.uiSettings?.isMyLocationButtonEnabled = false
        googleMap?.uiSettings?.isRotateGesturesEnabled = false
        googleMap?.uiSettings?.isMapToolbarEnabled = false
    }
    setPadding(paddingLeft, paddingTop, paddingRight, paddingBottom)
    myKml?.let { drawKML(context, it) }
}
```
OnMapClickListener, OnMapLongClickListener, OnPolygonClickListener, OnCameraIdleListener still work as expected. The only problem is with OnMarkerClickListener. 

For now I have to downgrade the library.

**Comment by barbeau** [comment]
@TatyanaRTB Thanks for the report! v1.0.0 introduces some breaking changes regarding managing multiple layers on the map - and using KML and your own markers fall into that category (i.e., they each count as their own layer.

Fortunately, it should be relatively simple to modify your code to support v1.0.0. You just need to instantiate a few manager classes and use those to manage your markers, as well as pass those into your KML layer. 

The [`MultiLayerDemoActivity`](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java#L64) in the demo app has a good complete example.

You'll need to add this at the top of your class:

```java
// Shared object managers - used to support multiple layer types on the map simultaneously
MarkerManager markerManager = new MarkerManager(getMap());
GroundOverlayManager groundOverlayManager = new GroundOverlayManager(getMap());
PolygonManager polygonManager = new PolygonManager(getMap());
PolylineManager polylineManager = new PolylineManager(getMap());
```

...and then pass these into your KML layer:

```java
KmlLayer kmlLayer = new KmlLayer(getMap(), R.raw.south_london_line_kml, this, markerManager, polygonManager, polylineManager, groundOverlayManager, null);
```

...and then use the `MarkerManager` to add your markers:

```java
// Instead of adding to the map directly, use the MarkerManager
MarkerManager.Collection markerCollection = markerManager.newCollection();
markerCollection.addMarker(new MarkerOptions()
		.position(new LatLng( 51.150000, -0.150032))
		.icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE))
		.title("Normal marker"));
markerCollection.setOnMarkerClickListener(new GoogleMap.OnMarkerClickListener() {
	@Override
	public boolean onMarkerClick(Marker marker) {
		Toast.makeText(MultiLayerDemoActivity.this,
				"Marker clicked: " + marker.getTitle(),
				Toast.LENGTH_SHORT).show();
		return false;
	}
});
```

Could you please give this a try and see if it resolves your problem?

**Comment by TatyanaRTB** [comment]
@barbeau Thank you! Managers work good, I migrated to v1.0.0.
