### ISSUE TITLE
setOnInfoWindowAdapter unable to resolve after 1.0.0 from 0.6.2

### ISSUE THREAD

**Issue by nicemak** [googlemaps/android-maps-utils#661]
Unable to resolve setOnInfoWindowAdapter after upgrading to 1.0.0 from 0.6.2

`clusterManager.getMarkerCollection().setOnInfoWindowAdapter(new MyCustomClusterItemInfoView());`

**Comment by arriolac** [comment]
@nicemak `setOnInfoWindowAdapter` was renamed to `setInfoWindowAdapter`.  There were some breaking changes in 1.0.0 (see the release notes), however, it looks like this one wasn't caught in our `CHANGELOG.md`. Will update `CHANGELOG.md` and the release notes with that info. Thanks for reporting!
