### ISSUE TITLE
GeoJson: Cannot resolve in 1.0.1

### ISSUE THREAD

**Issue by DanFTRX** [googlemaps/android-maps-utils#668]
Upon upgrading to version 1.0.1 of the library, I was no longer able to compile my code.  All references to classes within the com.google.maps.android.data.geojson package fail to resolve.

When I switch my version back to 1.0.0 or earlier.  Everything works fine.

#### Steps to reproduce

  1. Include the com.google.maps.android:android-maps-utils library version 1.0.1
  2. Attempt to compile code that references GeoJson classes

#### Code example

```
package com.example;

import android.app.Activity;
import android.os.Bundle;
import com.google.maps.android.data.geojson.GeoJsonPolygon;

public class MainActivity extends Activity
{

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        GeoJsonPolygon polygon;
    }
}

```

#### Error
error: package com.google.maps.android.data.geojson does not exist
import com.google.maps.android.data.geojson.GeoJsonPolygon;

**Comment by barbeau** [comment]
Thanks for reporting this! That's strange. If I bump the demo app to `1.0.1` it also won't build (Android Studio 3.5.3 and 3.6.1), but I see a different problem:

~~~
* What went wrong:
Execution failed for task ':demo:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\android-projects\android-maps-utils\demo\src\main\res\layout\multi_profile.xml:28: AAPT: error: resource id/amu_text (aka com.google.maps.android.utils.demo:id/amu_text) not found.
         
     C:\android-projects\android-maps-utils\demo\src\main\res\layout\multi_profile.xml:28: AAPT: error: resource style/amu_Bubble.TextAppearance.Light (aka com.google.maps.android.utils.demo:style/amu_Bubble.TextAppearance.Light) not found.
~~~

**Comment by barbeau** [comment]
It's something related to the release process, as if I depend on the library directly from the demo app (`implementation project(':library')`) I don't have any issues.

Looking at https://github.com/googlemaps/android-maps-utils/commit/7bbc3c7f9fb91e65264f6968f67dda17e78abc82 more closely, it looks like this line was removed:

~~~
classifier = 'sources'
~~~

I'm guessing that might be the cause, as I'm not sure what else since the 1.0.0 release might cause this. I'll open a PR shortly for @arriolac to review.

**Comment by DanFTRX** [comment]
@barbeau Its definentely that commit.  I examined the pom's downloaded by gradle for the two versions, and 1.0.0 and below have a "\<packaging\>aar\</packaging\>" tag, whereas 1.0.1 has a "\<packaging\>pom\</packaging\>" tag.  So its definently an issue in the maven push.  Hopefully re-adding that line is enough to fix it.
