### ISSUE TITLE
New stable version (1.0.0) replaces custom marker icons when moving the map

### ISSUE THREAD

**Issue by gnuyork** [googlemaps/android-maps-utils#682]
#### Summary

The current stable version (1.0.0) replaces custom marker icons with the default ones when the user moves the map.

#### Expected behavior

The custom icons should stay.

#### Observed behavior

The custom icons are loaded fine in the beginning. When the map is moved they will be replaced with the default icons (bubbles with numbers).

#### Environment details

com.google.maps.android:android-maps-utils:1.0.0
tested with Android 7-9

#### Steps to reproduce

  1. set a custom icon using the MarkerOptions in the onBeforeClusterRendered() method (in my case different icons depending on the cluster.size() value).
  2. Test it in the emulator as described above.

**Comment by barbeau** [comment]
@gnuyork Thanks for the report!

I believe you can solve this using the steps I outlined here:
https://github.com/googlemaps/android-maps-utils/issues/655#issuecomment-607965763

Could you please give that a shot and let me know if it works?

**Comment by gnuyork** [comment]
@barbeau Thanks for this very fast reply. 

Yup, this seems to work. Thank you.

**Comment by barbeau** [comment]
Awesome, thanks!
