### ISSUE TITLE
Improve documentation in README

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#686]
**Is your feature request related to a problem? Please describe.**
1.0.0 had a couple of breaking changes and there has been a lot of confusion since its release on how to add a marker click listener or a custom info window adapter. 

 **Describe the solution you'd like**
The README should have a section and describe example usages and scenarios such as this.

 **Describe alternatives you've considered**
Another alternative is to improve the API such that `GoogleMap.setOnInfoWindowClickListener`, `GoogleMap.setOnMarkerClickListener`, `GoogleMap.setOnMarkerDragListener`, and `GoogleMap.setInfoWindowAdapter` are not override by `MarkerManager`. I need to dig into this scenario deeper to see if it's a possibility.

 **Additional context**
See issues #685, #677, #676, #661, and #656.

**Comment by barbeau** [comment]
We could also post a few StackOverflow questions and answers specifically on these topics (i.e., answer our own questions) - developers may find these before they find the README.

**Comment by barbeau** [comment]
Per more discussion, this documentation could be written as a "Migration Guide" from v0.x to v1.0.

**Comment by lmj0011** [comment]
> Another alternative is to improve the API such that GoogleMap.setOnInfoWindowClickListener

I believe this 5 year old SO question is related: https://stackoverflow.com/a/34062726/2445763
