### ISSUE TITLE
How to use this library with Xamarin.Forms

### ISSUE THREAD

**Issue by WeiLinJoe** [googlemaps/android-maps-utils#692]
I'm new in Xamarin.Forms , I used Google Map Api to play my own map...
Now I want to Read KML file and add KMLlayer  in My map by Xamarin.Forms
But I have no idea to bind this library in my Project ...

I find lots of solution about Xamarin.Android , but it cannt work...

Thanks for ur answer....

**Comment by barbeau** [comment]
@WeiLinJoe Good question! I'm not very familiar with Xamarin.Forms, but I'm guessing that the "DependencyService" may be a good place to start:
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction

Here's a tutorial I found after some Googling:
https://www.andrewhoefling.com/Blog/Post/xamarin-forms-native-api-acces-with-dependency-injection

You might get a quicker response on [StackOverflow with the tag `google-maps`](https://stackoverflow.com/questions/tagged/google-maps?tab=Newest) and `xamarin.forms`. 

If you post there please link and close this issue. Thanks!

**Comment by WeiLinJoe** [comment]
> @WeiLinJoe Good question! I'm not very familiar with Xamarin.Forms, but I'm guessing that the "DependencyService" may be a good place to start:
> https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction
> 
> Here's a tutorial I found after some Googling:
> https://www.andrewhoefling.com/Blog/Post/xamarin-forms-native-api-acces-with-dependency-injection
> 
> You might get a quicker response on [StackOverflow with the tag `google-maps`](https://stackoverflow.com/questions/tagged/google-maps?tab=Newest) and `xamarin.forms`.
> 
> If you post there please link and close this issue. Thanks!

**Comment by WeiLinJoe** [comment]
@barbeau  OK , thanks , I will try tomorrow.
wow , u find all the infomations i had never seen b4~  thx a lot...
btw , my English is bad bad , sorry :))

**Comment by WeiLinJoe** [comment]
Another question ~
So far i know how to binding JAR file into my project ..
But this libriry didnt have JAR ?
it got lots of java file ,, how can I package this Java file into one JAR ?
