### ISSUE TITLE
setMinClusterSize() not respected

### ISSUE THREAD

**Issue by joknu1** [googlemaps/android-maps-utils#696]
#### Summary
`DefaultClusterRenderer.setMinClusterSize()` is not respected since `shouldRenderAsCluster()` logic checks `greater than mMinClusterSize`

#### Expected behavior
When `mMinClusterSize = 4`, I would expect to see clusters of size 4.

#### Observed behavior
The cluster is of min size 5. 

#### Environment details

1. Sony Compact
2. Android 9
3. android-maps-utils:1.1.0

#### Code example

```
 protected boolean shouldRenderAsCluster(Cluster<T> cluster) {
        return cluster.getSize() > mMinClusterSize;
    }
```
Change to `>=`

**Comment by barbeau** [comment]
@joknu1 Thanks for flagging this! I'll push a fix shortly.
