### ISSUE TITLE
Is an own API key strictly required now? Has anything changed?

### ISSUE THREAD

**Issue by unikumi** [googlemaps/android-maps-utils#705]
Sorry, I don't have much experience in Android development, but so far, I was using an app (created just for my own, not published) based on this demo, and I was really happy to be able to do it without an API key.
Before that, if I just cloned the master branch and installed it to the phone, most of the features worked properly from the first moment, the map examples were visible and usable. But now the map is not loading. As far as I knew, Maps activities in native apps were allowed to use quite free. Has something changed on the side of Google? Is an API key required now, even if I just wanna show the map in the app? Thank you.

**Comment by barbeau** [comment]
@unikumi I'm seeing this too - looks like the Maps API key bundled with the demo isn't working anymore. I just opened a PR here to switch to a configuration that would allow you to easily use your own API key:
https://github.com/googlemaps/android-maps-utils/pull/706

You can mirror this approach in your own app as well to hide your API key and avoid it being accidentally checked in to version control.

**Comment by unikumi** [comment]
@barbeau Thank you for checking it so quickly. Now, with my own key, it's working, indeed.
