### ISSUE TITLE
Cannot build with 1.2.0

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#708]
Has anyone tried v1.2.0?

I cannot build my project now. keeps giving me this error message.

ERROR: Unable to resolve dependency for ':appt/compileClasspath': Could not resolve com.google.maps.android:android-maps-utils:1.2.0.

1.1.0 builds fine.

**Comment by barbeau** [comment]
@chitgoks Thanks for reporting this! You're right, it looks like v1.2.0 and v1.2.1 (which is the latest version listed in the README) isn't showing up in Maven Central:
https://search.maven.org/artifact/com.google.maps.android/android-maps-utils

@arriolac Would you be able to take a look at this?

**Comment by arriolac** [comment]
Will take a look

**Comment by arriolac** [comment]
The build 1.2.0 and the latest build 1.2.1 should now be on maven central. The publish workflows have been failing so I need to run `./gradlew build publish` locally. See: https://github.com/googlemaps/android-maps-utils/actions?query=workflow%3A%22Publish+build+to+Sonatype%22

I've filed the issue #709 to address this.
