### ISSUE TITLE
Pass Marker in OnClusterClickListener, OnClusterInfoWindowClickListener, OnClusterItemClickListener, and OnClusterItemInfoWindowClickListener 

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#710]
**Is your feature request related to a problem? Please describe.**
With the current API, it's difficult to infer what `Marker` a click event originated from since the `Marker` object is not provided in the clustering event listeners `OnClusterClickListener`, `OnClusterInfoWindowClickListener`, `OnClusterItemClickListener` and `OnClusterItemInfoWindowClickListener`. This could be useful say if you want to modify the marker (such as its tag) when it is clicked.

 **Describe the solution you'd like**
Modify the aforementioned event listeners so that the `Marker` is provided. Note, however, that this change does introduce a breaking change.

```java
    public interface OnClusterClickListener<T extends ClusterItem> {
        boolean onClusterClick(Cluster<T> cluster, Marker marker);
    }

    public interface OnClusterInfoWindowClickListener<T extends ClusterItem> {
        void onClusterInfoWindowClick(Cluster<T> cluster, Marker marker);
    }

    public interface OnClusterItemClickListener<T extends ClusterItem> {
        boolean onClusterItemClick(T item, Marker marker);
    }

    public interface OnClusterItemInfoWindowClickListener<T extends ClusterItem> {
        void onClusterItemInfoWindowClick(T item, Marker marker);
    }
```

 **Describe alternatives you've considered**
* Create new listeners so there is no breaking change.
* Add a new property of type `Marker` in `ClusterItem`

**Comment by DmitrSP** [comment]
please, don't close this. it's great feature

**Comment by arriolac** [comment]
Still valid
