### ISSUE TITLE
Support Maps SDK 3 beta

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#718]
What are the plans for the Maps SDK 3 beta? That beta seems to be stagnant, but we can't implement it if the utils library doesn't support it.

**Comment by arriolac** [comment]
Hi @ryust, this is on our radar and this is what pull request #608 was intended to address. @barbeau and I have been working on a Gradle copy technique that would make supporting V3 much more automated (see https://github.com/googlemaps/android-maps-ktx/pull/51). I'm hoping to get to this by next week.

**Comment by ryust** [comment]
Fantastic! I've been holding off on SDK 3 until utils was ready to go also. Keep us posted.
