### ISSUE TITLE
Cluster sporadically showing wrong number of markers

### ISSUE THREAD

**Issue by queden** [googlemaps/android-maps-utils#719]
### Summary

Have a cluster manager on a map with only 9 markers. Most of the time, it shows cluster with "9" as expected, but occasionally, it will show 10+, and this morning even got it to say 20+. I can't find a pattern as to why it's happening. Will have a streak of all 9s, but then will revert to 10 or 20 once or twice. 

#### Expected behavior

What did you expect?
![image](https://user-images.githubusercontent.com/52253367/81936133-be2af580-95bf-11ea-960d-748c5a24c016.png)

#### Observed behavior

Did not change any code between taking these two pictures, just re-ran.

![image](https://user-images.githubusercontent.com/52253367/81936163-cc791180-95bf-11ea-9e4e-b0e2070ca4a1.png)

#### Environment details

1. Nexus 5X API 29 x86 Emulator, with Library 1.2.1. 

#### Code example

Private project so can't post the code, but let me know if there is any other information needed. 

This is not super urgent, as I am probably going to add custom cluster icons anyway, but just want to make sure nothing is fundamentally wrong with my use of CM.

**Comment by arriolac** [comment]
Thanks for reporting @queden. I'm not able to repro this on the demo app. Can you share a code sample that reproduces this problem?

**Comment by kikoso** [comment]
@queden , this seems to be an old issue. Are you still able to reproduce it? Could you provide us with a code sample?
