### ISSUE TITLE
PolyUtil.distanceToLine returns wrong result

### ISSUE THREAD

**Issue by robmir44** [googlemaps/android-maps-utils#720]
### Summary
distanceToLine (from PolyUtil) returns wrong result, not the nearest point on the line will be found. 

here the test data:
**P**:  
longitude12.0978238, 
latitude: 49.3210674

**Start**:  
longitude: 12.097749 
latitude: 49.321045

**End**:
longitude: 12.097795
latitude: 49.321016

### Expected behavior
nearest distance from the point to the line (perpendicular). The distance should be ca. 5.5m
![grafik](https://user-images.githubusercontent.com/40853360/82067263-c2930380-96d0-11ea-9274-6d04d1da72c6.png)

### Observed behavior
The green point is the calculated nearest point (su method variable), green is the line. Blue is the point. The distance is 5.956537

![image](https://user-images.githubusercontent.com/40853360/81956673-e17b9200-960b-11ea-935c-ea7d085446f3.png)

### Environment details
Java 

### Code example
 PolyUtil.distanceToLine(p, start, end). I checked this variable: su (method variable)

**Comment by robmir44** [comment]
do you think the bug is fixed for the next version?

**Comment by barbeau** [comment]
@robmir44 Thanks for reporting this, I'll take a look. Additional questions:
1. What version of Android Maps Utils library did you observe this result in?
1. What is the expected return value from `PolyUtil.distanceToLine()` as distance for the input you provided?

**Comment by robmir44** [comment]
1. v1.2.1 actually see master branch
2. the distance should be ca. 5.5m - 5.6m

**Comment by robmir44** [comment]
> 
> 
> @robmir44 Thanks for reporting this, I'll take a look. Additional questions:
> 
>     1. What version of Android Maps Utils library did you observe this result in?
> 
>     2. What is the expected return value from `PolyUtil.distanceToLine()` as distance for the input you provided?

I have updated my  bug report. The reurned distance is 5.956537m, should be ca. 5.5m

**Comment by barbeau** [comment]
@robmir44 I'm getting something a little different.

Here's the code I'm using:

```java
        startLine = new LatLng(49.321045, 12.097749);
        endLine = new LatLng(49.321016,  12.097795);
        p = new LatLng(49.3210674, 12.0978238);

        distance = PolyUtil.distanceToLine(p, startLine, endLine);
        assertEquals( 5.5, distance, 1e-6);
```

The `su` variable for me (the closest point on the line) ends up being `(49.32101762603991,12.097792420764282)`, which is green in the below screenshot:

![image](https://user-images.githubusercontent.com/928045/82078110-99617b80-96ae-11ea-97ef-ab67a20cc3c2.png)

But your example shows the green dot at the other end of the line.

Could you give me a copy/paste of your code so I can match exactly what you're seeing?

**Comment by robmir44** [comment]
> ```java
> 12.0978238
> ```

I assume it's my fault :/ mea culpa. I'll check it again and then I'll let you know (tomorrow).

**Comment by robmir44** [comment]
So, i checked it again and I am confused. I have two lines green and red.
**Point coordinates** are: (lat: 49.3210674, lon: 12.0978238) 

**green line coordinates** are: start (lat: 49.321045, lon: 12.097749), end (lat: 49.321016, lon: 12.097795) 

**red line coordinates** are: start (lat: 49.321045, lon: 12.097749), end (lat: 49.321072082966566, lon: 12.097703106701374)
 
the closest point on the red line is the red point and the calculated distance is: 5.97
the closest point on the green line is the green point and the calculated distance is: 5.98

But I have measured the closest point on the green line via QGIS and the result (see screen shot) is ca. 5.6m. Secondly, the red point should be further than the green one (optically seen)? 
I have also  measured the distance from the point to the calculated green point via QGIS  and I got ca. the same result ca. 5.97m. I don't know what I do wrong? Is it QGIS line measurement wrong or the calculation? 

![grafik](https://user-images.githubusercontent.com/40853360/82113244-daac6680-9754-11ea-86bc-3946018821d2.png)

**Comment by barbeau** [comment]
@robmir44 Thanks for the clarification. I believe the distance measurement value is correct between the blue and green dots - this comes to around 5.55m. I believe the current method for finding the closest point on the line isn't working correctly in all cases in AMU - I'm still looking into it.

**Comment by barbeau** [comment]
So after looking at this, I think the main issue that's resulting in incorrect measurements is that the algorithm used to determine the distance to the line segment in `distanceToLine()` is for 2D Euclidean space - it's described in these two articles in more detail:
* "Minimum Distance between a Point and a Line" - http://paulbourke.net/geometry/pointlineplane/
* "Distance of a Point to a Ray or Segment" - http://geomalgorithms.com/a02-_lines.html

However, for accurate results we want the distance of the arc on the surface of a sphere, which approximates the WGS84 ellipsoid where latitude and longitude come from. An example algorithm for calculating this arc distance is listed here:
* "Cross-track distance" - https://www.movable-type.co.uk/scripts/latlong.html

I did a quick implementation of the cross-track distance algorithm and got the expected ~5.559m distance using the example above.

However, it's important to note that the `simplify()` method uses `distanceToLine()` internally, and to work correctly `distanceToLine()` **must** be the implementation of the distance of a point to a line **segment**, not the distance of a point to a line that extends beyond the start and end point. I believe "cross-track distance" algorithm is the latter (point to great circle path), while the current implementation is the former (point to line segment). So I need to do more testing to identify how to restrict measuring the arc distance to just to just the line segment. We may want to have two methods for distance measurements, `distanceToLineSegment()` and `distanceToLine()`, to make it clearer what the method is doing.

Feedback on the above is welcome if anyone has any other thoughts or ideas!

**Comment by barbeau** [comment]
One item in particular that would help with unit tests - if anyone is aware of any existing datsets for known values for distances from points to lines and line segments that I could use in testing to verify behavior, please let me know!

**Comment by robmir44** [comment]
what you need is the longitude correction:

so, then the code should looks like:
double lonCorrection = Math.Cos(toRadians(s1lat))
double s2s1lat = s2lat - s1lat;
 double s2s1lng = (s2lng - s1lng) * lonCorrection ;
final double u = ((s0lat - s1lat) * s2s1lat + (s0lng - s1lng) * lonCorrection  * s2s1lng)
                / (s2s1lat * s2s1lat + s2s1lng * s2s1lng)

take care, this is an approximation for small distances but works very fine. 

You can read these links: 
https://www.movable-type.co.uk/scripts/latlong.html 
https://en.wikipedia.org/wiki/Equirectangular_projection

**Comment by bigbite95110** [comment]
Mix Google Maps  come in App

**Comment by bigbite95110** [comment]
Form then  Package tour all Connected FOOD Present Place

**Comment by barbeau** [comment]
WIP PR at https://github.com/googlemaps/android-maps-utils/pull/767.
