### ISSUE TITLE
1.3.0 for maps SDK beta 3 not found

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#722]
// Alternately - Utilities for Maps SDK for Android V3 BETA
implementation 'com.google.maps.android:android-maps-utils-v3:1.3.0'

Gradle error:

ERROR: Failed to resolve: com.google.maps.android:android-maps-utils-v3:1.3.0

**Comment by barbeau** [comment]
@ryust v1.3 was just published, so it may not be live in Maven Central yet.

@arriolac Do you know if the AMU SDK v3 artifact has been pushed to Maven Central?

**Comment by ryust** [comment]
No problem, I can wait. Just wanted to be sure there wasn't another issue with it getting published.

**Comment by arriolac** [comment]
Indeed—semantic release bot announces a release before it's even published on maven. I'm seeing some build/publish issues at the moment though. Will comment here once I resolve it.

**Comment by arriolac** [comment]
Also related to #709

**Comment by arriolac** [comment]
Ok, 1.3.0 should be live now. @ryust give it a go and let us know if you encounter any issues with it!

**Comment by ryust** [comment]
Sorry, no change on my end. Still not found. And to be clear I'm talking about the beta v3 version.

**Comment by arriolac** [comment]
Yup, the V3 version of the library under the artifact name `android-maps-utils-v3` was just published to maven central. I see it in the Nexus Repo Manager but not on maven search. I know there are delays sometimes with syncing so I'd give it another try in a few.

**Comment by ryust** [comment]
It's working now... pulling it in. Thanks for all your hard work!
