### ISSUE TITLE
Missing aar file for 1.3.0 in Maven Central

### ISSUE THREAD

**Issue by jrgonzalezg** [googlemaps/android-maps-utils#725]
#### Summary

The aar for version 1.3.0 is missing on Maven: https://repo.maven.apache.org/maven2/com/google/maps/android/android-maps-utils/1.3.0/

The checksum files appear, but not the aar file itself.

On the other hand the aar file does exists for v3:
https://repo.maven.apache.org/maven2/com/google/maps/android/android-maps-utils-v3/1.3.0/

#### Expected behavior

aar should be present on Maven central for stable version too

#### Observed behavior

aar is only present for v3 variant of the library

**Comment by arriolac** [comment]
Thanks for reporting. I'm working on publishing 1.3.1 to address this.

**Comment by arriolac** [comment]
1.3.1 has been published and should have the appropriate aar files attached. Please use that version instead.
