### ISSUE TITLE
Add additional product flavor to demo app

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#729]
**Is your feature request related to a problem? Please describe.**
The current `demo` app is to demo features for the GMS distribution of the Utility library. This feature request is to add an additional product flavor to the `demo` app for the standalone V3 BETA distribution of the Utility library.

 **Describe the solution you'd like**
Define 2 product flavors: `gms` and `v3` so that the `demo` app can be easily configure to run either the GMS or the V3 BETA version of the library.

 **Describe alternatives you've considered**
N/A

 **Additional context**
N/A

**Comment by barbeau** [comment]
Still valid

**Comment by barbeau** [comment]
WIP PR at https://github.com/googlemaps/android-maps-utils/pull/811
