### ISSUE TITLE
URL in the maven artifact incorrectly points the KTX repo

### ISSUE THREAD

**Issue by krage** [googlemaps/android-maps-utils#730]
Starting at version 1.3.0 the URL associated with the `com.google.maps.android:android-maps-utils` artifact points to `https://github.com/googlemaps/android-maps-ktx` instead of `https://github.com/googlemaps/android-maps-utils`.  Can compare at:

https://search.maven.org/artifact/com.google.maps.android/android-maps-utils/1.2.1/aar
vs.
https://search.maven.org/artifact/com.google.maps.android/android-maps-utils/1.3.1/aar

**Comment by arriolac** [comment]
Thanks for reporting!
