### ISSUE TITLE
Updating items clusterItems : Clear items and re-adding doesn't always work

### ISSUE THREAD

**Issue by juamor86** [googlemaps/android-maps-utils#732]
I am having an issue with this library. Whenever I clear the items from the cluster manager and add a new set, some single pins are not redrawn. Here's what I am doing:

private void displayMarkers(List markersToShowOnMap) {
gMap.clear();
clusterManager.clearItems();
clusterManager.cluster(); //if I disable this it doesn't work either
mClusterManager.addItems(markersToShowOnMap);
mClusterManager.cluster();
}

If I call this method with the same set of markers, while zoomed in such that some clusters are displayed and some single markers are displayed, the single markers disappear! I am using the DefaultClusterRenderer. I have logged the renderer and onBeforeClusterItemRendered is not being called a second time after clearing and re-adding items. If i zoom out and back in, the missing markers re-appear.

**Comment by barbeau** [comment]
@juamor86 Thanks for reaching out! Starting with v1 of the library, you'll need to override `onClusterItemUpdated()` in addition to `onBeforeClusterItemRendered()` - the general implementation can be the same. Similarly, you should override `onClusterUpdated()` in addition to `onBeforeClusterRendered()` - the general implementation can also be the same (Note that the implementation can't be identical, because you need to operate on a `Marker` instead of `MarkerOptions`, but the code is very close.).

You can see examples in the demo app `CustomMarkerClusteringDemoActivity`: https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity.java

The reason for needing to override the new methods is that some markers are cached for performance reasons, and therefore they might be updated instead of being rendered. If you don't override these `*Updated()` methods, the default implementation of these methods will execute, which might do strange things you're not expecting.

Could you give that a try and see if it fixes the issue?

**Comment by juamor86** [comment]
I only had the method onBeforeClusterItemRenderedoverride but I now added this three method 

 @Override
    protected void onBeforeClusterItemRendered(Centres centres, MarkerOptions markerOptions) {
       markerOptions.icon(getItemIcon(centres));
    }

    @Override
    protected void onClusterItemUpdated(Centres centres, Marker marker) {
        marker.setIcon(getItemIcon(centres));
    }

    @Override
    protected void onBeforeClusterRendered(Cluster<Centres> cluster, MarkerOptions markerOptions) {
       
    }

    @Override
    protected void onClusterUpdated(Cluster<Centres> cluster, Marker marker) {
       
    }
I would like that the cluster keep the colors from before, definitely the item marker with markerOptions.icon(getItemIcon(centres)); but the cluster collection keep the same color default, what must I do it?

**Comment by juamor86** [comment]
I could do the override onBeforeClusterRendered onClusterUpdated to keep the item cluster default
but this moment the method onClusterItemUpdated is doing crash the app

this my code of my custom DefaultClusterRenderer

public class CentresMarkerRenderer extends DefaultClusterRenderer<Centres> {

    private static final int[] BUCKETS = {10, 20, 50, 100, 200, 500, 1000};
    private SparseArray<BitmapDescriptor> mIcons = new SparseArray<>();
    private ShapeDrawable mColoredCircleBackground;
    private final IconGenerator mIconGenerator;
    private final float mDensity;
    private Context context;

    public CentresMarkerRenderer(Context ctx, GoogleMap map, ClusterManager<Centres> clusterManager) {
        super(ctx, map, clusterManager);
        context = ctx;
        mDensity = context.getResources().getDisplayMetrics().density;
        mIconGenerator = new IconGenerator(context);
        mIconGenerator.setContentView(makeSquareTextView(context));
        mIconGenerator.setTextAppearance(R.style.amu_ClusterIcon_TextAppearance);
        mIconGenerator.setBackground(makeClusterBackground());
    }

    @Override
    protected void onBeforeClusterItemRendered(Centres centres, MarkerOptions markerOptions) {
        markerOptions.icon(getDescriptorForMarker(centres));
    }

    @Override
    protected void onClusterItemUpdated(Centres centres, Marker marker) {
        marker.setIcon(getDescriptorForMarker(centres));
    }

    @Override
    protected void onBeforeClusterRendered(Cluster<Centres> cluster, MarkerOptions markerOptions) {
        markerOptions.icon(getDescriptorForCluster(cluster));
    }

    @Override
    protected void onClusterUpdated(Cluster<Centres> cluster, Marker marker) {
        marker.setIcon(getDescriptorForCluster(cluster));
    }

    @Override
    protected boolean shouldRenderAsCluster(Cluster cluster) {
        return cluster.getSize() > 1; // Always render clusters.
    }

    private BitmapDescriptor getDescriptorForMarker(Centres centres) {
        return ViewUtil.getBitmapDescriptor(context, centres.getIconMarker(), ViewUtil.sizeIconMarkerDefault);
    }

    protected BitmapDescriptor getDescriptorForCluster(@NonNull Cluster<Centres> cluster) {
        int bucket = getBucket(cluster);
        BitmapDescriptor descriptor = mIcons.get(bucket);
        if (descriptor == null) {
            mColoredCircleBackground.getPaint().setColor(getColor(bucket));
            descriptor = BitmapDescriptorFactory.fromBitmap(mIconGenerator.makeIcon(getClusterText(bucket)));
            mIcons.put(bucket, descriptor);
        }
        return descriptor;
    }

    private LayerDrawable makeClusterBackground() {
        mColoredCircleBackground = new ShapeDrawable(new OvalShape());
        ShapeDrawable outline = new ShapeDrawable(new OvalShape());
        outline.getPaint().setColor(0x80ffffff); // Transparent white.
        LayerDrawable background = new LayerDrawable(new Drawable[]{outline, mColoredCircleBackground});
        int strokeWidth = (int) (mDensity * 3);
        background.setLayerInset(1, strokeWidth, strokeWidth, strokeWidth, strokeWidth);
        return background;
    }

    private SquareTextView makeSquareTextView(Context context) {
        SquareTextView squareTextView = new SquareTextView(context);
        ViewGroup.LayoutParams layoutParams = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT, ViewGroup.LayoutParams.WRAP_CONTENT);
        squareTextView.setLayoutParams(layoutParams);
        squareTextView.setId(R.id.amu_text);
        int twelveDpi = (int) (12 * mDensity);
        squareTextView.setPadding(twelveDpi, twelveDpi, twelveDpi, twelveDpi);
        return squareTextView;
    }
}

**Comment by juamor86** [comment]
the error is 
java.lang.IllegalArgumentException: Unmanaged descriptor
        at com.google.maps.api.android.lib6.common.m.d(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:0)
        at com.google.maps.api.android.lib6.impl.q.c(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:1)
        at com.google.maps.api.android.lib6.impl.cy.a(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:20)
        at com.google.android.gms.maps.model.internal.o.a(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:19)
        at ch.onTransact(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:4)
        at android.os.Binder.transact(Binder.java:675)
        at com.google.android.gms.internal.maps.zza.zzb(SourceFile:20)
        at com.google.android.gms.internal.maps.zzv.zzg(SourceFile:80)
        at com.google.android.gms.maps.model.Marker.setIcon(SourceFile:30)
        at es.juntadeandalucia.msspa.centros.ui.centres.centresMap.CentresMarkerRenderer.onClusterItemUpdated(SourceFile:54)
        at es.juntadeandalucia.msspa.centros.ui.centres.centresMap.CentresMarkerRenderer.onClusterItemUpdated(SourceFile:28)

the method for convert a svg to bitmap is this but I think this method not is the problem

public static BitmapDescriptor getBitmapDescriptor(Context context, int id, int size) {
        Drawable vectorDrawable = context.getDrawable(id);
        int h = ViewUtil.dpToPx(size);
        int w = ViewUtil.dpToPx(size);
        if(vectorDrawable == null){
            return BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_GREEN);
        }
        vectorDrawable.setBounds(0, 0, w, h);
        Bitmap bm = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bm);
        vectorDrawable.draw(canvas);
        return BitmapDescriptorFactory.fromBitmap(bm);
    }

**Comment by barbeau** [comment]
@juamor86 Hmmm, I'm not sure. Are you able to reproduce this based on the demo app code?

**Comment by barbeau** [comment]
@juamor86 Looking back at your original code:

```java
private void displayMarkers(List markersToShowOnMap) {
    gMap.clear();
    clusterManager.clearItems();
    clusterManager.cluster(); //if I disable this it doesn't work either
    mClusterManager.addItems(markersToShowOnMap);
    mClusterManager.cluster();
}
```

Please try removing the `gMap.clear()` line to let the cluster manager remove the markers, and remove the 1st cluster line too:

```java
private void displayMarkers(List markersToShowOnMap) {
    clusterManager.clearItems();
    mClusterManager.addItems(markersToShowOnMap);
    mClusterManager.cluster();
}
```

**Comment by a1573595** [comment]
I got same issue(Unmanaged descriptor) in sometime, I can't reproduce it.

**Comment by barbeau** [comment]
@a1573595 Are you calling `GoogleMap.clear()` anywhere in your app code? Or removing any clustered markers directly in your app code via the `Marker` object?

If you clear markers in your own app code, it can confuse the clustering manager, as it thinks the markers still exist on the map, and can result in this error.

**Comment by a1573595** [comment]
> @a1573595 Are you calling `GoogleMap.clear()` anywhere in your app code? Or removing any clustered markers directly in your app code via the `Marker` object?
> 
> If you clear markers in your own app code, it can confuse the clustering manager, as it thinks the markers still exist on the map, and can result in this error.

Yes, I use Clustering marker, normal marker, PolyLine and Circle on Map, I wrote a method to clear all data.

```kotlin=
    @Override
    public void clearMap() {
        mClusterManager.clearItems();
        map.clear();
    }
```

**Comment by barbeau** [comment]
@a1573595 Hmmm, that should work as long as you're clearing the items in the cluster manager first. Can you try removing the call to `map.clear()` and see if you still get the error? I know this is hard to test when you can't consistently reproduce it.

**Comment by a1573595** [comment]
> @a1573595 Hmmm, that should work as long as you're clearing the items in the cluster manager first. Can you try removing the call to `map.clear()` and see if you still get the error? I know this is hard to test when you can't consistently reproduce it.

Sorry, I got this problem on Crashlytics in other device.
I can't reproduce it.

**Comment by wangela** [comment]
Closing as stale; please reopen if you still see this behavior.

**Comment by danielstr** [comment]
I have a similar issue. I am doing what @barbeau says
```
    clusterManager.clearItems();
    clusterManager.addItems(markersToShowOnMap);
    clusterManager.cluster();
```
and also override `onClusterItemUpdated()` and the other methods.
I have noticed that my markers will update their location correctly on the map if I zoom out to cluster them and then zoom in again, then their location will be correct.

Any Idea of what can be happening? I am without ideas right now

**Comment by wangela** [comment]
Reopening based on @danielstr's comment

**Comment by mans17312** [comment]
private void initClusterManager(){

        if (mClusterManager != null) {
            mClusterManager.getMarkerCollection().clear();
            mClusterManager.clearItems();
            mClusterManager.cluster();
        }

       // init Cluster Manager here 
       
        mClusterManager = new ClusterManager<>(context, myGoogleMap);
        mClusterManager.setRenderer(new CustomMapClusterRender());
        myGoogleMap.setOnCameraIdleListener(mClusterManager);

        mClusterManager.setOnClusterClickListener(this);
        mClusterManager.setOnClusterInfoWindowClickListener(this);
        mClusterManager.setOnClusterItemClickListener(this);
        mClusterManager.setOnClusterItemInfoWindowClickListener(this);

        readItems(eventsList);

        mClusterManager.cluster();

    }

before init with new cluster manager please have a check like this and it will clear all the old markers and clusterManager items worked fine for me

**Comment by mans17312** [comment]
> I have a similar issue. I am doing what @barbeau says
> 
> ```
>     clusterManager.clearItems();
>     clusterManager.addItems(markersToShowOnMap);
>     clusterManager.cluster();
> ```
> 
> and also override `onClusterItemUpdated()` and the other methods. I have noticed that my markers will update their location correctly on the map if I zoom out to cluster them and then zoom in again, then their location will be correct.
> 
> Any Idea of what can be happening? I am without ideas right now

private void initClusterManager(){

    if (mClusterManager != null) {
        mClusterManager.getMarkerCollection().clear();
        mClusterManager.clearItems();
        mClusterManager.cluster();
    }

   // init Cluster Manager here 
   
    mClusterManager = new ClusterManager<>(context, myGoogleMap);
    mClusterManager.setRenderer(new CustomMapClusterRender());
    myGoogleMap.setOnCameraIdleListener(mClusterManager);

    mClusterManager.setOnClusterClickListener(this);
    mClusterManager.setOnClusterInfoWindowClickListener(this);
    mClusterManager.setOnClusterItemClickListener(this);
    mClusterManager.setOnClusterItemInfoWindowClickListener(this);

    readItems(eventsList);

    mClusterManager.cluster();

}
before init with new cluster manager please have a check like this and it will clear all the old markers and clusterManager items worked fine for me

**Comment by danielstr** [comment]
if I do that all my markers wil dissapear when they should be redrawn. The only solution I found is, recreate the renderer before assing the new items, like this:
```
    clusterManager.renderer =  new CustomClusteringRenderer(...)
    clusterManager.clearItems();
    clusterManager.addItems(markersToShowOnMap);
    clusterManager.cluster();
```
but this is not a viable solution

**Comment by kikoso** [comment]
Thanks for letting us know, @danielstr !

**Comment by sonic-onkaringale** [comment]
I encountered the same issue, but thanks to @danielstr , I resolved it by removing hashCode() and equals().
Mine also happened where I told Android Studio to migrate the Java code to Kotlin.
