### ISSUE TITLE
Creating GeoJsonLayer instance breaks polyline, polygon and marker click listeners

### ISSUE THREAD

**Issue by Tybion** [googlemaps/android-maps-utils#735]
This one line of code breaks all the Polygon, Polyline and Marker click listeners.
`geojsonLayer = GeoJsonLayer(mMap, objJson)`

The good news is that if you pass null for the GoogleMap parameter, the problem is fixed.
`geojsonLayer = GeoJsonLayer(null, objJson)`

When reading the documentation, I did not notice that passing null for the GoogleMap is a valid option.

**Can you PLEASE commit to supporting this as an option**.  I have map data delivered to my app in various formats and for reliability I need to just have one system (ie. PolygonOptions, PolylineOptions and Marker) for plotting and interactivity.

This GeojsonLayer is brilliant for reading geojson files, but I don't want to depend on it for plotting and interactivity, when there is already a system fully supported and documented by Google.

This is probably related to #685 

This was not a problem when I updated my app on 3rd April 2020, but was a problem on the version released on 28 April 2020.

**Comment by barbeau** [comment]
@Tybion Thanks for reaching out! Have you taking a look at the Migration Guide for v1?

https://github.com/googlemaps/android-maps-utils#migration-guide

This explains how to add markers, polyines, and polygons to the map using the `Manager` objects in the library instead of adding them to the `GoogleMap` directly. In short, GoogleMaps only supports a single click listener for events, so for clicks and other events to work aross GeoJSON, KML, etc. a single hub (the `Manager`) needs to dispatch those events. You can also see an example in the MutiLayerDemoActivity:
https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/main/java/com/google/maps/android/utils/demo/MultiLayerDemoActivity.java#L159

Please give that a shot and let me know if it works!

**Comment by Tybion** [comment]
Hello, Sean.

Thanks for being responsive and I understand your suggestion, but I need to explain my situation - and what my requirements are.

I have a production system and am supporting thousands of customers.  For any production system, you need to keep the number of dependencies to a minimum, and to choose those dependencies wisely - make sure that they are stable and supported into the future. When I had a requirement for additional functionality in my app - to read geojson files - I looked at what was available and decided that this project was the best choice for reading geojson files in Android.

To minimise the dependency on this project, I have chosen not to use the plotting and click-listener functionality.  It makes sense to continue to use the PolygonOptions, PolylineOptions and Marker objects.  This is the path of least risk.  But I absolutely want to keep using this project to read geojson files - this clearly is the strength of this project and I think the reason for its existence.

Is there any reason that you would NOT allow the use of `GeoJsonLayer(null, objJson)` into the future?  This is perfect for me, and any other developers in my situation, because it gives us this choice.

Regards,
David Collins
http://trilobite.solutions

**Comment by Tybion** [comment]
Yes, instantiating the GeoJsonLayer via `GeoJsonLayer(null, objJson)` and yes, using `getFeatures()` .  Sample code follows.

In the code below 'plots' is a list of objects that can be either a `Marker`, `Polyline` or `Polygon` as provided by the Google Maps API.  Each of these has its `tag` set to the GeojsonLayer `Feature` so that when the plotted feature is tapped by the user, the data is quickly retrievable.

```
    fun clearPlot(plots: ArrayList<Any>) {

        for (plot in plots) {
            if (plot is Marker) {
                plot.remove()
            } else if (plot is Polyline) {
                plot.remove()
            } else if (plot is Polygon) {
                plot.remove()
            }
        }
        plots.clear()
    }

    fun plot(geojsonLayer: GeoJsonLayer?, plots: ArrayList<Any>, mMap: GoogleMap?) {

        if (geojsonLayer == null) return
        if (mMap == null) return

        // First clear out any plot on the map
        clearPlot(MainActivity.geojsonPlots)

        for (feature in geojsonLayer.features) {

            val geom = feature.geometry          //.geometry

            if (geom.geometryType == "Point") {
                plotPoint(feature, (geom as GeoJsonPoint), mMap, plots)

            } else if (geom.geometryType == "MultiPoint") {
                for (point in (geom as GeoJsonMultiPoint).points) {
                    plotPoint(feature, point, mMap, plots)
                }

            } else if (geom.geometryType == "LineString") {
                plotPolyline(feature, (geom as GeoJsonLineString), mMap, plots)

            } else if (geom.geometryType == "MultiLineString") {
                for (line in (geom as GeoJsonMultiLineString).lineStrings) {
                    plotPolyline(feature, line, mMap, plots)
                }

            } else if (geom.geometryType == "Polygon") {
                plotPolygon(feature, geom, mMap, plots)

            } else if (geom.geometryType == "MultiPolygon") {
                for (poly in (geom as GeoJsonMultiPolygon).polygons) {
                    plotPolygon(feature, poly, mMap, plots)
                }

            } else {
                return
            }
        }
    }

    private fun plotPoint(feature: Feature, geom: GeoJsonPoint, mMap: GoogleMap, plots: ArrayList<Any>) {

        val markerOpt = MarkerOptions().position(geom.coordinates).anchor(0.5f, 0.5f)
                .zIndex(MainActivity.GISINDEX)  // anchor is middle of the marker
        val marker = mMap.addMarker(markerOpt)
        val bitmapDesc = BitmapDescriptorFactory.fromResource(R.drawable.mymarker)
        marker.setIcon(bitmapDesc)

        marker.tag=feature
        plots.add(marker)
    }

    private fun plotPolyline(feature: Feature, geom: GeoJsonLineString, mMap: GoogleMap, plots: ArrayList<Any>) {

        val lineOpt = PolylineOptions().addAll(geom.coordinates)
                .color(Color.RED).zIndex(MainActivity.GISINDEX).clickable(true)
        val polyline = mMap.addPolyline(lineOpt)
        polyline.tag=feature
        plots.add(polyline)
    }

    private fun plotPolygon(feature: Feature, geom: Geometry<Any>, mMap: GoogleMap, plots: ArrayList<Any>) {

        val polygonOpt = PolygonOptions().addAll((geom as GeoJsonPolygon).coordinates[0])
                .strokeColor(Color.RED).zIndex(MainActivity.GISINDEX).clickable(true)
                .fillColor(Color.argb(64, 255,0,0))        // semi-transparent

        // First coordinate list is polygon outline
        val count = geom.coordinates.count()        // (geom as GeoJsonPolygon).coordinates.count()
        // Subsequent lists are holes
        for (i in 1..count-1) {
            polygonOpt.addHole(geom.coordinates[i])         // geom as GeoJsonPolygon
        }

        val polygon = mMap.addPolygon(polygonOpt)
        polygon.tag=feature
        plots.add(polygon)
    }

```

**Comment by hangduykhiem** [comment]
We encountered the same bug using the latest `2.0.3` build. The moment we create an instance of `GeoJsonLayer`, all clickListener stop working. The default clickListener behavior - move camera to the marker - happened instead. 

We did follow the migration guide, created `MarkerManager.Collection` for every type of marker and assign their specific clickListener / infoWindows.

Even when apply a `setOnFeatureClickListener` on the GeoJsonLayer instance didn't result in any event when clicking the marker, so it's a mystery where those events ended up.

**Comment by hangduykhiem** [comment]
Upon even closer inspection of the source code, we managed to find out that the `MarkerManager` instance that we created must be pass into the GeoJsonLayer constructor for it to work.

The only place where this is mentioned in the project is in the MultiLayerDemo, which is not visible to many users of the library. Might we suggest adding this to the documentation somewhere, maybe in the Migration guide?

**Comment by barbeau** [comment]
@hangduykhiem Yes, I agree - I'll update the README to be more obvious.

**Comment by barbeau** [comment]
Still valid for docs clarification (see https://github.com/googlemaps/android-maps-utils/issues/735#issuecomment-656092945).

@Tybion The `GeoJsonParser` is now fully public (see https://github.com/googlemaps/android-maps-utils/pull/797) so the latest release of the library should allow you to use that to `getFeatures()` instead of relying on the `GeoJsonLayer`.

**Comment by Tybion** [comment]
@barbeau Thanks for that info.

**Comment by hiasel** [comment]
Still having this issue with version `2.2.3`. Adding a GeoJson layer with `layer.addToMap()` breaks any attached marker click listeners.
As a workaround I am using the solution @Tybion posted earlier (https://github.com/googlemaps/android-maps-utils/issues/735#issuecomment-642345707).

Am I correct that this only works if I would migrate my code to use `MarkerManager`?
