### ISSUE TITLE
Google maps SDK v3  dead or in silent development?

### ISSUE THREAD

**Issue by kirvis250** [googlemaps/android-maps-utils#736]
Main question is: 
**Should we wait till v3 get out of beta or invest in searching for different mapping solution?**

There is some annoying bugs with google maps SDK v2 which won't be fixed, because in v3 they do not exist (egz: flickering fill when changing polygon point's locations). 

v3 BETA Has serious issues with loading performance. Loading even moderate amount of polygons to the map takes way longer than v2. It takes significantly longer to load even compared with MapBox. 

There were no developments with v3 for over the year now. And i would just assume that it's dead. But you are still working on utils, which wouldn't make much sense if Google maps SDK for android is dead.

**Comment by arriolac** [comment]
Hi @kirvis250, thanks for asking! Yes, V3 BETA is in silent development (I guess no longer silent as I write this message). It's been a long time in beta but definitely stay tuned for improvements.

Your feedback is very valuable and I suggest writing a note through the "Send Feedback" CTA on [this page](https://developers.google.com/maps/documentation/android-sdk/v3-client-migration). This way, it's visible to our eng and product teams as they work on continued improvements to the Map SDK.

**Comment by kirvis250** [comment]
@arriolac Thank you for the answer. I now can be a bit more relaxed about that. 

Will there be some way to reach objects displayed in map without having reference them in app code?

I mean that if you do `addPolygon` to map there should be `getPolygons` as well. 
It's just an old inconvenience that i no longer care much about, but it still would be an improvement.  

If you don't know that or can't tell it's okay.  It's just my curiosity taking over. :smile:

**Comment by dkati** [comment]
i will bump this "issue" since i am really interested in the stable version of this lib. 

commits are rare at this repo (like 1-2 per month) and even more rare are the actually commits excluding some README edits etc

i love utils lib.i hope it will be updated soon. 

PS.
check out my PR
