### ISSUE TITLE
The clustering of multiple custom markers lasts several seconds

### ISSUE THREAD

**Issue by HermineSan** [googlemaps/android-maps-utils#744]
Hello.

#### Summary

The clustering lasts several seconds, when there are multiple custom markers (for example 4500)

#### Steps to reproduce
 
1 . Add multiple markers to CustomMarkerClusteringDemoActivity (e.g. 4500)
2 . Zoom in so the items are fully reclustered.
3 . Zoom out to initial zoom level

#### Expected behaviour
 
Clustering should be done smoothly

#### Observed behaviour

Clustering lasts several seconds (see the attached screencast).

#### Environment details

1. Device model : Google Pixel 2 
2. Android version :  10
3. Library version : 1.3.3

[clustering_multiple_markers.mp4.zip](https://github.com/googlemaps/android-maps-utils/files/4738140/clustering_multiple_markers.mp4.zip)

![clustering_custom_markers](https://user-images.githubusercontent.com/47554867/83916932-17cdac80-a787-11ea-872a-3b8e7fccf506.png)

Thanks

**Comment by barbeau** [comment]
@HermineSan Thanks for reaching out! Have you tried using the `NonHierarchicalViewBasedAlgorithm` along with custom clusters?

For example:

```java
        DisplayMetrics metrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(metrics);

        ...
        mClusterManager = new ClusterManager<>(this, getMap());
        mClusterManager.setAlgorithm(new NonHierarchicalViewBasedAlgorithm<MyItem>(
                metrics.widthPixels, metrics.heightPixels));
```

The normal clustering algorithm can be slow with a lot of markers, so the above algorithm only clusters the markers in-view, which should help performance.

More info at https://github.com/googlemaps/android-maps-utils/issues/164#issuecomment-586350932.

**Comment by HermineSan** [comment]
Hello. 

Thank you so much for your quick response.

I'm using that algorithm in my application, will check what else can cause the wrong behaviour.

**Comment by dkati** [comment]
any updates here? did NonHierarchical algorithm helped you?

**Comment by HermineSan** [comment]
Yes, Thank you for reaching out, it's working pretty good now!!

**Comment by barbeau** [comment]
Glad it's working! I'll close out the issue, but please feel free to re-open or comment with more info.

**Comment by dkati** [comment]
it still lags on me, even with NonHierarchicalViewBasedAlgorithm.

there is no problem on v2.

**Comment by barbeau** [comment]
@dkati Sounds like this is an issue with the Maps SDK v3 beta then? If that is the case could you report the issue on the Maps SDK v3 beta issue tracker? https://issuetracker.google.com/issues/new?component=541018&template=1201436

**Comment by dkati** [comment]
yea. i reported it. although v3 maps teams doesnt seem to be really active.
