### ISSUE TITLE
Various animation effects for GeoJsonLayers

### ISSUE THREAD

**Issue by Erlend2** [googlemaps/android-maps-utils#748]
**Describe the solution you'd like**
Hi, would it be doable and reasonable to add animation effects to GeoJsonLayers? For instance, ripple animation like the RippleDrawable for views when pressing a layer, reveal polygons in a linear sequence when showing/hiding a layer, animate fill color changes, even a standard fade in/out etc.

 **Describe alternatives you've considered**
As of this moment, I don't know about any ways to achieve it with GeoJson files that uses multipolygons. If there are ways to do it, though, I'd very much like to hear about it!

**Comment by barbeau** [comment]
Interesting ideas! Some of the concepts that build on top of existing Maps APIs feature could probably work - for example, revealing polygons in sequence, fade in/out, and animating colors changes. Clustering in this library implements animations as part of the clustering effects. I don't think ripple effects would be easy to accomplish.

**Comment by Erlend2** [comment]
@barbeau Thanks, I'll look into Clustering then.

Would it be possible to "convert" a GeoJsonLayer to a View object, or at least add some View functionality to it? Besides from Ripple animation, it could also be useful for me to have an OnDragListener to a GeoJsonLayer, but I suppose that feature would be too specialized / unique for most users.

If nothing else, I could explore the properties and capabilities of GeoJsonLayers if necessary.

**Comment by barbeau** [comment]
>Is it possible to "convert" a GeoJsonLayer to a View object, or at least add some View functionality to it?

Off the top of my head, I don't think the Maps API provides enough information to allow you to anchor a View geographically to the map (or more precisely, hover a View over the MapView while keeping it geographically aligned). [GroundOverlay](https://developers.google.com/android/reference/com/google/android/gms/maps/model/GroundOverlay) is meant to anchor images to the map.

I'd welcome thoughts from anyone else on how to accomplish this.
