### ISSUE TITLE
Heatmap by average of values instead of point density

### ISSUE THREAD

**Issue by jda-tid** [googlemaps/android-maps-utils#749]
Currently, heatmaps are created by using the point density, which is useful in most scenarios. However, it can't be used when we can't add the values of each point, such as elevation, average precipitations or temperature.

As we can't add temperature we would need to build the heatmap using an interpolation between the data we have, while it is not affected by two close points.

Example:

https://mgimond.github.io/Spatial/spatial-interpolation.html

Source:

![image](https://user-images.githubusercontent.com/36664452/84363267-c716e300-abce-11ea-8a80-5a04950e24e6.png)

Possible result:

![image](https://user-images.githubusercontent.com/36664452/84363285-d138e180-abce-11ea-8ffb-934883c67c74.png)

**Comment by arriolac** [comment]
This is a good idea 👍

**Comment by arriolac** [comment]
You should be able to use the `HeatmapTileProvider.Builder#weightedData` method for this as well. Would that fit your use-case?

**Comment by jda-tid** [comment]
Can you consider again this feature ?
