### ISSUE TITLE
Add support for setOnInfoWindowLongClickListener()

### ISSUE THREAD

**Issue by ryust** [googlemaps/android-maps-utils#750]
There is no setOnInfoWindowLongClickListener in the new utils.

**Comment by barbeau** [comment]
@ryust Thanks for pointing this out! Was there a particular part of the library you were looking for `setOnInfoWindowLongClickListener()` support in?

**Comment by ryust** [comment]
Prior to the new utils release I used both setOnInfoWindowClickListener and setOnInfoWindowLongClick listeners, but after the update the long click one no longer works. I thought there should be one similar to how we now use setOnInfoWindowClick.

**Comment by barbeau** [comment]
@ryust Thanks for the feedback! I've opened a pull request implementing long clicks at https://github.com/googlemaps/android-maps-utils/pull/752.

**Comment by barbeau** [comment]
@ryust The long click listener should now be accessible in v2.0.0:

`implementation 'com.google.maps.android:android-maps-utils:2.0.0'`

For example:

```java
        mClusterManager.getMarkerCollection().setOnInfoWindowLongClickListener(marker ->
                Toast.makeText(ClusteringDemoActivity.this,
                        "Info window long pressed.",
                        Toast.LENGTH_SHORT).show());
```
