### ISSUE TITLE
Add support for Kotlin in the library

### ISSUE THREAD

**Issue by arriolac** [googlemaps/android-maps-utils#755]
**Is your feature request related to a problem? Please describe.**
This feature request is for the Maps SDK for Android Utility Library to support Kotlin in addition to Java. Kotlin has several modern language features (lambdas, nullability, coroutines, etc.) that make developing with it pleasing. Since increasingly more developers are using Kotlin, this is also a good way to continue catch a wider net of developers who may want to contribute to the library.

 **Describe the solution you'd like**
Add the following to the top-level `build.gradle` file:

```
// Project build.gradle file.
buildscript {
    ext.kotlin_version = '1.3.30'
    ...
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```

...and to each module:
```
// Inside each module using kotlin
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-android'

...

dependencies {
   implementation "androidx.core:core-ktx:1.0.1"
   implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

 **Describe alternatives you've considered**
N/A

 **Additional context**
Before considering integrating this, it would be good to assess the impact on the size of the `.aar` library by adding Kotlin support.

**Comment by arriolac** [comment]
Given that there's significant Kotlin adoption across Android apps (see [State of Kotlin on Android](https://www.youtube.com/watch?v=etLUpHvhNZw) talk), I think it's worth revisiting this issue.

Thought of this as I was looking into adding some more extensions to the `maps-utils-ktx` package, however, if this issue gets integrated the KTX related changes should be integrated in this library. An implication of this is that `maps-utils-ktx` is no longer necessary to integrate for Kotlin developers.

Any thoughts @barbeau ?

**Comment by barbeau** [comment]
@arriolac Just to clarify, is this issue proposing maintaining Java and Kotlin versions of the library, or gradually migrating the Java library to Kotlin (or something else?)?

The former seems daunting in terms of maintenance especially if the Java version is supported indefinitely into the future.

The latter seems like a good approach given the overall state of Kotlin in Android, although off the top of my head it's not clear to me if there would be any breaking changes to existing Java apps if they referenced this library after it was migrated to Kotlin (versus referencing the current pure Java version). If there are breaking changes in this process for existing Java apps, maybe a good long-term roadmap is a migration to Kotlin while implementing a Java facade for backwards API compatibility?

I could certainly see many components in this library benefiting from Kotlin features - for example, the multi-threading in clustering could certainly benefit from coroutines.

>Before considering integrating this, it would be good to assess the impact on the size of the .aar library by adding Kotlin support.

☝️ This is still something to think about too - I haven't looked at the relative size of Kotlin vs Java libraries myself.

**Comment by arriolac** [comment]
> @arriolac Just to clarify, is this issue proposing maintaining Java and Kotlin versions of the library, or gradually migrating the Java library to Kotlin (or something else?)?

For this issue, I'm proposing something that is much smaller in scope—that the Kotlin standard library be added as a dependency to enable Kotlin development. Gradual migration of the code to Kotlin can be done, but it's not necessarily in scope. But, if any code was migrated to use Kotlin instead (for whatever reason), the author/reviewer needs to make sure that the API remains the same as to not break any existing integrations. The primary motivation of doing this is to enable new development to use Kotlin and for the migration of KTX functions to exist within this library.

As far as the impact on the size of the .aar library, it is about 20-70KB assuming the app is minified with Proguard, and more importantly, if the app does not yet use Kotlin. However, app already contains some Kotlin code, the .apk will already have the necessary Kotlin classes and so the app will not have an effective app size increase based on this change.

**Comment by barbeau** [comment]
>For this issue, I'm proposing something that is much smaller in scope—that the Kotlin standard library be added as a dependency to enable Kotlin development.

Makes sense to me, especially given the level of Kotlin adoption as those apps wouldn't see any size difference. And it would be nice to allow new development to leverage Kotlin here.
