### ISSUE TITLE
Colouring each polygon individually using geojson in android

### ISSUE THREAD

**Issue by mallikarjuna0308** [googlemaps/android-maps-utils#762]
Hi there, I have used geo json to draw polygons on google maps. Now I am unable to colour each polygon separately, when I am trying to do so, all the polygons are taking the same colour. Could anyone help me to sort out this issue. Below is the code I have written to colour each polygon.
We have parking slot drawn on google maps, based on their status(vacant(va), occupied(oc)), I need to show colour but it is taking the last colour in the loop and filling all the polygons with that colour.

for (int i = 0; i < matchedSlots.size(); i++) {
    for (Map.Entry k : machedslotMap.entrySet()) {
        if (matchedSlots.get(i).equals(k.getKey())) {
            Log.i("TAG", "DrawSlotSuccess: " + k.getValue());
            if (k.getValue().equals(va)) {
                geo.getPolygonStyle().setFillColor(ContextCompat.getColor(this, R.color.btn_green));
                break;
            } else if (k.getValue().equals(oc)) {
                geo.getPolygonStyle().setFillColor(ContextCompat.getColor(this, R.color.red));
                break;
            } 
        }
    }

**Comment by barbeau** [comment]
@mallikarjuna0308 I believe the same default style gets applied to each of the polygons if they don't have properties in the GeoJSON file, which means that if you change the color for that style it will change the color for all polygons.

You could just create a new `GeoJsonPolygonStyle` for each color, and then assign them to the `geo` objects.

Like:

```java
GeoJsonPolygonStyle vacant = new GeoJsonPolygonStyle();
vacant.setFillColor((ContextCompat.getColor(this, R.color.btn_green)));

GeoJsonPolygonStyle occupied = new GeoJsonPolygonStyle();
occupied.setFillColor((ContextCompat.getColor(this, R.color.red)));

for (int i = 0; i < matchedSlots.size(); i++) {
    for (Map.Entry k : machedslotMap.entrySet()) {
        if (matchedSlots.get(i).equals(k.getKey())) {
            Log.i("TAG", "DrawSlotSuccess: " + k.getValue());
            if (k.getValue().equals(va)) {
                geo.setPolygonStyle(vacant);
                break;
            } else if (k.getValue().equals(oc)) {
                geo.setPolygonStyle(occupied);
                break;
            }
        }
    }
}
```

Could you please give that a try and see if it works?

**Comment by mallikarjuna0308** [comment]
@barbeau  Thank you for your reply. It's working fine.
