### ISSUE TITLE
Object order in MapObjectManager.Collection is random

### ISSUE THREAD

**Issue by solcott** [googlemaps/android-maps-utils#772]
#### Summary

The order in which objects are stored in MapObjectManager.Collection and subclasses is random.  It is hard to compare the data stored here with other data sources for marker, polygon, etc.

#### Expected behavior

Storing data in a **LinkedHashSet** instead of a **HashSet** would keep the stored objects in the same order they were inserted

#### Observed Behavior

I have to create my own MapObjectManager, MarkerManager, etc to implement dragging Markers that also update a corresponding polygon.

#### Environment details

1. Device make and model, or emulator details - _Default Android 11 Emulator, Pixel 3, Samsung Tab 8_
2. Android version - _Android 8-11 at least, haven't tried other versions_
3. Library version and other environment information - _2.0.3 and previous versions back to 1.5_

**Comment by jeffdgr8** [comment]
Fixed in #972
