### ISSUE TITLE
KmlLayer containers are only exposed after calling addLayerToMap()

### ISSUE THREAD

**Issue by rrforte** [googlemaps/android-maps-utils#773]
Calling `KmlLayer::getContainers()` returns `null` when calling it prior to adding the layer to the map by calling `KmlLayer::addLayerToMap()`. This makes it impossible to retrieve containers (and nested data) without adding the layer to the map first, and also causes `KmlLayer::hasContainers()` to fail with a `NullPointerException`.

The cause is that `KmlRenderer::mContainers` [is only set during addLayerToMap](https://github.com/googlemaps/android-maps-utils/blob/4fb8c89d24a7a627e414f0b84eb366b40830c59e/library/src/main/java/com/google/maps/android/data/kml/KmlRenderer.java#L126) (and retains its initial `null` value until that point).

A current workaround seems to call `addLayerToMap()` followed by `removeLayerFromMap()` though this is far from ideal.

**Comment by ssandon** [comment]
Yes this is annoying if you want to overide Kml default style for exemple.

**Comment by dkati** [comment]
any solution here?
i want to remove kml's polygons' border/width size

**Comment by ssandon** [comment]
has said above, you have to add the layer to the map before working with Containers or Placemarks.

however, not sure you will be able to change all properties.

**Comment by dkati** [comment]
check out my pull request. https://github.com/googlemaps/android-maps-utils/pull/825

i cant find a way to do it programmatically
