### ISSUE TITLE
Add utility for animating marker movement

### ISSUE THREAD

**Issue by barbeau** [googlemaps/android-maps-utils#777]
**Is your feature request related to a problem? Please describe.**
Right now the clustering algorithm animates markers moving into and out of clusters, but a general utility to animate marker movements on the map isn't exposed as an API in this library.

Animating marker movement is useful beyond just clustering - for example, I wanted to animate the movement of a vehicle marker rather than have it jump from one position to another.

Here's the existing clustering implementation of marker animations in this library:
https://github.com/googlemaps/android-maps-utils/blob/db41dfa8d03f458edf2cccc4824f30713a232c54/library/src/main/java/com/google/maps/android/clustering/view/DefaultClusterRenderer.java#L1094

 **Describe the solution you'd like**
A few years back I implemented a general-use marker animation utility for an app I maintain, partially based on code from this project and https://gist.github.com/broady/6314689. The implementation is here:
https://github.com/OneBusAway/onebusaway-android/blob/8eeda8586a394d293b3ae8bb99ef5c6df7a93176/onebusaway-android/src/google/java/org/onebusaway/android/map/googlemapsv2/AnimationUtil.java

I'd like to contribute the utility to this project, and potentially merge it with the implementation used in clustering so the code is shared where it makes sense.

 **Describe alternatives you've considered**
Do nothing - leave the clustering marker animation implementation private

**Comment by kikoso** [comment]
Hi @barbeau,

Would it make sense to add the `AnimationUtil` class you developed before as a standalone class? I can add it on a PR for you with some tests to review.

**Comment by barbeau** [comment]
@kikoso yes, thanks, I think that would be great!

**Comment by kikoso** [comment]
I will work a bit on samples and test on [this PR](https://github.com/googlemaps/android-maps-utils/pull/1151). Thanks @barbeau

**Comment by wangela** [comment]
There is a parallel feature request with 13 +1s in the public issue tracker for Maps SDK for Android. https://issuetracker.google.com/issues/35829563

**Comment by wangela** [comment]
Thank you @barbeau for suggesting this feature and @kikoso for implementing it!
