### ISSUE TITLE
Animated GIF support in Ground Overlay

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#783]
Very important feature.

**Comment by barbeau** [comment]
@chitgoks That would be an interesting feature! That needs to be supported directly by the Android Maps SDK, though, and not this project (which depends on the Android Maps SDK). Could you please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker) and file a feature request there? Thanks!

**Comment by chitgoks** [comment]
for a moment i thought ground overlay is part of this lib. 😁 my bad

**Comment by barbeau** [comment]
@chitgoks No worries!
