### ISSUE TITLE
SymbolPath feature like in Google Maps Javascript API

### ISSUE THREAD

**Issue by chitgoks** [googlemaps/android-maps-utils#784]
Hi. i figure i try to open up a feature request here since android map sdk never had this feature like in google maps javascript api symbolpath

same use case as in the sample. draw circles based on earthquake magnitude

Please close if you feel this should still be forwarded to android maps sdk.

**Comment by chitgoks** [comment]
urgent

**Comment by chitgoks** [comment]
valid

**Comment by chitgoks** [comment]
valid

**Comment by chitgoks** [comment]
urgent!

**Comment by chitgoks** [comment]
urgent

**Comment by kikoso** [comment]
Hi @chitgoks . Feel free to open an issue on the Google Maps SDK tracker:

https://issuetracker.google.com/issues?q=status:open%20componentid:188851&s=created_time:desc
