### ISSUE TITLE
Make GeoJsonParser constructor public - allow FeatureCollection parsing

### ISSUE THREAD

**Issue by s8mathur** [googlemaps/android-maps-utils#785]
**Problem**
Unable to use `GeoJSONParser` to parse GeoJSON FeatureCollection

 **Solution**
The package private constructor of `GeoJSONParser` as seen below should be marked as public.
```java
    /**
     * Creates a new GeoJsonParser
     *
     * @param geoJsonFile GeoJSON file to parse
     */
    /* package */ GeoJsonParser(JSONObject geoJsonFile) {
        mGeoJsonFile = geoJsonFile;
        mGeoJsonFeatures = new ArrayList<>();
        mBoundingBox = null;
        parseGeoJson();
    }
```
 
**Alternatives considered**
Made an attempt to use `GeoJsonParser.parseGeometry()` but it ignores FeatureCollection geojsons and only seems to like pure geometry objects. 

 **Additional context**
* Previously requested here, but somehow missed (?): https://github.com/googlemaps/android-maps-utils/pull/492
* Please ensure GoogleMap (a UI thread-loving , non-serializable object) isn't required for data parsing classes such as Parsers.

**Comment by barbeau** [comment]
@s8mathur Thanks for opening this! I'll take a look.

**Comment by barbeau** [comment]
PR open at https://github.com/googlemaps/android-maps-utils/pull/797.
