### ISSUE TITLE
Exception building library

### ISSUE THREAD

**Issue by mdicosimo** [googlemaps/android-maps-utils#794]
Hello there,
I'm trying to build a "library" or "library-v3" through Gradle Task "build", but script fails with the following message:

```
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':library-v3'.
> groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'executionData' for task ':library-v3:jacocoTestDebugUnitTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.
```

Is there a way to overcome the problem?
I'm using Android Studio 4.0.2.
Thank you.
Max

**Comment by mdicosimo** [comment]
Solution here:

https://proandroiddev.com/how-i-resolved-jacoco-plugin-error-after-upgrading-gradle-to-6-1-1-d85c0086d66a

**Comment by arriolac** [comment]
I'm able to see `library` and `library-v3` build on `master`. The issue you ran into is most likely related to using the Android Gradle Plugin 4.x.x which both libraries are not yet upgraded to. When we do upgrade, the fix as you pointed out is to use the fork of `jacoco-android-gradle-plugin`.

**Comment by barbeau** [comment]
PR open at https://github.com/googlemaps/android-maps-utils/pull/799
