### ISSUE TITLE
read_only error

### ISSUE THREAD

**Issue by gurpreet78371** [googlemaps/android-maps-utils#798]
A problem occurred configuring project ':library'.
> groovy.lang.GroovyRuntimeException: Cannot set the value of read-only property 'executionData' for task ':library:jacocoTestDebugUnitTestReport' of type org.gradle.testing.jacoco.tasks.JacocoReport.

I have added the API_KEY, and created secure.properties file and added that line. But still it's giving this error.

**Comment by barbeau** [comment]
@gurpreet78371 Thanks for opening the issue! It looks like this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/794, so I'm going to close this issue. Could you please take a look at https://github.com/googlemaps/android-maps-utils/issues/794 and we can continue the discussion here?
