### ISSUE TITLE
CustomMarkerClusteringDemoActivity Reference Fails at Runtime

### ISSUE THREAD

**Issue by pfg23** [googlemaps/android-maps-utils#80]
The demo app fails at _runtime_ in MainActivity.onCreate on the addDemo line:

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);

    mListView = (ViewGroup) findViewById(R.id.list);

    addDemo("Clustering", ClusteringDemoActivity.class);
    addDemo("Clustering: Custom Look", CustomMarkerClusteringDemoActivity.class);    // <<--- FAILS HERE
    addDemo("Clustering: 2K markers", BigClusteringDemoActivity.class);
    // ...
```

With the following error...

04-21 10:49:52.047: I/System.out(16798): waiting for debugger to settle...
04-21 10:49:52.248: I/System.out(16798): debugger has settled (1334)
04-21 10:49:52.268: I/dalvikvm(16798): Failed resolving Lcom/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity; interface 2696 'Lcom/google/maps/android/clustering/ClusterManager$OnClusterClickListener;'
04-21 10:49:52.280: W/dalvikvm(16798): Link of class 'Lcom/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity;' failed
04-21 10:49:52.281: E/dalvikvm(16798): Could not find class 'com.google.maps.android.utils.demo.CustomMarkerClusteringDemoActivity', referenced from method com.google.maps.android.utils.demo.MainActivity.onCreate
04-21 10:49:52.283: W/dalvikvm(16798): VFY: unable to resolve const-class 2715 (Lcom/google/maps/android/utils/demo/CustomMarkerClusteringDemoActivity;) in Lcom/google/maps/android/utils/demo/MainActivity;
04-21 10:49:52.284: D/dalvikvm(16798): VFY: replacing opcode 0x1c at 0x001d
04-21 10:49:52.419: D/AndroidRuntime(16798): Shutting down VM
04-21 10:49:52.419: W/dalvikvm(16798): threadid=1: thread exiting with uncaught exception (group=0x4197dd40)
04-21 10:49:52.431: E/AndroidRuntime(16798): FATAL EXCEPTION: main
04-21 10:49:52.431: E/AndroidRuntime(16798): Process: com.google.maps.android.utils.demo, PID: 16798
04-21 10:49:52.431: E/AndroidRuntime(16798): java.lang.NoClassDefFoundError: com.google.maps.android.utils.demo.CustomMarkerClusteringDemoActivity
04-21 10:49:52.431: E/AndroidRuntime(16798):    at com.google.maps.android.utils.demo.MainActivity.onCreate(MainActivity.java:21)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.Activity.performCreate(Activity.java:5248)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2173)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2269)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.ActivityThread.access$800(ActivityThread.java:139)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.os.Handler.dispatchMessage(Handler.java:102)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.os.Looper.loop(Looper.java:136)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at android.app.ActivityThread.main(ActivityThread.java:5102)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at java.lang.reflect.Method.invokeNative(Native Method)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at java.lang.reflect.Method.invoke(Method.java:515)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
04-21 10:49:52.431: E/AndroidRuntime(16798):    at dalvik.system.NativeStart.main(Native Method)

**Comment by zefron345** [comment]
I have the same issue. Of course Library is imported to the project and they are all copied to the Workspace. This is pathetic. Just awful documentation.
