### ISSUE TITLE
2.1.0 release was not correctly published

### ISSUE THREAD

**Issue by jrgonzalezg** [googlemaps/android-maps-utils#801]
#### Summary

The 2.1.0 release publication process seems to have failed so it is not available in Maven Central. Could you republish?

#### Expected behavior

2.1.0 should be available on Maven Central for the dependency resolution to work.

#### Observed behavior

2.1.0 is not found when added as a dependency since publication seem to have failed.

**Comment by arriolac** [comment]
Thanks for filing. Looking into this right now.

**Comment by arriolac** [comment]
The 2.1.0 artifact should now be published. @jrgonzalezg can you confirm that you're able to pull in this version? If so, please feel free to close this issue.

**Comment by jrgonzalezg** [comment]
It found it now, although I'm not sure where it is being obtained from. It doesn't show up at https://search.maven.org/artifact/com.google.maps.android/android-maps-utils yet. Maybe it is there but not yet visible on the site?. Closing anyway since builds seem to go through.

**Comment by arriolac** [comment]
I've noticed that it takes some time to propagate and be searchable on search.maven.org. The artifact is here: https://search.maven.org/artifact/com.google.maps.android/android-maps-utils/2.1.0/aar
