### ISSUE TITLE
 Standard API: map lagging while moving and a dialog pops over it

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-maps-utils#803]
Tested on:
Android 8  (snapdragon 8xx - 8 ram)
Android 10  (snapdragon 8xx - 8 ram)
Android 5.0 on samsung device (jfltexx - S4 )

#### Tested on
  1. googlemaps/android-samples demo
  2. googlemaps/android-maps-utils demo

Using pure java (no kotlin at all)

**Fun fact: Does NOT happening on Google Maps app!**

#### Steps to reproduce

  1. create a map
  2. add a fab (or something) and on it's click listener zoom to your location
  3. run the app and zoom fully out (see the earth)
  4. press the fab 
  5. While camera animation is going, pull your QuickSettings panel OR on fab's listener also create an alert dialog
  6. see the background map is laggy

or , if you use a demo from googlemaps/android-samples demo or googlemaps/android-maps-utils you can reproduce this 
by quickly swipe-to-move-camera and pull QS panel

By my "research" it happens on any dialog (QS panel, alert dialog, fragmentdialog, progress dialog, bottom dialog)
but it doesnt happens on fragments

Generally, poping any dialog over maps, also spams: 
E/SchedPolicy: set_timerslack_ns write failed: Operation not permitted
on app's log

**Comment by barbeau** [comment]
Thanks @dkati! I see you opened this issue at https://github.com/googlemaps/android-samples/issues/379 as well. Since this doesn't seem related to the android-maps-utils library specifically, I'm going to close out this issue and the discussion can continue at https://github.com/googlemaps/android-samples/issues/379.
