### ISSUE TITLE
How to load large GeoJson 

### ISSUE THREAD

**Issue by lqhshishen** [googlemaps/android-maps-utils#808]
I have a 200MB size GeoJson and I want to load it in google map. But always end with OOM. 
![image](https://user-images.githubusercontent.com/32257697/102399178-2f101100-3fd8-11eb-9e8f-4e1d65ebb871.png)
Here is my reading code. 
![image](https://user-images.githubusercontent.com/32257697/102399227-3fc08700-3fd8-11eb-8437-320d10ea264b.png)
Here is the error.  
Seems the StringBuilder was too large to append anything. What can I do?

**Comment by barbeau** [comment]
@lqhshishen Have you tried splitting the GeoJSON up into smaller files?

**Comment by lqhshishen** [comment]
> @lqhshishen Have you tried splitting the GeoJSON up into smaller files?

So I should splite the file to multiple GeoJsons?  Seems ok, but this means I should create multiple layers too?

**Comment by barbeau** [comment]
>Seems ok, but this means I should create multiple layers too?

IIRC, yes.
