### ISSUE TITLE
DistanceDemoActivity crashes when using the v3 library

### ISSUE THREAD

**Issue by barbeau** [googlemaps/android-maps-utils#812]
#### Summary

If you use the AMU v3 library (e.g., `'com.google.maps.android:android-maps-utils-v3:2.2.0'` such as in the `v3` demo app variant in https://github.com/googlemaps/android-maps-utils/pull/811) and you run the demo app, when you tap on the "SphericalUtil.ComputeDistanceBetween" button to launch the `DistanceDemoActivity` the app crashes with:

~~~
2021-01-06 16:19:48.796 26534-26619/com.google.maps.android.utils.demo.v3 E/AndroidRuntime: FATAL EXCEPTION: GLViewThreadImpl 1006086
    Process: com.google.maps.android.utils.demo.v3, PID: 26534
    java.lang.IllegalArgumentException: capacity < 0: -40
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:254)
        at com.google.android.apps.gmm.map.internal.vector.gl.zzr.zzb(VertexDataBuilder.java:153)
        at com.google.android.libraries.maps.bv.zzaj.zza(ClientLinesImpl.java:265)
        at com.google.android.libraries.maps.bv.zzan.run(ClientLinesImpl.java:162)
        at com.google.android.libraries.maps.ed.zzag.zzb(EntityRenderer.java:116)
        at com.google.android.libraries.maps.do.zzq.zzb(GmmRenderTarget.java:101)
        at com.google.android.libraries.maps.ed.zzaz.run(GLViewThreadImpl.java:135)
~~~

This appears to be an issue with different behavior in the v3 beta SDK vs v2, so I've opened an issue for the v3 beta SDK at https://issuetracker.google.com/issues/176925192.

I'll leave this open until we get a response from the Maps SDK team to see if we need to change the demo app.

#### Expected behavior

App should not crash, as per when using the Maps SDK v2 based on Google Play Services

```
    gmsImplementation 'com.google.android.gms:play-services-maps:17.0.0'
    gmsImplementation 'com.google.maps.android:android-maps-utils:2.2.0'
```

#### Observed behavior

App crashes

#### Environment details

Samsung Galaxy S8+ w/ Android 9

```
    v3Implementation 'com.google.android.libraries.maps:maps:3.1.0-beta'
    v3Implementation 'com.google.maps.android:android-maps-utils-v3:2.2.0'
```

#### Steps to reproduce

1. Clone the Android Maps Utils project (https://github.com/googlemaps/android-maps-utils) and checkout the `sean/demo/v3beta` branch used in this pull request - https://github.com/googlemaps/android-maps-utils/pull/811
2. Run the demo app `v3Debug` variant
3. Tap on the "SphericalUtil.ComputeDistanceBetween" button to launch the `DistanceDemoActivity`

#### Code example

`mPolyline = getMap().addPolyline(new PolylineOptions().geodesic(true));` seems to be the line that's crashing it

**Comment by wangela** [comment]
Closing since the v3 beta has been [deprecated](https://developers.google.com/maps/documentation/android-sdk/v310-beta).
