### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by Devanshi2101** [googlemaps/android-maps-utils#813]
Found Error 
Could not determine the dependencies of task ':demo:compileDebugJavaWithJavac'.
> Extension not initialized yet, couldn't access compileSdkVersion.

**Comment by barbeau** [comment]
@Devanshi2101 Looks like this is a duplicate of https://github.com/googlemaps/android-maps-utils/issues/800, so I'm going to close this issue.

See more details there, but a workaround is to try changing back to `classpath 'com.android.tools.build:gradle:4.0.2'` in `build.gradle`. If you have any issues with this working please comment in https://github.com/googlemaps/android-maps-utils/issues/800.
