### ISSUE TITLE
How can i get latlng from clickevent when kml layer is on the map?

### ISSUE THREAD

**Issue by natescom** [googlemaps/android-maps-utils#814]
When I add a Kml layer on the map and click on a point where this layer is drawn, the GoogleMap click event is not triggered. How can I solve this? I would like to receive the same LatLng that I receive when GoogleMap's onMapClick is triggered.

**Comment by OlavAa** [comment]
I am also interested in how this can be achieved. I have for now resorted to using long click to capture the position.

**Comment by dkati** [comment]
Click event on KML layer can be triggered via geojson functions.

Click event on map(marker) is not related to KML layers.
