### ISSUE TITLE
Default marker info window is always displayed when using showInfoWindow()

### ISSUE THREAD

**Issue by pxblx** [googlemaps/android-maps-utils#823]
#### Summary

When I use `marker.showInfoWindow()`, the default info window is displayed instead of the custom defined with `collection.setInfoWindowAdapter(new CustomInfoWindowAdapter(getApplicationContext()))`.

#### Expected behavior

Open the custom info window when using `marker.showInfoWindow()`. I'm trying to display the marker custom info window open when starting the activity.

#### Observed behavior

When using `marker.showInfoWindow()`, appears the default info window, but if I close it and reopen it, the custom one appears. I have tried to invert the order of setting the adapter and showing the info window, but I get the same behavior.

#### Environment details

Device: Xiaomi Mi 9
Android version: 10
Library version: com.google.maps.android:android-maps-utils:2.2.0

#### Code example

```
@Override
public void onMapReady(GoogleMap googleMap) {
    MarkerManager markerManager = new MarkerManager(googleMap);
    MarkerManager.Collection collection = markerManager.newCollection();

    collection.setInfoWindowAdapter(new CustomInfoWindowAdapter(getApplicationContext()));
    collection.addMarker(new MarkerOptions()
        .position(new LatLng(37.890331, -4.777600))
        .title("Test title")
        .snippet("Test snippet")).showInfoWindow();
}
```
I'm using too `collection.setOnMarkerClickListener`, `collection.setOnInfoWindowClickListener` and `googleMap.setOnInfoWindowCloseListener` after adding the marker and I have tried to invert the order too.

**Comment by sam2566** [comment]
I am facing same issue.

**Comment by kikoso** [comment]
@pxblx , this seems to work now. There is an example in ClusteringDemoActivity that works:

```
  mClusterManager.getMarkerCollection().setInfoWindowAdapter(new GoogleMap.InfoWindowAdapter() {
            @Override
            public View getInfoWindow(@NonNull Marker marker) {
                final LayoutInflater inflater = LayoutInflater.from(ClusteringDemoActivity.this);
                final View view = inflater.inflate(R.layout.custom_info_window, null);
                final TextView textView = view.findViewById(R.id.textViewTitle);
                String text = (marker.getTitle() != null) ? marker.getTitle() : "Cluster Item";
                textView.setText(text);
                return view;
            }

            @Override
            public View getInfoContents(@NonNull Marker marker) {
                return null;
            }
        });
```

Can you check whether that works out for you, and otherwise post the code from your `CustomInfoWindowAdapter`?
