### ISSUE TITLE
[v3][Clustering] Clustering about 2000 custom markers makes app unreliable

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-maps-utils#830]
at title says.

Although its not present on v2 lib

thats how i initialize it

```
       mClusterManager = new ClusterManager<>(mActivity, mMap);

        List<CustomClusterItem> items = new CustomClusterReader().read(mAllMarkers);
        
        mClusterManager.addItems(items);

        DisplayMetrics metrics = new DisplayMetrics();
        mActivity.getWindowManager().getDefaultDisplay().getMetrics(metrics);
        mClusterManager.setAlgorithm(new NonHierarchicalViewBasedAlgorithm<>(
                metrics.widthPixels, metrics.heightPixels));

        mClusterManager.setRenderer(new MarkerRenderer());
        mClusterManager.setOnClusterClickListener(this);
        mClusterManager.setOnClusterInfoWindowClickListener(this);
        mClusterManager.setOnClusterItemClickListener(this);
        mClusterManager.setOnClusterItemInfoWindowClickListener(this);
        mMap.setOnCameraIdleListener(mClusterManager);

```

custom cluster item is nothing but a custom icon

**Comment by barbeau** [comment]
@dkati Can you reproduce this with the demo app `v3Debug` build flavor? 

I just tried with the [`VisibleClusteringDemoActivity`](https://github.com/googlemaps/android-maps-utils/blob/master/demo/src/v3/java/com/google/maps/android/utils/demo/VisibleClusteringDemoActivity.java) (shown in the demo app as "Clustering: 20K only visible markers") on a Samsung Galaxy S8+ with Android 9 and it didn't seem to perform any differently than the `gmsDebug` build flavor (which uses v2 SDK).

Also, what do you mean by "makes app unreliable"? Do you mean it crashes, or ANRs? And what device and Android version are you testing on?

**Comment by dkati** [comment]
thanks for response.

1. demos are not using custom markers. maybe thats the problem. 
2. i mean ANRs....camera move is really cracky etc...i just migrated from v2....nothing else changed

**Comment by dkati** [comment]
i found out that the problem is not the markers but the polygons.
(i use a marker for every polygon i draw. the amount of polygons is same as markers)

**Comment by barbeau** [comment]
@dkati If you could open an issue for this as well on the Maps SDK v3 beta issue tracker it would help (I think there might already be one?).

**Comment by dkati** [comment]
Sorry for the veeeery late response. i have already opened an issue to Maps SDK guys...i took a response like "its ok. confirmed. thanks" but nothing else, since then

**Comment by barbeau** [comment]
Thanks @dkati. Could you add the link to the Maps SDK issue here?

**Comment by dkati** [comment]
Hello

https://issuetracker.google.com/issues/186806271
