### ISSUE TITLE
GeoJsonLayer is not filling Polygon inside

### ISSUE THREAD

**Issue by Miteshmakwana73** [googlemaps/android-maps-utils#861]
this is what i did so far

```
val layer = GeoJsonLayer(mMap, R.raw.newjson, applicationContext)
            val style: GeoJsonPolygonStyle = layer.defaultPolygonStyle
            style.fillColor = R.color.map_highlight
            style.strokeColor = R.color.map_highlight_border
            style.strokeWidth = 1f
            layer.addLayerToMap()
```

this is my json file. this is created using this [site](https://geojson.io/#map=4/23.40/80.73) 

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              44.47265625,
              12.811801316582619
            ],
            [
              51.5478515625,
              15.368949896534705
            ],
            [
              53.0419921875,
              16.594081412718474
            ],
            [
              52.03125,
              18.93746442964186
            ],
            [
              49.3505859375,
              18.771115062337024
            ],
            [
              46.93359375,
              17.056784609942554
            ],
            [
              45.615234375,
              17.22475820662464
            ],
            [
              43.505859375,
              17.434510551522894
            ],
            [
              43.1982421875,
              16.804541076383455
            ],
            [
              42.978515625,
              16.29905101458183
            ],
            [
              43.2421875,
              13.197164523281993
            ],
            [
              42.978515625,
              15.707662769583518
            ],
            [
              44.033203125,
              12.768946439455956
            ],
            [
              43.5498046875,
              12.85464890558895
            ],
            [
              44.47265625,
              12.811801316582619
            ]
          ]
        ]
      }
    }
  ]
}
```

this is what i am getting 
![device-2021-04-22-182305](https://user-images.githubusercontent.com/38969602/115717476-d7bfea00-a397-11eb-9300-97f74fc78c6c.png)

this is only showing the border outside of the area not filling color inside. is there anything wrong in json file?

why the inside data is not filled already used `style.fillColor = R.color.map_highlight`

the output should be something like this

![Capture](https://user-images.githubusercontent.com/38969602/115717889-3d13db00-a398-11eb-965f-822fcce8cb57.PNG)

if I am using usa.json file from the project then it's working fine 
![device-2021-04-22-184849](https://user-images.githubusercontent.com/38969602/115721156-67b36300-a39b-11eb-8f26-0f6aa924bd3b.png)

show what should i do to get output like this in any country

**Comment by gouravjat** [comment]
Similar issue: [Polygon does not fill correctly; Concave issue?
](https://issuetracker.google.com/issues/35823225)

Waiting for **team google** to resolve this. It seems to be supported just about everywhere(Google Maps Web, iOS), but on Android Maps SDK.

@Miteshmakwana73 My guess is it's due to [self intersecting Polygons](https://demonstrations.wolfram.com/SelfIntersectingPolygons/).

**Comment by kikoso** [comment]
Hi @Miteshmakwana73 . As @gouravjat  pointed out, self-overlapping/intersecting polygons are not currently supported. If you have some flexibility, you can try to adapt the GEOJson file.

I am closing this issue, but let us know if you need further support.
