### ISSUE TITLE
How can I get "zoom", "tilt", "mapTypeId","center" value from an encoded Polyline

### ISSUE THREAD

**Issue by nhatpv-1627** [googlemaps/android-maps-utils#878]
Thanks for stopping by to read my issue!

---

**The problem**

With an "overview_polyline" string that I got from [GoogleMap API directions](https://developers.google.com/maps/documentation/directions/get-directions) looks like this:

yzaaBoyasSgAuCeA}CxLwDlBo@nBs@hBu@bAm@r@i@r@m@~@_Ap@aAfByCpBqDRa@OIwAu@{ImFaDuBiBsAsA}@c@SwCaBwEyCiBoAyFiDeC_BwCkBmDuBaAs@c@]ACAEMIUC{EyCuDsBKKEEMGy@i@oMgIIECMYcAKa@l@mAlA}CxCyGdC{FtAkDhCiHfAsD|FqQv@aDp@aCfBaHvAoFdAgE^aBb@kCvAqLl@gFVaDj@mF|@cH`AgK^_MDqB?_IIqCOqCc@cFMkA]qCcBeIeAcEaA_Dw@oBmAwCo@sAaB{CiCyDc@s@sA_BsAiB_AgA{B_CeB}AqAeAgCoBiCaBqGiF}AmAsBiAeCeAaFkBsDuAyIaDi@OAGCGKKMGQ?UJCDkBJg@Ba@X{BBkB@oC@kB?c@Cw@Kg@MeAe@{@i@q@u@o@{@eAgCaAcCcAcCeCgGcAeC

By using this lib, I can get all the LatLng(s) very well: `val decodedPath = PolyUtil.decode(<overview_polyline>)`

But with the "overview_polyline", has any way I can get more info are  "zoom", "tilt", "mapTypeId", "center".... How can I do this? 
I've tried to decode the "overview_polyline" on the website: http://www.geocodezip.com/blitz-gmap-editor/test5b.html
And these are what I received: 
`
{
    "zoom": 7,
    "tilt": 0,
    "mapTypeId": "hybrid",
    "center": {
        "lat": 20.487486793750797,
        "lng": 74.22363281640627
    },
    "overlays": [
        {
            "type": "polygon",
            "title": "",
            "content": "",
            "fillColor": "#000000",
            "fillOpacity": 0.3,
            "strokeColor": "#000000",
            "strokeOpacity": 0.9,
            "strokeWeight": 3,
            "paths": [
                [
                    {
                        "lat": "21.329035778926478",
                        "lng": "73.46008301171878"
                    },
                    {
                        "lat": "21.40065516914794",
                        "lng": "78.30505371484378"
                    },
                    {
                        "lat": "20.106233605369603",
                        "lng": "77.37121582421878"
                    },
                    {
                        "lat": "20.14749530904506",
                        "lng": "72.65808105859378"
                    }
                ]
            ]
        },
        {
            "type": "polygon",
            "title": "",
            "content": "",
            "fillColor": "#000000",
            "fillOpacity": 0.3,
            "strokeColor": "#000000",
            "strokeOpacity": 0.9,
            "strokeWeight": 3,
            "paths": [
                [
                    {
                        "lat": "21.329035778926478",
                        "lng": "73.46008301171878"
                    },
                    {
                        "lat": "21.40065516914794",
                        "lng": "78.30505371484378"
                    },
                    {
                        "lat": "20.106233605369603",
                        "lng": "77.37121582421878"
                    },
                    {
                        "lat": "20.14749530904506",
                        "lng": "72.65808105859378"
                    }
                ]
            ]
        }
    ]
}
`
This result is shortened. You can take a tour to get whole response at [here](http://www.geocodezip.com/blitz-gmap-editor/test5b.html?encoded=tgarEvbscJ?@VXhAfBtC%7CDtDzFbCtDhCzDjCzDrC~DzAhCl@bAVZXPPDxCv@tB%5EzBd@nCl@v@Zt@d@zAjBnCjEpCtEbCxDnB%60DfB%60D%60DpFvC%7CErCxERZbCvDnC~ERZbCpDj@~@tB%60DtAtB%7C@xA%7CBxDbC%60EXd@dBvCHJ%7CDvGjB~Cd@v@j@z@%60BvCdBtCZf@lChEtA%7CBj@fAXd@pCrEPVFLNV%5Eb@%5CZNN%5EZl@h@t@p@%7C@x@xAnAXXFLP%5Cr@xAjCxF%60AxB%7C@jBv@pBx@dB%60BxDXl@Pb@%5Ex@P%60@RZ%60@XXXVVxEjC%5CRbBr@bA~Bz@nBHRzBxApE%7CDhA%7C@bCfCxBnERh@&parse=encoded)

Thank you for reading!
Best regards,

**Comment by barbeau** [comment]
@nhatpv-1627 To my knowledge polyline encoding/decoding handles only latitudes and longitudes - you can see the algorithm [here](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) which discusses how it encodes only the offset between points. I believe the text result you're seeing from http://www.geocodezip.com/blitz-gmap-editor/test5b.html is additional information added by the site based on the map UI there. But that data isn't contained in the encoded polyline.

You can try decoding the example `overview_polyline` string in the official Google Maps polyline decoder here:
https://developers.google.com/maps/documentation/utilities/polylineutility

...and you'll just see latitudes and longitudes.

**Comment by nhatpv-1627** [comment]
@barbeau Oh, I got it. Thank you so much. I used to need more info like zoom to config the map camera. But now I can handle that issue by myself. 
Thank you for your support!
