### ISSUE TITLE
没有平移滑动吗

### ISSUE THREAD

**Issue by TimelessTyler** [googlemaps/android-maps-utils#885]
Thanks for stopping by to let us know something could be better!

---
**PLEASE READ**

If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/). This will ensure a timely response.

Discover additional support services for the Google Maps Platform, including developer communities, technical guidance, and expert support at the Google Maps Platform [support resources page](https://developers.google.com/maps/support/).

If your bug or feature request is not related to this particular library, please visit the Google Maps Platform [issue trackers](https://developers.google.com/maps/support/#issue_tracker).

Check for answers on StackOverflow with the [google-maps](http://stackoverflow.com/questions/tagged/google-maps) tag.

---

Please be sure to include as much information as possible:

#### Summary

Summarize your issue in one or two sentences

#### Expected behavior

What did you expect?

#### Observed behavior

What did you see instead?  Describe your issue in detail here.

#### Environment details

1. Device make and model, or emulator details
2. Android version
3. Library version and other environment information

#### Steps to reproduce

If you can reproduce using the demo app in the project, it helps us troubleshoot faster.

  1. ?

#### Code example

```
# example
```

#### Stack trace
```
# example
```

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by barbeau** [comment]
@TimelessTyler Sorry, I couldn't decipher the meaning of this using Google Translate. I'm going to close out the issue as there isn't much detail provided, but please feel free to re-open with more detail.
