### ISSUE TITLE
2.2.5 is not available

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-maps-utils#924]
```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsInternalProd'.
> Could not resolve all files for configuration ':app:internalProdCompileClasspath'.
   > Could not find com.google.maps.android:android-maps-utils-v3:2.2.5.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```
while my gradle is 

`implementation 'com.google.maps.android:android-maps-utils-v3:2.2.5'`

Do i miss something?

**Comment by barbeau** [comment]
@dkati Thanks for reporting this.

@arriolac Looks like 2.2.5 hasn't posted to Maven Central yet:
* https://search.maven.org/artifact/com.google.maps.android/android-maps-utils-v3
* https://search.maven.org/artifact/com.google.maps.android/android-maps-utils

Could you take a look?

**Comment by arriolac** [comment]
Odd... I'm positive I pushed this out yesterday. Will have another look and update you

**Comment by arriolac** [comment]
Looks like [version](https://github.com/googlemaps/android-maps-utils/blob/main/build.gradle#L119) is still set at 2.2.4. Probably an issue with the .releaserc config change in #921
