### ISSUE TITLE
Load image from network as cluster icon

### ISSUE THREAD

**Issue by gruelfin** [googlemaps/android-maps-utils#93]
Hello!
what would be the best solution to download an image as cluster icon?
I successfully downloaded an image asynchronously and recreated the clustericon in onClusterRendered. 

The problem with this solution is that I have thousands of markers so there is an Out Of Memory Exception because clusters that are not on screen are rendered. 
My solution to this was to check the bounds of the visible map area after a OnCameraChange event and call ClusterManager.clear() and add only markers that are within these bounds. Because of this, clusters are recreated every time a user moves the map and so clusters are first displayed with the parameters I set in onBeforeClusterRendered and then the images are downloaded again in onClusterRendered which creates a bad user experience obviously for flickering cluster icons and bad performance.

This leads me to these questions:
1. Why are clusters rendered on the whole map and not only in the visible screen area?
2. What is the best way to make cluster icons out of downloaded images?
3. Is it possible to lazy load markers?

Sorry for the long reading and thank you in advance!

**Comment by amatkivskiy** [comment]
You can override method **DefaultClusterRenderer.onClusterRendered(Cluster<T> cluster, Marker marker)** where marker's icon can be changed.
