### ISSUE TITLE
Cluster background custom stroke color

### ISSUE THREAD

**Issue by Runman44** [googlemaps/android-maps-utils#935]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to change the stroke color of a cluster. This is always transparent white (0x80ffffff)

 **Describe the solution you'd like**
A setter for the stroke color for example. 

 **Describe alternatives you've considered**
Creating a custom icon, but this would make so much redundant code

 **Additional context**
Screenshot of cluster with transparent white stroke color
![image](https://user-images.githubusercontent.com/4160534/127135665-279aec38-8dd4-48b1-ae27-fbc3d5d3c859.png)

**Comment by dkati** [comment]
you can always use custom background for cluster icon by doing the following...

On your marker renderer override the onBeforeClusterItemRendered, onClusterItemUpdated, onBeforeClusterItemRendered, onClusterItemUpdated

on there i simply say `marker.setIcon(getClusterIcon())` where 
`
private BitmapDescriptor getClusterIcon(Cluster<CustomClusterItem> cluster) {
            mClusterImageView.setImageDrawable(ContextCompat.getDrawable(mActivity,R.drawable.ic_marker_field));
            Bitmap icon = mClusterIconGenerator.makeIcon(String.valueOf(cluster.getSize()));
            return BitmapDescriptorFactory.fromBitmap(icon);
}
`
        
Thats my full snippet:
        
        `private class MarkerRenderer extends DefaultClusterRenderer<CustomClusterItem> {
        private final IconGenerator mClusterIconGenerator = new IconGenerator(mActivity);
        private final ImageView mClusterImageView;


        public MarkerRenderer() {
            super(mActivity, mMap, mClusterManager);

            @SuppressLint("InflateParams") View multiProfile = mActivity.getLayoutInflater().inflate(R.layout.markers_cluster_container, null);
            mClusterIconGenerator.setContentView(multiProfile);
            mClusterImageView = multiProfile.findViewById(R.id.image);

            ImageView mImageView = new ImageView(mActivity);
            int mDimension = (int) mActivity.getResources().getDimension(R.dimen.cluster_container_size);
            mImageView.setLayoutParams(new ViewGroup.LayoutParams(mDimension, mDimension));
            int padding = (int) mActivity.getResources().getDimension(R.dimen.cluster_container_padding);
            mImageView.setPadding(padding, padding, padding, padding);
            IconGenerator mIconGenerator = new IconGenerator(mActivity);
            mIconGenerator.setContentView(mImageView);
        }

        @Override
        protected void onBeforeClusterItemRendered(@NonNull CustomClusterItem person, MarkerOptions markerOptions) {
            // Draw a single person - show their profile photo and set the info window to show their name
            markerOptions.icon(BitmapDescriptorFactory.fromResource(R.drawable.ic_marker_field));
        }

        @Override
        protected void onClusterItemUpdated(@NonNull CustomClusterItem person, Marker marker) {
            // Same implementation as onBeforeClusterItemRendered() (to update cached markers)
            marker.setIcon(BitmapDescriptorFactory.fromResource(R.drawable.ic_marker_field));
        }

        @Override
        protected void onBeforeClusterRendered(@NonNull Cluster<CustomClusterItem> cluster, MarkerOptions markerOptions) {
            // Draw multiple people.
            // Note: this method runs on the UI thread. Don't spend too much time in here (like in this example).
            markerOptions.icon(getClusterIcon(cluster));
        }

        @Override
        protected void onClusterUpdated(@NonNull Cluster<CustomClusterItem> cluster, Marker marker) {
            // Same implementation as onBeforeClusterRendered() (to update cached markers)
            marker.setIcon(getClusterIcon(cluster));
        }

        private BitmapDescriptor getClusterIcon(Cluster<CustomClusterItem> cluster) {
            mClusterImageView.setImageDrawable(ContextCompat.getDrawable(mActivity,R.drawable.ic_marker_field));
            Bitmap icon = mClusterIconGenerator.makeIcon(String.valueOf(cluster.getSize()));
            return BitmapDescriptorFactory.fromBitmap(icon);
        }

        @Override
        protected boolean shouldRenderAsCluster(Cluster cluster) {
            return cluster.getSize() > SHOULD_CLUSTER_MARKERS_THRESHOLD;
        }
    }`
