### ISSUE TITLE
kml file with refresh from network not working

### ISSUE THREAD

**Issue by IvanKashtelyan** [googlemaps/android-maps-utils#949]
google maps give the possibility to download kml file with the link, and always get the latest file version, but this file not working in android

Steps to reproduce what we have
1. open https://www.google.com/maps/d/u/0/edit?mid=1lmroTF1Pj2Fc1RHLI0eTo4cmsvKEIbW6&usp=sharing or download the attached file
        1) choose export kml/kmz file
        2) choose "refresh data by network" and download it
2. add downloaded kml/kmz file into your maps
3. see the result

Also add the following details:
- Maps SDK Version: 3.1.0-beta
- Maps utils version: 2.2.5
[test(4).zip](https://github.com/googlemaps/android-maps-utils/files/6968150/test.4.zip)

**Comment by dkati** [comment]
i cant understand what you say... whats step 1? where is the 'refresh data by network' ?

**Comment by Akucuki** [comment]
> i cant understand what you say... whats step 1? where is the 'refresh data by network' ?

He meant the first option which is available under "export kml/kmz", update map using the link to kml/kmz file

**Comment by dkati** [comment]
first of all the link is dead...secondly the KML file is not visible even on google earth app (PC) ...

**Comment by Akucuki** [comment]
@dkati You can check my [link](https://www.google.com/maps/d/u/0/edit?mid=1Gg-XNkSK6zQ2nIF2VDgcc2lDql0XgAQ&usp=sharing). Do you mean that this feature doesn't work in general, not only on the android platform?

**Comment by dkati** [comment]
are u trying to download the KML directly from that link, via your android gmaps app?

**Comment by Akucuki** [comment]
@dkati No, I'm trying to use the downloaded file with the selected first option (update the map using the link to kml/kmz file) inside the MapView component in my app. Without selecting that option the resulting file works well, but with it - no data from kml is displayed

**Comment by dkati** [comment]
ok give me some minutes to test it

**Comment by Akucuki** [comment]
@dkati There's no disclaimer saying that I cannot use it on mobile, so why not? My app has permission to use the internet connection

**Comment by IvanKashtelyan** [comment]
@dkati I'm so sorry, missed your first answer. Thank you @Akucuki for describing what I meant.

**Comment by dkati** [comment]
read my reply about `<Link>` tag

**Comment by IvanKashtelyan** [comment]
@dkati do you have any plans to add support to that tag? That's why I'm marked the issue as feature request

**Comment by dkati** [comment]
i am not a gmaps utils maintainer :P although, i would repeat my question.

Why would u need such thing on mobile ?

**Comment by IvanKashtelyan** [comment]
This is was research on what we can do with google maps utils. And I think this feature will helpful when developer use kml file to show smth on the map. And when kml drawing need some updates he can do it without updating the application version.

**Comment by dkati** [comment]
This "issue" can be solved by statically stored KML files to a server and periodically fetch it/update current one 

i can get your point, although i dont think its vital. 

KML/KMZ mounting works really fine on latest google maps (utils and base), at least for me.

**Comment by IvanKashtelyan** [comment]
Yes, I agree with you. It will be helpful only if do not have a backend.

**Comment by kikoso** [comment]
Closing this issue.
