### ISSUE TITLE
Simple way to retrieve a List<T> from ClusterManager<T extends ClusterItem>

### ISSUE THREAD

**Issue by lschlessinger1** [googlemaps/android-maps-utils#96]
For example, Is there an easy way to get a Collection or a List of `MyItem` in the demo? I know that it's possible to get a collection of markers fairly easily.

I want to check if the marker already exists before adding it. (I have an object id field that I assign to each `MyItem`).

**Comment by gepd** [comment]
There is no way to do this yet?

**Comment by Sivious** [comment]
IT seems that there is not a simple way yet. Too strange, you can add items, "remove" items, but cannot retrieve the coleection of items.
