### ISSUE TITLE
High marker counts(in clustering) lag when zooming out

### ISSUE THREAD

**Issue by AidanWelch** [googlemaps/android-maps-utils#960]
#### Summary

When zooming in high amounts then zooming out on a map with thousands of markers there is significant lag as the markers re-cluster.

#### Expected behavior

The markers would near immediately re-cluster to the clusters appropriate for the current zoom.

#### Observed behavior

It seems like instead each "cluster level" is animated in order instead of immediately clustering to current zoom/cluster level.  This leads to drawing and calculating for more markers than is feasible at once.

#### Steps to reproduce

If you can reproduce using the demo app in the project, it helps us troubleshoot faster.

  1. Distribute and cluster 20,000+ markers.
  2. Zoom in significantly.
  3. Zoom out

**Comment by barbeau** [comment]
@AidanWelch Thanks for the report! This sounds a lot like https://github.com/googlemaps/android-maps-utils/issues/744.

Have you tried using the `NonHierarchicalViewBasedAlgorithm`?

For example:

```java
        DisplayMetrics metrics = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(metrics);

        ...
        mClusterManager = new ClusterManager<>(this, getMap());
        mClusterManager.setAlgorithm(new NonHierarchicalViewBasedAlgorithm<MyItem>(
                metrics.widthPixels, metrics.heightPixels));
```

The normal clustering algorithm can be slow with a lot of markers, so the above algorithm only clusters the markers in-view, which should help performance.

More info at https://github.com/googlemaps/android-maps-utils/issues/164#issuecomment-586350932.

**Comment by AidanWelch** [comment]
That resolved it thank you.
