### ISSUE TITLE
Ability to remove ClusterItems

### ISSUE THREAD

**Issue by jpardogo** [googlemaps/android-maps-utils#97]
So far an exception is thrown at this [line](https://github.com/googlemaps/android-maps-utils/blob/0.3.1/library%2Fsrc%2Fcom%2Fgoogle%2Fmaps%2Fandroid%2Fclustering%2Falgo%2FNonHierarchicalDistanceBasedAlgorithm.java#L75)

**Comment by stephenmcd** [comment]
f49f604ee1262105a40ca61bcae90f217f22043c
