### ISSUE TITLE
Performance issue with 500+ polygons

### ISSUE THREAD

**Issue by KristapsKrumins** [googlemaps/android-maps-utils#971]
Google maps for Android native app gets very laggy when 2k polygons are added to the map. I have implemented the same functionality also on the web, where I display 2k polygons on the Google maps. The same mobile device is less laggy when I view the web implementation from browser. Why Google Maps Android SDK is slower and how can I match the performance as I was using the browser. Is there a similar function to https://developer.apple.com/documentation/mapkit/mkmultipolygon ?

**Comment by dkati** [comment]
i have the same issue exactly. they told me that its not gmaps-utils issue but maps itself. i opened an issue to the guys there, but no response 6 months now
