### ISSUE TITLE
Enable lint on CI on every commit?

### ISSUE THREAD

**Issue by barbeau** [googlemaps/android-maps-utils#986]
**Is your feature request related to a problem? Please describe.**
Currently we run GitHub Actions CI on every commit to the project, including PRs:
https://github.com/googlemaps/android-maps-utils/blob/main/.github/workflows/android.yml

However, lint checks are disabled with `-x`:

```
run: ./gradlew build jacocoTestReport -x lint --stacktrace
```

This results in unpredictable behavior where PRs pass but then release builds fail after the PR is merged, such as https://github.com/googlemaps/android-maps-utils/issues/973, because lint is apparently run before release (although I haven't yet tracked down exactly where that happens).

 **Describe the solution you'd like**

@arriolac Should we enable lint on every commit in `android.yml`? Is there a good reason not to do this?

**Comment by arriolac** [comment]
Good catch—we should definitely run lint on `android.yml` as well.

**Comment by barbeau** [comment]
Sounds good, I'll open a PR for this.
