### ISSUE TITLE
[Question-Needs explanation] Is V3 deprecated?

### ISSUE THREAD

**Issue by dkati** [googlemaps/android-maps-utils#988]
Based on [this](https://github.com/googlemaps/android-maps-utils#installation), the V3 maps library is going to be deprecated?
also the link of 'release notes' leads to a google-account-protected website. maybe wrong?

Finally, that means that if my app is based on v3beta
```
//  maps v3
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.google.android.libraries.maps:maps:3.1.0-beta'
    implementation 'com.google.maps.android:android-maps-utils-v3:2.2.6'
```

1. 
i will have to downgrade to v2 main stream versions?

2.
as mentioned to the docs, there will be a 'new' sdk version that will support v3 features....Will that SDK version be released on the same day that v3beta will be completely stopped?

**Comment by dkati** [comment]
also ping @arriolac

**Comment by arriolac** [comment]
You are correct that the V3 beta is deprecated. Your questions are addressed in the release notes though unfortunately I had the incorrect link. Here's the [correct one](https://developers.google.com/maps/documentation/android-sdk/releases#august_18_2021).

> The Beta versions of Maps SDK for Android and iOS are now deprecated and will be fully decommissioned in late 2022. A generally available (GA) version of the Maps SDK for Android and iOS will be made available at least one year prior to the Beta decommissioning.

Will update the README with the correct link.
